### ISSUE TITLE
Broken links on user stats

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#100]
http://tm.teresco.org/user/system.php?u=michih&sys=deua

The first table shows:

> System Stats
> Miles Driven  8097.35 of 8097.35 mi (100.00%) Rank: 1
> Routes Driven 157 of 157 (100%)
> Routes Clinched   157 of 157 (100%) Rank: 1

I don't know why*\* but the 2 last lines are clickable and open a map without user selection:
http://tm.teresco.org/user/mapview.php?u=&sys=deua

*\* Why are they clickable at all? The map of the system is already displayed above. Maybe a system stats (ranking of users) should be linked from system table.
The link in the region table makes sense though.

**Comment by jteresco** [comment]
It seems this was fixed at some point.  I don't see that behavior.  Closing, but will reopen if the behavior can still be replicated.

**Comment by michihdeu** [comment]
yep, clinched.php is called now. And if you deselect the user on system.php, an empty site is loaded. Fine 👍
