### ISSUE TITLE
Graph colors look similar for traveled and untraveled routes

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#105]
It's not an urgent matter but I wanna report it because there might be a modification of computing graphs/drawing maps, please refer to #104 .

Looking on a map with traveled and not traveled segments is sometimes confusing. I think it's caused by:
- multiple drawing of graphs in case of concurrent routes
- multiple drawing because of start and end points

Example A (small region to ease pointing out):
http://tm.teresco.org/user/mapview.php?u=michih&rg=LUX (select "blank" map).

I've not traveled the tier 4 (brown) routes in the city of Luxembourg but there are a lot of waypoints. Due to multiple drawing, it looks "brown" (traveled), especially when you zoom out. I print maps for my travels and it's sometimes really confusing.

Example B:
http://tm.teresco.org/user/mapview.php?u=michih&rg=BEL (select "blank" map).

Zoom in twice. I've traveled the tier 2 ring Bruxelles in the middle but I've not traveled Kortrijk or Gent ring roads in the west. The drawn graphs look simliar though.
A10 near Ostende on the west does not have a concurrent E road. It's brighter than E40 just east of it. 
It's more confusing, when a different layer (GM or Mapnik) is in the background.

Is it possible to draw the graph of the highest tier only?

**Comment by jteresco** [comment]
This has been addressed with #198 and will be live on site soon.
