### ISSUE TITLE
Developer links page

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#106]
I thought I've already requested it but couldn't find an issue... Maybe I just wrote it anywhere on the forum.

I miss a link to http://tm.teresco.org/logs/pointsinuse.log. Maybe from http://tm.teresco.org/devel/datacheck.php?

There might be more "developer" links which are not accessable from the website...

**Comment by jteresco** [comment]
In general, there should be a page of developer links.  I'm not sure where best to put it.

**Comment by michihdeu** [comment]
> I'm not sure where best to put it.

In the footer, next to the "TM on GitHub"

**Comment by michihdeu** [comment]
About developer log files, see http://tm.teresco.org/forum/index.php?topic=1858.msg4737#msg4737, it could be a first step to have a different directory for user log files.

**Comment by jteresco** [comment]
First draft: http://tmtest.teresco.org/devel/tools.php

**Comment by jteresco** [comment]
I'm closing this one.  If there are items to be added to the tools page, please feel free to make suggestions in a new issue here or over on the forum.
