### ISSUE TITLE
Footer navigation (Credits and Sources - Datacheck - Raw Stats - TM on GitHub ) missing in HB

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#107]
The footer is missing in HB: http://tm.teresco.org/hb/ or http://tm.teresco.org/hb/index.php?sys=alba et cetera.

I think it's perfect that it's not displayed on sites with maps though.

**Comment by jteresco** [comment]
I made a couple quick attempts to address this, but I couldn't get the footer to show up all the way at the bottom on all hb pages.  It's back to the way it was for now.

**Comment by michihdeu** [comment]
see #269
