### ISSUE TITLE
Large initial database load when opening Highway Browser with no parameters

### ISSUE THREAD

**Issue by Thing342** [TravelMapping/Web#11]
The server has to display all of the routes in the database, causing the Highway Browser to lag significantly on startup. I would suggest the use of some sort of landing page.

**Comment by jteresco** [comment]
I'm thinking you're referring to mapview.php.  This is a definite problem and will be fixed.

**Comment by jteresco** [comment]
Temporary fix for this: if no QS parameters are passed, it loads only usai.  Still doesn't plot correctly as a map, but at least it doesn't load 300,000+ points from the DB and try to plot them.  mapview.php needs any overhaul anyway so I don't want to put more time into it until I have enough time for the major fixes needed.  Thanks for the issue report.  I'll leave this one open as a reminder.

**Comment by yakra** [comment]
@Thing342, did you mean the hb.php page that lists all the routes?

**Comment by Thing342** [comment]
I meant mapview, but loading hb.php with no params also has a tendency to lag my browser, which could probably be its own issue.
