### ISSUE TITLE
Highway System Status Changes: system codes links don't work if new status is not "preview" or "active"

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#110]
http://tm.teresco.org/devel/updates.php#sysupdates

If the new status is "**split**" or "**extended**" or "**merged**", the link in the "**system code**" column does not work.

However, it's correct that "**merged**" system links should not work because they don't exist anymore.

System codes of "**extended**" and "**split**" systems remain existing though and the link should work.

**Comment by michihdeu** [comment]
I've modified line 46 of \devel\updates.php but I have no permission for uploads to web repository.

`        if (($row['statusChange'] == "active") || ($row['statusChange'] == "preview")) {`

-->

`        if (($row['statusChange'] == "active") || ($row['statusChange'] == "preview") || ($row['statusChange'] == "extended") || ($row['statusChange'] == "split")) {`

**Comment by jteresco** [comment]
Thanks, this is now live.  BTW, anyone should be able to submit a pull request.  If not, let me know and I'll see if I can make it so you can.  Please feel free to close the issue if you agree it's resolved.

**Comment by michihdeu** [comment]
Yep, works. I couldn't submit a pull request last week. Have you changed anything meanwhile?
