### ISSUE TITLE
Mapview: First entry on route list not shown

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#111]
http://tm.teresco.org/forum/index.php?topic=451.0

**Comment by jteresco** [comment]
Quick investigation shows that the HTML table entry for the first line is there, but doesn't show up in browser.  My working assumption is that it's there but obscured by the header row.  Maybe this is just a css fix.

**Comment by jteresco** [comment]
I'm definitely suspecting the css of the table.  I can't investigate further right now, and would be happy to have help from anyone who's got experience in styling.

**Comment by jteresco** [comment]
I was able to put in a couple more minutes and put in a temporary workaround.  I inserted a dummy line in the table that now gets hidden instead of the first real data line.  I'd like to leave the issue open until a better fix is in place.

**Comment by jteresco** [comment]
Somehow the way the CSS plays with various things in these tables continues to baffle me.

You might have noticed that I avoided this problem in the Scrollable Mapview by forgetting about trying to keep the header row always displayed.  This became necessary when I split the header into two rows because we're now showing both visible and overall stats about each route.

So how much do we care about the header row(s) staying visible when the table scrolls down?

**Comment by michihdeu** [comment]
I think it's better to remove the line than keepting it "broken" as it is right now.

**Comment by jteresco** [comment]
You mean broken as in remove the headers because they scroll off the top when you scroll down in Mapview?

**Comment by michihdeu** [comment]
Never mind, I've mistaken the issues!

I have no strong feeling on whether the header row(s) should stay visible or not.

**Comment by jteresco** [comment]
The problematic version of the table is no longer part of Mapview.   Closing.
