### ISSUE TITLE
Data check page

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#117]
The [data check page](http://tm.teresco.org/devel/datacheck.php) is sorted but page loading takes ages because tons of **marked FPs** are loaded. I think they **should be moved to a different page or totally removed** from the site because it's useless there*.

I'm used to enter the region code of regions I've recently modified. The web browser find feature jumps to the first hit which is usually a marked FP. Afterwards, I have to go to the top of the page, mark text and enter the next region code...

http://tm.teresco.org/forum/index.php?topic=335.msg4382#msg4382

*It's useless because it's not required at all for contributors because they are listed in [datacheck.csv](https://github.com/TravelMapping/HighwayData/blob/master/datacheckfps.csv) on GitHub. If anyone wanna have a total list, there's [datacheck.log](http://tm.teresco.org/logs/datacheck.log).

**Comment by jteresco** [comment]
About to install a fix for this that only shows marked FPs if a QS parameter is included, and has a link in the default page that reloads with that QS parameter.
