### ISSUE TITLE
Map labels for intersection/concurrency waypoints on mapview

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#12]
Reminder to self: have "infowindow" text for waypoints that are common to multiple routes have the route name and waypoint label displayed.

**Comment by michihdeu** [comment]
Is this still relevant?

**Comment by jteresco** [comment]
I think so.

**Comment by jteresco** [comment]
A process similar to #198 could find colocated points, and only have the popup attached to the one "on top" of the stacking order, but have that one contain all of the information for the points below.

**Comment by jteresco** [comment]
If Markers are added to the new Scrollable Mapview (See #425), this would be taken care of.  If not, the question will become irrelevant if this new implementation is used to replace all current Mapview functionality.

**Comment by jteresco** [comment]
New Mapview does not support Markers, and there has been no call for it to do so.  Closing.
