### ISSUE TITLE
SR shields display system text if located in a different state

### ISSUE THREAD

**Issue by theFXexpert** [TravelMapping/Web#121]
State highways that are located in a different state show system abbreviations along with the numbers in the shield.
Examples: 
- TN KY1076: http://tm.teresco.org/hb/?r=tn.ky1076
- PA NY17: http://tm.teresco.org/hb/?r=pa.ny017swa

**Comment by rickmastfan67** [comment]
Hey @jteresco, any new about this one?  Seems to be becoming more of an issue do to us now adding a few more 'logical' state extensions into other states.
http://forum.travelmapping.net/index.php?topic=2633.msg11212#msg11212

**Comment by jteresco** [comment]
Nothing from me.  Several hands have been in the shield generation code but none are mine.  I am hoping one or more of those who worked on it before will be willing to do so again and fix this (and any other shieldgen issues).
