### ISSUE TITLE
Loading order start page

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#155]
If a site update fails, the start page is not fully loaded. It's fine but the footer with developer page link is also not loaded. The loading order should be changed (if possible).

**Comment by michihdeu** [comment]
I think that only the following line must be moved to the beginning of index.php!?

`<?php require  $_SERVER['DOCUMENT_ROOT']."/lib/tmfooter.php"; ?>`

I guess it could be just after:
`<?php require  $_SERVER['DOCUMENT_ROOT']."/lib/tmheader.php"; ?>`

**Comment by jteresco** [comment]
This has been substantially addressed by the new site update process that minimizes time when a DB is unavailable.

**Comment by michihdeu** [comment]
The feature is not needed during the site update but only when the update process has failed and DB was NOT created. When the site remains "broken" for some hours.

I think you just need to copy one line, see above.......
