### ISSUE TITLE
Feature: Here map layers

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#176]
Can we get Here map layers as an option?

http://wego.here.com/

**Comment by jteresco** [comment]
Did you see some mechanism by which they make tiles freely available?  I'm not seeing anything about that on the link above.

**Comment by michihdeu** [comment]
The API key seems to be for free: https://developer.here.com/develop/javascript-api?!

**Comment by jteresco** [comment]
Looks like it's a whole API rather than tiles that can be loaded into Google Maps API-based code.  But I could be wrong.

**Comment by michihdeu** [comment]
https://developer.here.com/faqs#licensing-terms

> Public Basic – Free monthly access to Standard features via our web APIs (RESTful and JavaScript) & Starter SDKs for use on both commercial and non-commercial websites, subject to maximum monthly limit of 15,000 platform transactions. This license is only applicable for consumer-facing applications, i.e., applications where the end customers are business users are explicitly excluded. Free plans do not include an SLA. 

>  One request to HERE Platform is equal to one transaction for all features, except in the case of:
>-   Map, satellite and traffic tiles, for which a transaction equals 15 requests.
>...

> If you go over your monthly or annual usage allowance, overage fees will be applied to your account. > Overage fees are charged on a per transaction basis as follows:
> Public Plans:
> $0.0005 USD / transaction
> €0.0005 EUR / transaction

I don't know how many transactions we would have per month...

**Comment by michihdeu** [comment]
It's live on the site, issue can be closed!
