### ISSUE TITLE
Feature: Waze map layers

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#177]
Can we get Waze map layers as an option?

http://www.waze.com/livemap

**Comment by jteresco** [comment]
I'm happy to include any available map layers, but not interested enough to do the research and coding myself.  Bring on those pull requests!

**Comment by jteresco** [comment]
Same question here: do you have information about if and how Waze makes map tiles freely available?

**Comment by jteresco** [comment]
I believe we concluded last summer that inclusion of Waze tiles would violate their ToS.
