### ISSUE TITLE
close InfoWindow by clicking outside it on map

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#178]
One feature I miss from CHM is the ability to close an InfoWindow by clicking outside it on the map. Made things faster. I'd love it if this could be added to the HB, HDX, and mapview.

Not being familiar with the code, I don't know whether this could be added in one place to take care of it in all three or not.

**Comment by jteresco** [comment]
Does it do what you are asking about in our Leaflet implementation?  I moved away from the "info window" idea to use Leaflet's popup mechanism.

**Comment by yakra** [comment]
It works in the HB. [I was unable to test mapview[(https://github.com/TravelMapping/Web/issues/258#issuecomment-392240787).
