### ISSUE TITLE
Feature: Load HB map like it was selected before changing route by using intersecting link

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#179]
http://tm.teresco.org/forum/index.php?topic=2028.msg5975#msg5975

On clicking an intersecting route link in HB, the HB map of the new route should be
- centered with the last waypoint
- zoomed in with the same zoom level and
- loaded with the same map style which was selected before

That means, one would see exactly the same map but just the highlighted route is changed. One could directly proceed browsing at the point one left the previous route.

**Comment by yakra** [comment]
Seconded. I've thought about this several times too; it would be handy, Maybe add some optional QS parameters to the HB, such as `?ll=42.000000,42.000000&zoom=15`

> loaded with the same map style which was selected before

This much, at least, is done now.

**Comment by yakra** [comment]
Still on my wish list. Been thinking of taking a crack at it as I've started to get under the hood in the Web code.

**Comment by michihdeu** [comment]
It's also my most-wanted feature. I would really appreciate if you (or Jim) would have a try 😃

**Comment by yakra** [comment]
I have this feature working on lab2.
Working from a slightly older version of the Web repo, so I'll have to make sure the changed files are still OK with Jim's recent edits.
The EduTools repo also uses the updateMap function, so we'll need some updates there too.
Then, there's the matter of opening up lab2 to the public so y'all can test this feature out... or just submitting a pull request.

**Caveat:**
The links in the Intersecting/Connected Routes list will link to a new map with the same center and zoom as when the popup was first opened. And additional panning or zooming with the popup already onscreen will not change the link.

**URLs:**
Must have *all 3* parameters, `lat=`, `lon=`, and `zoom=`, to work. I'm open to doing this differently if people think it's appropriate. The main thing as that the Intersecting/Connected Routes feature works as described in the OP.

**ToDo:**
I think a "Full Zoom" link at the top of the HB page, that links to the same route without the lat/lon/zoom parameters, would be useful.

**Also?:**
This opens the door to adding `lat=`, `lon=`, and `zoom=` capability to mapview.php, region.php & system.php if anyone would find that useful.

**Comment by michihdeu** [comment]
> ToDo:
> I think a "Full Zoom" link at the top of the HB page, that links to the same route without the lat/lon/zoom parameters, would be useful.

Yep, I had the same thought yesterday

> Also?:
> This opens the door to adding lat=, lon=, and zoom= capability to mapview.php, region.php & system.php if anyone would find that useful.

We could use it in updates.csv one day...... Do you know what I mean?

**Comment by jteresco** [comment]
Excellent!

1) We can easily enough make a yakratest.teresco.org or whatever to have this open to the public for testing.

2) You mean URLs will be required to have all three **or none** of the QS parameters?  I have no problem with that.

3) Corresponding changes to HDX is a little tricky at the moment, as I have huge changes in the master branch of the repository now that are not ready to go live on the main site.  I was able to patch up the production HDX with minor changes needed for the connection highlighting changes of the past week.  I hope to get the summer HDX features cleaned up this week to the point where they can become the production version.

**Comment by michihdeu** [comment]
> We can easily enough make a yakratest.teresco.org or whatever to have this open to the public for testing.

That would be all on the same CPU, wouldn't it? A single point of failure...

**Comment by jteresco** [comment]
> > We can easily enough make a yakratest.teresco.org or whatever to have this open to the public for testing.
> 
> That would be all on the same CPU, wouldn't it? A single point of failure...

I'm thinking of it in this case as a staging area for @yakra's version.  

In the longer term, it would be nice to have instances of TM configured on multiple servers in multiple places.

**Comment by yakra** [comment]
>    We can easily enough make a yakratest.teresco.org or whatever to have this open to the public for testing.

I plan on opening up lab2 fairly soon. Just gotta become a little more familiar with firewalld.

>    You mean URLs will be required to have all three or none of the QS parameters? I have no problem with that.

Pretty much, yes. None of the QS parameters = existing behavior. This would be used in the "Full Zoom" link mentioned above. If only one or two of the parameters are included, it would behave as is none were, and we'd get a "regular" HB.

>    Corresponding changes to HDX is a little tricky at the moment, as I have huge changes in the master branch of the repository now that are not ready to go live on the main site. I was able to patch up the production HDX with minor changes needed for the connection highlighting changes of the past week. I hope to get the summer HDX features cleaned up this week to the point where they can become the production version.

The only changes we'd need for EduTools would be the existing calls to `updateMap()` becoming `updateMap(null,null,null)` instead.

**Comment by michihdeu** [comment]
To be honest, I just thought about next weekend ;)

> In the longer term, it would be nice to have instances of TM configured on multiple servers in multiple places.

Seconded. For instance, if there is any problem while you are traveling, the site might be down for weeks. Dunno whether it's possible to redirect to a different address in case of a failure? The forum would be down anyway.

**Comment by yakra** [comment]
Lab2 is now publically accessible, so we can test this feature out. Link is on the forum.

**Comment by yakra** [comment]
I'd close this in favor of https://github.com/TravelMapping/EduTools/issues/292 now, but I don't have the same permissions here in Web that I have in HighwayData / DataProcessing / EduTools.

**Comment by michihdeu** [comment]
@yakra is anything left to be implemented or can we close the issue?

**Comment by yakra** [comment]
Closing this got lost in the shuffle. Doing so now.
