### ISSUE TITLE
Bing map layers

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#19]
Can we get Bing map layers as an option?

**Comment by michihdeu** [comment]
I think more and more new road maps are getting popular. Maybe we can add more layers. For instance, according to [this ranking](http://www.nydailynews.com/autos/street-smarts/top-5-navigation-maps-apps-drivers-article-1.2314257), Top 3 is:
1. http://wego.here.com/
2. http://maps.google.com/
3. http://www.waze.com/livemap

**Comment by a30peng** [comment]
A few unclear issues about whether or not we can integrate bing tiles while maintaining their terms of service.

Bing TOS
https://www.microsoft.com/maps/product/terms.html
Section 3.P is unclear

Google TOS
https://developers.google.com/maps/terms
Section 10.1.a is also unclear

**Comment by a30peng** [comment]
WEGO HERE maps only offer a 90-day API key
https://developer.here.com/

Waze maps TOS prohibits the reuse of their maps from what I can tell, at least without consent.
https://www.waze.com/legal/tos

USE RESTRICTIONS

"You may not, whether yourself or through any other means or person :  (i) copy, modify, adapt, translate, reverse engineer, decompile, or disassemble any portion of the Content included in the Service and/or Site, or in any way or publicly display, perform, or distribute them;"

**Comment by jteresco** [comment]
Closing this one, as with our conversion to Leaflet, we'll likely go with a subset of the tiles in https://github.com/leaflet-extras/leaflet-providers .  I believe we want to remain very careful about honoring terms of service for any provider we use.
