### ISSUE TITLE
Some incorrect LIST name entries in the HB

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#191]
http://tm.teresco.org/forum/index.php?topic=2111.0

**Comment by yakra** [comment]
Is this due to the Banner field being limited to 3 characters?

**Comment by yakra** [comment]
http://tm.teresco.org/forum/index.php?topic=2325

**Comment by jteresco** [comment]
Am I correct that this is now addressed with the expansion to 6 characters for the banner field?

**Comment by yakra** [comment]
I believe so.

**Comment by jteresco** [comment]
OK, let's close it up.
