### ISSUE TITLE
Special characters not shown correct when they are cut

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#195]
http://tm.teresco.org/user/system.php?sys=eursf

Primer Cinturón de San Sebasti�
Mіnskaja Kaĺcavaja Aŭtamabі�
...

It's not a csv issue, see HB:
http://tm.teresco.org/hb/?r=esp.gi020
http://tm.teresco.org/hb/?r=blr.mkad

It seems to happen because the text is cut within the special character which allocates more than 1 byte...

Why are the texts cut at all? If they wouldn't be cut, the problem would be gone...

**Comment by jteresco** [comment]
I first thought it must be that the entries were too big for the DB field (48 characters), but the entire name is stored there.  I am not seeing anything in system.php that would try to truncate...  Hmm...

**Comment by jteresco** [comment]
No, wait, the DB field used here is actually only 32 characters.  I was looking at routes.city, and this query uses connectedRoutes.groupName.  I'll expand it for the next site update.

**Comment by michihdeu** [comment]
Works, thanks 👍
