### ISSUE TITLE
Save map type preference

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#197]
http://tm.teresco.org/forum/index.php?topic=2116.msg6889#msg6889

Feature request: retain default map tile preference in a browser cookie.

**Comment by jteresco** [comment]
This is complicated by the fact that the control that chooses map tiles is created by Google Maps, not TM code.  There's probably an event handler we could use to find out when someone changes the selection.

**Comment by yakra** [comment]
I bet that's the case. CHM retained map tile preference in a cookie. So, *however* it was done, it can be done.

**Comment by michihdeu** [comment]
This would be really helpful now we have (the ugly) Leaflet "Stamen Terrain" as default...

**Comment by jteresco** [comment]
This is likely easier with Leaflet.  I hope to take a look at the possibility soon.
