### ISSUE TITLE
Feature: Draw concurrent polylines only once

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#198]
There should be a way to load routes traveled only because:

- it's sometimes hard to distinguish traveled and untraveled graphs because color codes look similar depending on the zoom level
- it takes ages to load maps of more than one region, for instance, [my map of European countries traveled](tm.teresco.org/user/mapview.php?units=km&u=michih&rg=AND,AUT,BEL,CHE,CZE,DEU,DNK,ESP,EST,FRA,FIN,HUN,ITA,LTU,LUX,LVA,NLD,NOR,POL,PRT,ROU,SWE).

**Comment by yakra** [comment]
The 1st bullet point can be taken care of by [specifying custom colors in the mapview URL](http://tm.teresco.org/user/mapview.php?units=miles&rg=NS&u=ua747sp&colors=tier1:rgb(128,210,255):rgb(0,160,255);tier2:rgb(128,210,255):rgb(0,160,255);tier3:rgb(128,210,255):rgb(0,160,255);tier4:rgb(128,128,128):rgb(64,64,64);tier5:rgb(224,144,86):rgb(224,0,0))

The 2nd bullet point, having fewer polylines/overlays to plot/draw could be a Good Thing...

**Comment by michihdeu** [comment]
> The 1st bullet point can be taken care of by specifying custom colors in the mapview URL

Well, yes... But my specific problem is when teal and green (eursf and eure) routes are concurrent and the zoom level is very low. It looks like traveled... The main issue is the 2nd bullet point though...

**Comment by yakra** [comment]
It seems that when a segment is clinched, it's marked with just one polyline, of the highest tier.
When a segment is unclinched, multiple polylines are drawn, leading to the issue in @michihdeu's post above.
Perhaps just having one polyline for a single segment, whether clinched or not, would be a Good Thing.

**Comment by yakra** [comment]
Looks like my "clinched = just one polyline" assumption in my previous post was incorrect.

Look at @michihdeu's mapview of DEU, POL & DNK:
[custom colors](http://tm.teresco.org/user/mapview.php?units=miles&rg=DEU,POL,DNK&u=michih&colors=tier1:rgb(100,100,255):rgb(0,0,220);tier2:rgb(100,200,200):rgb(0,140,160);tier3:rgb(100,200,100):rgb(0,224,0);tier4:rgb(224,162,162):rgb(240,150,115);tier5:rgb(255,216,100):rgb(232,176,0))  |  [default colors](http://tm.teresco.org/user/mapview.php?u=michih&units=miles&rg=DEU,POL,DNK)

**First, look at Warsaw, Poland...**
There's relatively good teal/green contrast here.
* On the E67/S8War concurrency north of Warsaw, S8War *(tier 2)*, overlays teal atop the green of E67 *(tier 3)*.
* On the E67/DK8Mar concurrency as the route turns more northward, E67 *(tier 3)* overlays green, presumably atop the lightsalmon of DK8Mar *(tier 4)*.

**Next, look northeast of Kolding, Denmark**
at the triangle formed by E20, E45, and OstMot.
* To the west, TauMot & SonJysMot *(tier 2)* overlay teal atop the green of E20 & E45 *(tier 3)* respectively.
* On the eastern leg, OstMot has no concurrency, and overlays teal onto no other color.

There is a noticeable contrast to *teal-over-green* vs. just straight teal.

**Comment by jteresco** [comment]
Nothing in the code now stops all concurrent routes on a segment, either clinched or unclinched, from being drawn.  They're layered on top of each other by tier order.  I'd have to think about how much work it would be to avoid drawing all except the "top-level" if that's the general consensus for a preferred behavior.

**Comment by yakra** [comment]
> They're layered on top of each other by tier order.

This can get tricky. What to do about concurrencies where different systems of the same tier render in different colors? Consider usaib (green) & usaus (red), both tier 2.
http://tm.teresco.org/user/mapview.php?units=miles&u=okroads&rg=OK
• I-40BLSay / US283 (W end of state): I-40BLSay gets rendered on top, in green.
• I-40BLElR / US81 (a bit W of OKC metro): US81 gets rendered on top, in red.
• I-40BLSal / US59 / US64 (E end of state): I-40BLSal gets rendered on top, in green.
So, right now, the results we get aren't consistent.
Not *too* big a deal AFAIC, but worth considering.
Do we put in some thought & effort into ensuring the results are expected/desired/sensible? Or content ourselves with a simpler "roll-the-dice" approach similar to what we have now, if we decide that OK/good enough?

**Comment by yakra** [comment]
More food for thought:
Fewer polylines to render could mean less CPU & RAM usage, and less likelihood of overwhelming a browser.

It's been fun the past couple days, messing around with michih's DEU,POL,DNK mapview while testing out new color schemes. Each instance uses about 600 MB of RAM. On top of that, I'd frequently load it into 3 (or even more) browser tabs. That adds up fast. It's when closing a browser tab that things get really interesting -- RAM usage increases substantially for a bit before the memory is finally released. (I guess class destructors temporarily need a bit more memory to do their thing?...) This can send me a gig or two into Swap File land, and my browser can all but seize up (and system responsiveness overall becoming sluggish for a bit) while this is all paged in & out, added to Swap & then released...

I'm considering upgrading my RAM to the maximum my machine supports, 8 GB. This will leave me a *little* headroom. But not as much as I might like...

**Comment by michihdeu** [comment]
> This can get tricky. What to do about concurrencies where different systems of the same tier render in different colors? Consider usaib (green) & usaus (red), both tier 2.

I think drawing the line with the color of the highest tier (lowest number) should work.
There are three options for the rarely found exception:
- Avoid having two concurrent routes of the same tier by splitting routes (including data check error)
- Draw the line only once, first come, first serve
- Draw the line twice and have funny color as-is today

The exception doesn't stop any general solution by tiers...

**Comment by yakra** [comment]
All-in-all, agreed.
Option 1: not sure what you mean here...
I prefer option 2, neater & cleaner & requires less code than making an exception to draw a line twice.

(As is now, for *traveled* segments, drawing twice looks almost like a first-come-first-serve option, due to traveled segments having greater opacity. The more transparent untraveled segments are likely to yield the funny colors.)

Actually, how about this for an option 4?
* Create a color hierarchy: blue > teal > green > red > magenta > lightsalmon > brown > yellow.
If a line segment is part of two different same-tiered systems, then pick whichever color is highest in this hierarchy.
Imagine a route segment on a concurrency shared by a usaib route, a usaus route, and a usausb route. That's two Tier 2 systems and one Tier 3 system. Thus Tier 3 gets disregarded. Of the two Tier 2 systems, one is green and the other red. Green is higher in the hierarchy, and so the segment gets rendered in green.

**Comment by michihdeu** [comment]
> Option 1: not sure what you mean here...

Not allow to have concurrent segments of the same tier. Split routes etc.

Sure, option 2 is the best but everything depends on the code. I think option 4 might be quite similar to option 2... However, we can discuss a lot here but without understanding how the code works... It's quite useless...

**Comment by yakra** [comment]
[Kazakhstan](http://tmtest.teresco.org/user/mapview.php?units=miles&rg=KAZ&u=yakra) is an interesting case. We have both *asiah* (red;3) and *eure* (green;3), and two lightsalmon;4 systems thrown into the mix. There's a lot of multiplexing here, with some segments carrying 2, 3, 4, or as many as 7 routes. With so many segments getting multiple red & green overlays in no predictable order, the end result is a bit of a "gradient" effect, with no clear delineation of traveled/untraveled/this-color/that-color.

This simple [clinched/unclinched map](http://tm.teresco.org/user/mapview.php?units=miles&rg=KAZ&u=ua747sp&colors=tier1:rgb(128,128,128):rgb(255,0,0);tier2:rgb(128,128,128):rgb(255,0,0);tier3:rgb(128,128,128):rgb(255,0,0);tier4:rgb(128,128,128):rgb(255,0,0);tier5:rgb(128,128,128):rgb(255,0,0)) illustrates how multiple polylines can create a "boldface" effect, that can be (on color maps) confused with a map of routes traveled.

**System Maps:**
Just saving these links here... [asiah](http://tmtest.teresco.org/user/mapview.php?units=miles&rg=KAZ&u=ua747sp&sys=asiah) [eure](http://tmtest.teresco.org/user/mapview.php?units=miles&rg=KAZ&u=ua747sp&sys=eure) [cism](http://tmtest.teresco.org/user/mapview.php?units=miles&rg=KAZ&u=ua747sp&sys=cism) [kaza](http://tmtest.teresco.org/user/mapview.php?units=miles&rg=KAZ&u=ua747sp&sys=kaza)

@jteresco wrote:
> if that's the general consensus for a preferred behavior

unscientific survey, sample size = 1: I prefer that behavior. :)

> I'd have to think about how much work it would be to avoid drawing all except the "top-level"

@michihdeu wrote:
> we can discuss a lot here but without understanding how the code works...

Graph file generation combines segments from multiple routes into single edges. Somehow. ;)
(So somewhere, in *some* specific context, Jim has an implementation of this concept down. :) )
Though, I believe this is part of the data processing / site update process, not so much Web. Or, does it rely on the DB at all? *(relevant forum discussion link(s)?)*

I see needing a DB element that keeps track of individual line segments. Is such a thing already included?

Attempting to get under the hood a bit and understand the code a bit...

http://tm.teresco.org/lib/waypoints.js.php?units=miles&u=yakra&rg=DC&sys=usadc
> function waypointsFromSQL() {
    newRouteIndices[0] = 0;
routeTier[0] = 4;
routeColor[0] = 'brown';
routeSystem[0] = 'usadc';
waypoints[0] = new Waypoint("I-295/695",38.869618,-76.987634)
waypoints[1] = new Waypoint("PenAve",38.875198,-76.974592)
waypoints[2] = new Waypoint("ECapSt",38.889764,-76.958477)
waypoints[3] = new Waypoint("BenRd",38.895575,-76.95204)
waypoints[4] = new Waypoint("NHBurAve",38.902397,-76.943741)
waypoints[5] = new Waypoint("NashSt",38.907536,-76.938238)
waypoints[6] = new Waypoint("DC/MD",38.912265,-76.934123)
traveler = 'yakra';
segments[0] = 309566; // route=dc.dc295
segments[1] = 309567; // route=dc.dc295
segments[2] = 309568; // route=dc.dc295
segments[3] = 309569; // route=dc.dc295
segments[4] = 309570; // route=dc.dc295
segments[5] = 309571; // route=dc.dc295
mapClinched = true;
    genEdges = true;
}

http://tm.teresco.org/lib/waypoints.js.php?units=miles&u=yakra&rg=ME&sys=usanh
> function waypointsFromSQL() {
    newRouteIndices[0] = 0;
routeTier[0] = 4;
routeColor[0] = 'brown';
routeSystem[0] = 'usanh';
waypoints[0] = new Waypoint("ME113_S",44.160434,-70.985295)
waypoints[1] = new Waypoint("ME/NH",44.164107,-71.004754)
newRouteIndices[1] = 2;
routeTier[1] = 4;
routeColor[1] = 'brown';
routeSystem[1] = 'usanh';
waypoints[2] = new Waypoint("NH/ME",43.684058,-70.98052)
waypoints[3] = new Waypoint("ShoAcrRd",43.687402,-70.97845)
waypoints[4] = new Waypoint("MouRd",43.693205,-70.977951)
waypoints[5] = new Waypoint("BaiRd",43.701133,-70.981829)
waypoints[6] = new Waypoint("ME/NH",43.711855,-70.982097)
traveler = 'yakra';
segments[0] = 365641; // route=me.nh113b
segments[1] = 366284; // route=me.nh153
segments[2] = 366285; // route=me.nh153
segments[3] = 366286; // route=me.nh153
segments[4] = 366287; // route=me.nh153
clinched[0] = 365641; // route=me.nh113b
clinched[1] = 366284; // route=me.nh153
clinched[2] = 366285; // route=me.nh153
clinched[3] = 366286; // route=me.nh153
clinched[4] = 366287; // route=me.nh153
mapClinched = true;
    genEdges = true;
}

What is this segmemts array, and what are these integers getting plugged into it?
https://github.com/TravelMapping/Web/blob/master/lib/waypoints.js.php line 163:
> echo "segments[$segmentIndex] = {$row['segmentId']}; // route={$row['root']}\n";

Hmm... what is this **'segmentId'**?

**Comment by jteresco** [comment]
Another thing to revisit here with Leaflet maps.  I had to change up some of what we do since the only way to get one polyline on top of another is to add the one you want on the bottom before the one you want on the top.  I was just back in waypoints.js.php for the first time in a while to make this happen.  As we do it now, I don't see a really easy way to draw only the polylines for the highest tier segment on a concurrent route.  There's probably some SQL magic that could implement that restriction, but I'm still pretty weak at coming up with clever SQL queries.

**Comment by yakra** [comment]
A case of real-world confusion:
http://forum.travelmapping.net/index.php?topic=2514

**Comment by jteresco** [comment]
An attempt to fix this is live on tmtest2.teresco.org . Please take a look.  I worry that it's too slow, since its the JS code that's searching for any previously-plotted concurrent segment and making the previous one 100% transparent.  It is |E|^2 for this first attempt.  If this is deemed to be an improvement, I can work on efficiency (definitely possible to improve).

**Comment by michihdeu** [comment]
Thanks! I thought the featue might help for two purposes and it's definitely an improvement to distinguish traveled and untraveled graphs (I had a try, untraveled teal/green routes do no longer look like teal traveled) but it's (currently) bad for loading maps. LOL.

But you already wrote that it's worse but there's room for improvement.

**Comment by yakra** [comment]
Does the DB contain a list of highway segments?
https://github.com/TravelMapping/Web/issues/198#issuecomment-323846152
> What is this segments array, and what are these integers getting plugged into it?
https://github.com/TravelMapping/Web/blob/master/lib/waypoints.js.php line 163:
> `echo "segments[$segmentIndex] = {$row['segmentId']}; // route={$row['root']}\n";`
> Hmm... what is this 'segmentId'?

Would one possibility to speed things up (at the expense of a larger DB size?) be to store info on each segment's tier & color?

**Comment by jteresco** [comment]
I've made some efficiency improvements and installed on tmtest.teresco.org .  It's similar to performance without the code to show only the last polyline drawn on each segment where there is a concurrency.  The slowness on larger data sets is now more from the slower database access to do the ordering of routes in the table based on CSV order (#276).

**Comment by jteresco** [comment]
Timing notes: 

updateMap runs for 1112870 ms loading country=USA using the property lookup based on segment length.

**Comment by jteresco** [comment]
Idea to try for this if the current approach can't be made efficient enough: draw all segments in the first loop, then once the map is displayed, another loop looks for concurrencies and makes them transparent.

**Comment by jteresco** [comment]
But ultimately, @yakra's suggestion of putting information into the DB might be the best way here.  The concurrencies are all detected in the Python code anyway, but not all of that information ends up in the DB in a way it can be used for this purpose.

**Comment by jteresco** [comment]
And the likely final solution keeps lists of matches with the properties, and this runs for country=USA in only 4809 ms!  Worth an extra second on a large map like that, it seems.

**Comment by jteresco** [comment]
This is live on the main site.  Please open new issues if any problems are found with this.
