### ISSUE TITLE
HB: add direct link to interrupted connected routes

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#199]
A feature similar to https://github.com/TravelMapping/Web/issues/192 but for **interrupted** routes, see forum: http://tm.teresco.org/forum/index.php?topic=1888.

Interrupted connected routes must be processed first, see https://github.com/TravelMapping/DataProcessing/issues/55

**Comment by jteresco** [comment]
Is the current "show associated routes" not good enough for this?

**Comment by michihdeu** [comment]
It shows the route but it often shows much **more routes because it shows all routes by name only**. I've used it yesterday for PR9 in Denmark but PR9 in Puerto Rico was also output. European motorways usually begin with A and you'll get a long list...

**Comment by michihdeu** [comment]
https://forum.travelmapping.net/index.php?topic=3697.msg19498#msg19498

**Comment by jteresco** [comment]
The HB cannot meaningfully supply such routes unless/until we augment the data to indicate which separate connected routes are interrupted pieces of the same route.

**Comment by michihdeu** [comment]
> unless/until we augment the data

which is still possible.... if there would will.... and consensus on a definition... but it seems, there isn't https://forum.travelmapping.net/index.php?topic=3700
