### ISSUE TITLE
Feature: Kilometer / mile conversion (default value and manual switching)

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#20]
It should be possible to switch b/n miles and kilometers

Previous discussion:
julmac: http://www.aaroads.com/forum/index.php?topic=17071.msg2115971#msg2115971
si: http://www.aaroads.com/forum/index.php?topic=17071.msg2116074#msg2116074
jim: http://www.aaroads.com/forum/index.php?topic=17071.msg2116086#msg2116086

michih: I'd prefer having a default value (like si's proposal in list file?) and a possibility to switch manually. Jim's proposal "entry in countries.csv indicating the default units" sounds great but the stats main page usually displays data of more than one country and US+CA with partial miles and partial km would be quite odd!

**Comment by jteresco** [comment]
Any suggestions for a metric equivalent of the word "mileage"?  "kilometerage" doesn't seem like a word.

**Comment by jteresco** [comment]
At the moment, I'm going with "distance (miles)" and "distance (km)" but feel like we can do better.

**Comment by jteresco** [comment]
This is live on site.  Please comment on the forum or open a new issue if you see problems other than the known issue with the thousands separators breaking the table sorting.
