### ISSUE TITLE
Shield page should only show one shield if there is more than one route

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#200]
If there is more than one route which has the same shield, connected route or interrupted connected route, **only one shield** should be displayed on http://tm.teresco.org/shields/clinched.php. See forum: http://tm.teresco.org/forum/index.php?topic=1888

Interrupted connected routes must be processed first, see https://github.com/TravelMapping/DataProcessing/issues/55

**Comment by michihdeu** [comment]
http://forum.travelmapping.net/index.php?topic=3604.msg18664#msg18664

The link on the only remaining shield must direct to the multi-region route. This would also fix https://github.com/TravelMapping/Web/issues/101

**Comment by jteresco** [comment]
Are we good on this now?

**Comment by michihdeu** [comment]
I didn't realize that it was changed. Works as intended. Closing 😄
