### ISSUE TITLE
Bug: Overall User Stats routes % active+preview incorrect

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#201]
My current stats: http://tm.teresco.org/user/?units=miles&u=michih

> Routes Traveled | 1295 of 20315 (6.37%) Rank: TBD | 2053 of 30403 (10.11%) Rank: TBD
> Routes Clinched | 717 of 20315 (3.53%) Rank: TBD | 902 of 30403 (4.44%) Rank: TBD

The active+preview calculation is wrong because the total number of routes from active systems (20315) is used instead of active+preview (30403).

**Comment by jteresco** [comment]
Fix live on site, thanks.
