### ISSUE TITLE
Exclude VISIBLE_DISTANCE data check error for ACTIVE systems

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#205]
It's just clutter, but it's useful when building systems.

Error should only be output on [url=http://tm.teresco.org/devel/datacheck.php]datacheck.php[/url] for systems in preview and in development.

http://tm.teresco.org/forum/index.php?topic=2066

**Comment by yakra** [comment]
Safe to close this issue now, yes?

**Comment by michihdeu** [comment]
Close
