### ISSUE TITLE
HB: Intersecting/Concurrent Routes at full beltway "ends", etc.

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#207]
[IN I-465](http://tm.teresco.org/hb/index.php?r=in.i465) has two points at (39.703423°, -86.108265°), one for each "end" of the beltway.
Click on either of these points ("I-65" or "53") in the HB, and you'll see eight Intersecting/Concurrent Routes listed.
For each of these routes, click on the corresponding point in the HB, and you'll see *nine* Intersecting/Concurrent Routes, including listing I-465 *twice*.
I'm sure this is because I-465 has two points that intersect here.

The same behavior shows up, as expected, with
AB AB2 535
Everything intersecting the ends of Texas Loops 7, 8, 12, 1604, and certainly countless other TXLps.
NB NB850 NB845

Compare and contrast NB NB772 NB772_E NB772_W:
The HB is evidently smart enough to know that NB772 intersecting itself is irrelevant, and not list NB772 under Intersecting/Concurrent Routes.
However: the "Intersecting/Concurrent Routes" line is still **there** in the InfoWindow, albeit *not listing anything*. As opposed to there being no "Intersecting/Concurrent Routes" text at a point where no other routes connect.

**Comment by yakra** [comment]
And I'm incredibly pleased that I just submitted issue #207! :grin:

**Comment by jteresco** [comment]
Interesting.  The only check currently there is to filter out the route itself.  I hesitate to put in an extra check to remove duplicates in the PHP or JS code which could slow things down for larger routes.  If there's an easy way to do it in the SQL query that's probably more efficient.

**Comment by jteresco** [comment]
And yes, there is a way for SQL to do it.  It's live on tmtest.  Please try it a bit and I'll put it on the production server soon.

**Comment by yakra** [comment]
Looks good, thanks!

**Comment by jteresco** [comment]
Installing onto the main site and closing issue.
