### ISSUE TITLE
HB: Intersecting/Concurrent Routes and case sensitivity

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#208]
http://tm.teresco.org/hb/index.php?u=&r=me.us001altban
is not the same as
http://tm.teresco.org/hb/index.php?u=&r=me.us001AltBan
In the latter case, clicking on any waypoint with an intersecting or concurrent route (EG, ColRd) lists "ME US1 Alt(Bangor, ME)" among the Intersecting/Concurrent Routes.
Oddly, in light of this, clicking on a waypoint with nothing intersecting/concurrent (EG, CoveRd) yields the "expected" behavior, of listing nothing.

Similarly,
http://tm.teresco.org/hb/index.php?units=miles&u=&r=ny.ny017k
is not the same as
http://tm.teresco.org/hb/index.php?units=miles&u=&r=ny.ny017K

**Comment by jteresco** [comment]
Fix is live on site. "r=" QS param values are now converted to lowercase on load, so their case will match that in root entries in the DB, and the check that skips the route itself when finding intersecting routes will work as intended.

**Comment by yakra** [comment]
Out of curiosity, how was it that routes with nothing intersecting (E.G. ME US1AltBan CoveRd) still showed nothing?

**Comment by jteresco** [comment]
There's a preliminary check done that only continues if there's more than one concurrent point in the DB.  So any point like that would never go through and compare for non-matching roots to populate the list of intersecting points.
