### ISSUE TITLE
Feature: User-specific default data

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#21]
There are many options for displaying user data. There should be a user-specific default.

Previous discussion:
michih: http://www.aaroads.com/forum/index.php?topic=17071.msg2116069#msg2116069
si: http://www.aaroads.com/forum/index.php?topic=17071.msg2116074#msg2116074
thing342: http://www.aaroads.com/forum/index.php?topic=17071.msg2116088#msg2116088

Relevant data:
- km/miles
- colors (corresponding to tiers)
- map type
- selected stats columns
- map with or w/o in-dev systems
- ...

**Comment by jteresco** [comment]
Cookies seem like the way to go here.

**Comment by michihdeu** [comment]
more or less a duplicate of #351 
The solution should be cookies there while it was intended to have it anyhow else here AS A DEFAULT.
