### ISSUE TITLE
Show current location on maps

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#211]
I'd like to see if we can enable a "show current location" on maps when the browser can provide such information.

**Comment by jteresco** [comment]
https://developers.google.com/maps/documentation/javascript/geolocation

**Comment by jteresco** [comment]
Leaflet's Map has a locate function to investigate.  Might require https.

**Comment by yakra** [comment]
Is https in fact required?

**Comment by jteresco** [comment]
The Leaflet documentation links to this page:

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by jteresco** [comment]
Not sure why this remained open.  Closing.
