### ISSUE TITLE
HB: Add user traveled length and percent

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#218]
Add an entry for the amount the selected user has traveled on the route view of the HB.

**Comment by yakra** [comment]
Maybe have it take the place of "Average Traveled", and have that only show up when no user (*&u=&*) is specified?

**Comment by yakra** [comment]
Concurrently, this might be an opportunity to clean up the Route Stats table.
I like the somewhat cleaner appearance of CHM's HB.  Compare...
http://tm.teresco.org/hb/?u=yakra&r=me.me206
http://cmap.m-plex.com/hb/hwymap.php?u=yakra&r=me.me206
In the case of ME206, the "ME ME206" label below the shield looks about the same.
But wait, there's more...
http://tm.teresco.org/hb/?u=yakra&r=tn.us041altnas
http://cmap.m-plex.com/hb/hwymap.php?r=tn.us041altnas
In the case of TN US41AltNas, we see that CHM conveniently includes the LIST Name right below the shield, whereas TM spells out the City name.
This has led to confusion [for at least one user](http://tm.teresco.org/logs/aaroads.log).
A layout more similar to CHM's format, without the LIST Name hidden down in the Route Stats table, would be nicer looking and less confusing IMO.

> how up when no user (&u=&) is specified?

Speaking of which, the HB has been missing the old solid blue polyline for a null user for a while now, instead using the "untraveled" gray.

Though I'm starting to get a little off-topic. Maybe some of this might be better served split off into their own issues?

**Comment by jteresco** [comment]
Definitely split off into issues so they don't get lost.

My own TM time available is very limited starting today through at least early November.  I'll probably not do much more than manage updates and make occasional easy fixes.

**Comment by yakra** [comment]
It's about time for school to begin, innit?

**Comment by yakra** [comment]
The following issues all fall under the design/layout/presentation umbrella, and should probably be considered concurrently:
#218 HB: Add user traveled length and percent
#221 HB: Remove coordinates from waypoints table?
#222 HB: cleaner info presentation, more CHM-style
#224 HB: Deprecated labels

**Comment by yakra** [comment]
ping @mapcat

**Comment by mapcat** [comment]
It wouldn't need to replace the average...actually it might be interesting to some to compare their percent travelled to the average.

**Comment by jteresco** [comment]
Related to this, a possibility is to put the current info up when u=null and all user-specific info and stats (including traveled segments highlighted in the waypoint list) when u=someone.

**Comment by yakra** [comment]
That's what I was thinking.
Though I also have no objection to displaying both pieces of info.

**Comment by jteresco** [comment]
User mileage and percent is now a new row in the "Route Stats" table when u=someone.  On tmtest for now.

**Comment by mapcat** [comment]
Bug report on forum:

http://tm.teresco.org/forum/index.php?topic=2316.msg8482;topicseen#msg8482

**Comment by yakra** [comment]
`jteresco commented on Aug 27`
> Related to this, a possibility is to put the current info up when u=null and all user-specific info and stats **(including traveled segments highlighted in the waypoint list)** when u=someone.

Traveled segments could be highlighted in the Name column, and the % column could stay as-is. This way, we still have all the info available when *u=null* when *u=someone*, and we can compare away.

**Comment by jteresco** [comment]
I don't think that last bit is too hard - just need to figure out how to enhance the SQL that brings in that list of waypoints so that it gives me an extra field telling me if each segment is clinched by the current user...  Someday I'll learn more SQL.

**Comment by jteresco** [comment]
Changes live on the main site.  Closing this issue.  Please feel free to open new issues for further enhancements to the HB.
