### ISSUE TITLE
HB: cleaner info presentation, more CHM-style

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#222]
Ties in to #218 a bit:

Concurrently, this might be an opportunity to clean up the Route Stats table.
I like the somewhat cleaner appearance of CHM's HB.  Compare...
http://tm.teresco.org/hb/?u=yakra&r=me.me206
http://cmap.m-plex.com/hb/hwymap.php?u=yakra&r=me.me206
In the case of ME206, the "ME ME206" label below the shield looks about the same.
But wait, there's more...
http://tm.teresco.org/hb/?u=yakra&r=tn.us041altnas
http://cmap.m-plex.com/hb/hwymap.php?r=tn.us041altnas
In the case of TN US41AltNas, we see that CHM conveniently includes the LIST Name right below the shield, whereas TM spells out the City name.
This has led to confusion [for at least one user](http://tm.teresco.org/logs/aaroads.log).
A layout more similar to CHM's format, without the LIST Name hidden down in the Route Stats table, would be nicer looking and less confusing IMO.

**Comment by michihdeu** [comment]
I like the info table about the route. Wish there would be anything similar for regions and systems (one has not yet traveled)...

**Comment by yakra** [comment]
I like the info table too. Just brainstorming about a different presentation of the info.

**Comment by michihdeu** [comment]
The "additional" info could be "hidden" by default... Hide/Show button...

**Comment by yakra** [comment]
The following issues all fall under the design/layout/presentation umbrella, and should probably be considered concurrently:
#218 HB: Add user traveled length and percent
#221 HB: Remove coordinates from waypoints table?
#222 HB: cleaner info presentation, more CHM-style
#224 HB: Deprecated labels

**Comment by yakra** [comment]
The new .list name display looks good.
My only other idea for changes to the Route State table is over at https://github.com/TravelMapping/Web/issues/218#issuecomment-324540848 , so I'll close this issue for housekeeping purposes.
