### ISSUE TITLE
HB: gray vs. blue polyline for null user

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#223]
The HB used to show a solid blue polyline when a null user (&u=& in the URL) was specified, similar to CHM, instead of using the "untraveled" gray.
This disappeared (inadvertently?) some time back when some other changes to the code were implemented.

**Comment by jteresco** [comment]
Inadvertent.  Would we want it blue in all cases, as it used to be, or use the "clinched" color for that system for visibility?

**Comment by jteresco** [comment]
Maybe what we want is to use the system's colors at all times (not just the pink/gray), and when u=null, draw all segments in the clinched color.

**Comment by michihdeu** [comment]
> Maybe what we want is to use the system's colors at all times (not just the pink/gray), and when u=null, draw all segments in the clinched color.

This!

**Comment by yakra** [comment]
Thought of that before too. Thirded!

**Comment by jteresco** [comment]
Do we still want this?  Easy enough.

**Comment by michihdeu** [comment]
System color would be nice.

**Comment by jteresco** [comment]
System color used (matching the opacity as on mapview) for HB routes on tmtest.

**Comment by jteresco** [comment]
Also uses clinched color for null user, satisfying the original point of this nearly 3-year-old issue.
