### ISSUE TITLE
HB: Show deprecated labels

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#224]
The CHM Highway Browser included an option to show Deprecated labels.
This would be useful... it's received at least a [passing mention](http://tm.teresco.org/forum/index.php?topic=1827.msg4441#msg4441) on the forum.
Right now, if I want to figure out that "FL US1 FleSt FL821" maps to "FL US1 FleSt FLTpk", I have to [check the WPT file](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/FL/usaus/fl.us001.wpt)...

The following issues all fall under the design/layout/presentation umbrella, and should probably be considered concurrently:
#218 HB: Add user traveled length and percent
#221 HB: Remove coordinates from waypoints table?
#222 HB: cleaner info presentation, more CHM-style
#224 HB: Deprecated labels

**Comment by michihdeu** [comment]
HB shows by default the traveled segments in a different color for the selected user...
In addition, Jim wants to remove alt labels automatically, see #189

**Comment by jteresco** [comment]
This is harder than it sounds, since the alt labels are used in the site update process but are not included at all in the DB.  I believe it would mean adding more fields to the waypoints table or another table that would track alt labels.  Seems like more work than it's worth.

**Comment by yakra** [comment]
> No user would be obligated to use this file, but I expect some might.

My takeaway from Jim's post, and the forum thread, is that only an automated removal of unused AltLabels was considered. I can't see removing in-use AltLabels without large-scale changes to the site & its mechanics, and the way users interact with it. Also in the "harder than it sounds" category, IMV.

That said, if I'm really dead-set on seeing this implemented, I do have the option of learning PHP myself. :D

**Comment by michihdeu** [comment]
Go for it 👍

**Comment by jteresco** [comment]
A quick summary of my thoughts on reducing alt labels:

- During the site update process, a "canonical" list file would be generated for all users, which would have routes in systems order then by the csv within each system, with all concurrencies included and the minimum segments (so if two were overlapping, they're merged into one), and in wpt file order for each route, using only primary labels for waypoints and current actual names for highways.  Like the nmp merged wpt files, they could be used by anyone interested either as a replacement for or to help update submitted list files.

- A sweep through the wpt files, removing all alt labels that are not in use, and a sweep through the csv files, removing alt route names that are not in use.

I think the consensus, and I agree, is that we would not remove anything that would break user list files.

The first item is actually pretty easy to accomplish.  The second requires a little more coding.  Neither is a high priority in my mind.

And none of it changes the fact that the alt labels do not exist in the DB, so the web can't be updated to include them unless we add more informatiton to the DB.

**Comment by jteresco** [comment]
Yes, the python code creates a giant .sql file, which is then used to remove all data from the old DB tables and populate them all with the newest.

**Comment by jteresco** [comment]
Once such data would be added to the DB, the PHP and/or code that displays the routes in the HB could be augmented to show the alt labels.

**Comment by jteresco** [comment]
One place I think this would be useful would be in a future TM-specific wpt editor, to catch conflicting names including alt labels.

**Comment by yakra** [comment]
Why would a WPT editor require info from the DB?

**Comment by michihdeu** [comment]
I think the points in use should automatically be indicated...

More ideas:
Concurrent routes could automatically be indicated one day
Traveled segments could be indicated e.g. to improve figuring out if an update entry is required
...

**Comment by jteresco** [comment]
> Why would a WPT editor require info from the DB?

As @michihdeu mentioned, I was thinking for points in use. I could see it gathering lots of potentially useful information from the DB.  Maybe we could have an option to show nearby waypoints for ease of bringing them in.  Many possibilities with a more "integrated" WPT editor.  All that said, sometimes you just want to see/build a route and don't care about all of that so some features would likely be optional/switchable.

**Comment by mapcat** [comment]
I definitely agree with working on adding deprecated labels to the waypoint table, but waiting until all unused alt labels are removed is fine with me.

This would be useful when log entries refer to a waypoint in the user's .list that's no longer the primary name, which seems to happen to me several times a year. Digging through the file in GitHub is time-consuming, and not an option for the users who don't use it.

**Comment by jteresco** [comment]
If nothing else, it might be helpful to have a log file that lists all of the alt labels that you could bring up and search (with your browser's search function).  Or maybe adding them to the DB is more useful than I'm thinking and it's worth going that route.

**Comment by yakra** [comment]
Adding them to the DB would be more end-user friendly than just writing them to a log file.
If they are added to the HB, I'd definitely want to go the CHM route and have an option to enable/disable viewing them. It's not something I'd want to see by default.

**Comment by michihdeu** [comment]
**Sorry, but I still don't understand why alt labels should be displayed in HB.**

Example:
http://tm.teresco.org/hb/index.php?u=si404&units=miles&r=eng.a001m

`ENG A1M 40 49`

If wp 40 would be renamed to HelWor (Hello World), the HB would display HelWor instead of 40 only. If Si is not sure where the hell wp 40 was, he can just look on the map. **The traveled segment is always displayed in a different color**. He can zoom in, click on the first wp 49 (match) and on the other end of the colored line, he will find HelWor. He can be sure that HelWor is the old 40 wp.

It also works if there are more than one segments traveled except if really all wps in use by the traveler have been changed. 
However, why should the user do anything here? I only see one reason: To extend a traveled segment. In this case, one can click on the first and last wp of the colored line and enter the wp names to the list file. The alt labels are completely replaced and the segment to be extended can be identified and modified.

**What's the advantage of displaying alt labes in the HB?**

The disadvantages are clear: Larger DB, longer DB query time and longer site update procedure.

**Comment by mapcat** [comment]
http://cmap.m-plex.com/hb/hwymap.php?r=tn.us070&sys=usaus&rg=all&u=mapcat

Select "all" for "deprecated labels shown".

Consider a user with the label US70Bus_E in his list file. If his list is broken during an update, and the entry in the log includes that label, it will be difficult to tell what exactly needs to be replaced without knowing where US70Bus_E is, since there are so many waypoints with US70Bus in them.

**Comment by michihdeu** [comment]
Ok, got it. Thanks.

It reminds me of the [Including map views in highway data updates entries](http://tm.teresco.org/forum/index.php?topic=1849) discussion.  I'd prefer improving the update entries...

**Comment by mapcat** [comment]
Sometimes lists are broken without an update entry, such as when a collaborator forgets to check for points in use.

**Comment by michihdeu** [comment]
which should NOT happen...

If we would extend update entries by labels in use (see forum discussion) which are no longer available, we could also add a data check...

Better than a larger DB...

**Comment by jteresco** [comment]
Any new thoughts on this?  It remains less a Highway Browser issue than it is a DB issue, as it would be straightforward enough to have an option to show the hidden alt labels if they were stored.  So here's an Issue over there:

https://github.com/TravelMapping/DataProcessing/issues/345

**Comment by yakra** [comment]
Despite having opened the issue, it's not very important for me right now. This issue hasn't had any discussion in almost 3 years... Let is sit a bit more? Take it to the forum to get a wider range of opinions?

**Comment by jteresco** [comment]
Almost 5 years and many things have since changed, so closing this one.
