### ISSUE TITLE
HB: select points to generate a list file entry

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#226]
Idea based on note in #221:

Like the HDX allows selection of start and end vertices for Dijkstra's algorithm, the HB could have a way to select start and end waypoints for a traveled segment and then generate a .list entry with the appropriate region, route, and waypoint labels that can easily be copied into a .list file.

**Comment by yakra** [comment]
> Like the HDX allows selection of start and end **vertices** for Dijkstra's algorithm, the HB could have a way to select start and end **waypoints** for a traveled segment and then generate a .list entry with the appropriate region, route, and waypoint labels that can easily be copied into a .list file.

Per #316, I think at least on mapview, from a UI standpoint it makes more sense to select by segments/edges than waypoints/vertices. There will probably be fewer times we'd have to make a selection to disambiguate a concurrent segment than to disambiguate a colocated waypoint.

Not to say that doing it by waypoint it bad at all; we could have both UI options available. Whatever it is / they are, it makes sense to have the same or similar interface in mapview & the HB.

Once something is implemented in one, it's then easier to reuse the code & implement in the other, yes?

**Comment by jteresco** [comment]
I'd definitely like to experiment with these kinds of things.  I would like a consistent interface as much as possible, and would be willing to try to get both a segment-based and waypoint-based selection going.

**Comment by jteresco** [comment]
Segment-based so far, can think about waypoint-based if there's a feeling that it would be significantly better.

**Comment by yakra** [comment]
Segment-based is fine IMO

**Comment by michihdeu** [comment]
We were used to click on the wp and think it should remain like this.

**Comment by jteresco** [comment]
> We were used to click on the wp and think it should remain like this.

I'm not sure what you mean here.  Is there functionality that you could do before clicking on a waypoint that's not there in the new version?

> The navigation table is still in place and I think that it should also be possible to make the selection there. Hold SHIFT and click two wps.
> 
> _I hope that we don't want to eliminate the table which is very helpful for peer-reviews etc._

I'm not sure what you mean by "navigation table"?  You mean the list of waypoints on the left?  I have no intent to remove that.

So you would prefer to be able to click markers for waypoints to set travels, not just segments?

**Comment by michihdeu** [comment]
> So you would prefer to be able to click markers for waypoints to set travels, not just segments?

yep, click on a wp on that list opens the info window and I currently need to copy the wp label from there and put it to my user list file. Then I click on the next wp - on the "list of wps" or directly on a wp on the wp - the info window opens and I need to copy the label again.

I click on wps, not on segments.

The current implementation of the new feature is segment-based though.

**Comment by jteresco** [comment]
> yep, click on a wp on that list opens the info window and I currently need to copy the wp label from there and put it to my user list file. Then I click on the next wp - on the "list of wps" or directly on a wp on the wp - the info window opens and I need to copy the label again.
> 
> I click on wps, not on segments.

Can't you still do that? 

But the new functionality is intended to eliminate the need to click on each marker and copy the label.  Instead, you just copy the line(s) you need from the toolbox textarea once you've selected all of your traveled segments.

**Comment by michihdeu** [comment]
sure, by users ONLY click on WPs right now. In the future they ONLY can click on segments to get the user list file entry. The opposite. And the list of wps would be.... useless for picking up user list file entries while it is still a great help for navigation.

Just my 2c. I will get used to whatever will be available.

**Comment by jteresco** [comment]
Since this functionality was implemented long ago, closing.  If there are problems to report or enhancements to request, let's do them in separate issues.
