### ISSUE TITLE
Mapview: Clickable segments/points

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#228]
A possible feature to add: click on any polyline and get an infowindow about that segment, including links to the HB for each route carried by that segment.

**Comment by yakra** [comment]
Ooh. Yes.

**Comment by michihdeu** [comment]
I think I like the idea even more than #95. Not just a list of all routes in a defined radius but exactly the route(s) of a segment. I think it's more useful and I guess it should be easier to be implemented. Nevertheless, the other feature might have additional benefit.

**Comment by jteresco** [comment]
This might have become easier with the recent addition of graph edge popups in HDX.

**Comment by jteresco** [comment]
tmtest version (code in branch polylinepopups for now) shows only route like "NY NY5" or "RI US1BusPro", but the intent is to include all routes carried by the segment, the visible waypoint endpoints of each, an HB link for each, and the segment length.   Since the Polylines are stacked on top of each other for concurrent routes, things are more complicated than they'd seem at first.

**Comment by yakra** [comment]
Would it make sense to add concurrency info to the DB?

**Comment by yakra** [comment]
In mapview.php, system.php  region.php, clicking an edge will produce a popup where I clicked, but pan to a seemingly random location.
https://github.com/TravelMapping/Web/blob/7dfd8e338edee3966939251f00aa63ad4479fd63/lib/tmjsfuncs.js#L820-L835
Do we have the wrong `connIndex` maybe?

**Comment by jteresco** [comment]
This functionality is live on the production site.
