### ISSUE TITLE
"Browser" column in stats table

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#23]
A new column "Browser" column would be great to link directly to the Highway Data Browser with corresponding filter

**Comment by Thing342** [comment]
Fixed in a future pull request.

**Comment by Thing342** [comment]
If this has been fixed to your satisfaction, would you mind closing the issue? I can't close it by myself.

**Comment by michihdeu** [comment]
Thanks :)

**Comment by jteresco** [comment]
@Thing342 I believe I just added permissions so you'll be able to merge and close issues in this repository.
