### ISSUE TITLE
Stats/rankings for multi-regional countries

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#233]

**Comment by jteresco** [comment]
http://tm.teresco.org/forum/index.php?topic=2204.0

**Comment by yakra** [comment]
Should this be considered a duplicate of #54?

**Comment by michihdeu** [comment]
IT is a little bit more: 

> It doesn't have to be limited to multi-region countries either - continents are something we can do in the same way.

But I'll add this to #54

**Comment by yakra** [comment]
Closing as a duplicate of #54
