### ISSUE TITLE
Invalid links in updates.csv

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#239]
Root links of updates.csv should be automatically checked and invalid links should be output in a log file linked on the site.

See https://github.com/TravelMapping/HighwayData/commit/8dd95d17237ccd7ef719b9db7bd5d9314b166e28#commitcomment-24855860

**Comment by jteresco** [comment]
Moved to https://github.com/TravelMapping/DataProcessing/issues/62 .
