### ISSUE TITLE
Stats table headlines are redundant

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#24]
The headlines like "Overall Stats" are displayed twice at the moment. I think the first table row is not required.

"Stats by Region" and "Clinched Mileage by Region:" is also the same info, and
"Stats by System" and "Clinched Mileage by System".

**Comment by Thing342** [comment]
Fixed in a future pull request: 0f475705e486852256057f4e8ae712ca2d4f0e50

**Comment by michihdeu** [comment]
It's ok for "Overall Stats" but still redundant for the others. I'll accept if you really like it this way but I think it's confusing and it's strange that the 2nd row is used for sorting...

**Comment by michihdeu** [comment]
It's ok now. Thanks :)
