### ISSUE TITLE
General stats table design of values

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#25]
Mileage values should have two positions after decimal point only (looks quite strange with up to 4) like it's already designed in the table of the map

Milage and percent values should generally be right-aligned in the table

**Comment by Thing342** [comment]
I fixed this in a commit.

**Comment by michihdeu** [comment]
There are still more than two positions after decimal point and it's still left-aligned!?!?!?!?

**Comment by yakra** [comment]
Just a guess here, but I think Jim may have pulled the changes into master but just not updated them on the site yet.

**Comment by jteresco** [comment]
I think the site matches the GitHub master, but it's certainly possible I missed something in the transfer.  I'm going to be out for a couple hours now, but can check on it when I get home.
