### ISSUE TITLE
Leaflet: speed when many polylines are on the map

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#258]
Leaflet seems to be slower than Google when there are lots of polylines, such as when loading several states into mapview.

**Comment by jteresco** [comment]
@michihdeu reports:

Loading a (simple) map takes about the same time. For instance France less than 10s on both: http://tml.teresco.org/user/mapview.php?units=miles&u=michih&rg=FRA

Loading a multi-region map takes about twice the time than on the old version (200s vs. 90s): http://tml.teresco.org/user/mapview.php?units=miles&u=michih&rg=DEU-BY,DEU-HE,DEU-BW,DEU-RP,DEU-SL,DEU-NW,FRA,LUX,BEL,IRL,NIR,SCT,WLS,ENG

Moving the map with mouse is incredibly slow with less and much data on the new server (both links above). It stucks and the map is not moving anymore.

**Comment by jteresco** [comment]
I'm guessing we've likely lost the ability to view large datasets, especially the graphs, at least the ability to move them around.  Leaflet clearly isn't optimized to handle the number of objects we've been putting on our maps, at least not in the way we've been doing it.  Maybe there's a better way to manage on our end, or maybe this is just the reality of moving to an open-source product.

**Comment by jteresco** [comment]
Now that I've removed the debugging output, I'm trying some things out with mapview.  I can load some pretty good-sized data sets reasonably quickly and can pan and zoom without too much frustration.  However, when we hit some threshold (not exactly sure where, but probably in the 20,000+ segments range) Leaflet maps seem to hit a wall and become hard to use.

**Comment by yakra** [comment]
http://tml.teresco.org/user/mapview.php?units=miles&u=yakra&rg=NH,MA,CT,NY
Firefox 60.0.1 on UbuntuMate 16.04 = unusable. Redlines the CPU for minutes at a time. No response to attempt to pan. Mouse wheel zoom worked a few times. Took forever. :(

**Comment by jteresco** [comment]
All of these are reasonably fast with either Firefox 60.0 or Chrome 66.0.3359.139 on my MacBook Pro macOS 10.12.6, 16 GB memory.  Leaflet maps might be more of a memory hog or might need some graphics acceleration.  Not sure.

**Comment by yakra** [comment]
I bet it's graphics acceleration. I still had plenty of memory headroom in the cases I tested out.
I've noticed that in-browser apps such as the Google Maps API are much faster and more responsive in Firefox under commercial OSes than Linux, on systems with comparable specs.

**Comment by jteresco** [comment]
Closing this issue, but efforts will continue to improve efficiency.
