### ISSUE TITLE
Incomplete update on new server

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#260]
@jteresco You just run an update but logs are not updated, e.g.:

http://tml.teresco.org/logs/bhemphill.log
http://tml.teresco.org/logs/michih.log

**Comment by jteresco** [comment]
Missed a spot I needed to update a path.  Rerunning now.  Let's see if it fixes everything.

**Comment by michihdeu** [comment]
It's fine now. Thanks.
