### ISSUE TITLE
Shieldgen: some files on old server not in GitHub

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#261]
I'd like someone more familiar with the shield generation to look at this one.  The current production server somehow has the following files which are not in GitHub, so not on the new server:

<pre>
-rw-r--r--  1 terescoj  wheel      723 Jan 10  2017 template_deub_wide.svg
-rw-r--r--  1 terescoj  wheel      655 Jan 11  2017 template_eure_wide.svg
-rw-r--r--  1 terescoj  wheel      851 Feb  4  2017 template_roudn_wide6.svg
-rw-r--r--  1 terescoj  wheel     3023 Jan  9  2017 template_usadc.svg
-rw-r--r--  1 terescoj  wheel     7663 Jan 10  2017 template_usala.svg
-rw-r--r--  1 terescoj  wheel     7663 Jan 10  2017 template_usala_wide.svg
-rw-r--r--  1 terescoj  wheel     3145 Jan 12  2017 template_usamts_wide.svg
</pre>

This breaks any shield generation that tries to use these files. I'm guessing some are obsolete, but @michihdeu observes that this breaks (for example): http://tml.teresco.org/hb/index.php?units=miles&u=michih&r=deush.e47

**Comment by rschen7754** [comment]
usadc and usala/la_wide can be thrown out, as can usamts_wide.

**Comment by jteresco** [comment]
It looks like eure_wide is needed (http://forum.travelmapping.net/index.php?topic=3102.msg14452) so I will get it in.

**Comment by jteresco** [comment]
Anyone know about usadc, usala, deub_wide, and roudn_wide6?

**Comment by yakra** [comment]
**lab2 has**
* `template_usadc_wide.svg`, and the shield shows up fine in the HB.
* `template_usala1.svg` and `template_usala1_wide.svg`, but I only see generic state route rectangles. I'll check `error_log` shortly.
* `template_deub.svg`, no `_wide` flavor. Checked out several deub routes in the HB; shields displayed fine. Don't know if this would only be used for a small subset of routes or what. Ping @michihdeu
* `template_roudn.svg` and `template_roudn_wide.svg`, no `6` flavor. Also unclear to me what if anything that would be used for. Checked out several roudn routes in the HB; shields displayed fine.

**Comment by yakra** [comment]
Nothing in `error_log` for usala.
```
# mv template_usala1.svg template_usala.svg
# mv template_usala1_wide.svg template_usala_wide.svg
```
and I'm good. Looks like the same should be done on noreaster.

**Comment by jteresco** [comment]
Thanks.  Fixed the LA ones, and will be renaming in GitHub also.

**Comment by michihdeu** [comment]
> `template_deub.svg`, no _wide flavor. Checked out several deub routes in the HB; shields displayed fine. Don't know if this would only be used for a small subset of routes or what. Ping @michihdeu
I don't remember. I think it can be removed.

**Comment by jteresco** [comment]
Closing this old issue, please open new issues for any shield generator problems.
