### ISSUE TITLE
HB route index page problems

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#262]
@michihdeu reports:

HB: Filter by region / system does not work (drop-down cannot be opened: http://tml.teresco.org/hb/index.php?units=miles&u=michih&sys=null&rg=DEU-SH

This appears to be a CSS problem with the route table being stacked on top of those controls (and given a fixed width of 100%), and I'm guessing it will go away when the red bar across the top is removed.  I can tab around and use arrow keys to activate those controls.

This is just one example of a place we're using way too many hard-coded positions of items and hopefully someone more talented at CSS than I am will tackle it at some point.

**Comment by michihdeu** [comment]
Yes, it works now. Issue can be closed.
