### ISSUE TITLE
HB: clicking on table to bring up info popups with Leaflet maps

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#263]
@michihdeu reports: 

Info window at waypoint does not appear when clicking on the table (but appears when clicking on the wp itself).

**Comment by jteresco** [comment]
I think this one is not too bad.  I'm using "popups" instead of "info windows" with Leaflet (who knows if this is appropriate).  I didn't think about this functionality and will check it out.

**Comment by yakra** [comment]
Are there plans to add similar functionality to the HDX?
Is there already an issue for this that I've missed?

**Comment by jteresco** [comment]
Just added it.  I forgot that HDX has a "custom" callback for clicks in the table that also needed to be updated.

**Comment by yakra** [comment]
Quick test: Looks good!
