### ISSUE TITLE
Leaflet: Blank map tiles

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#265]
We had an option for blank map tiles with Google Maps.  I think it's not too hard to make this possible with Leaflet also.

**Comment by yakra** [comment]
In the meantime, Stamen Toner isn't half bad for this purpose.

**Comment by jteresco** [comment]
White and black blank tiles are now in place.  The way it's implemented at this point also required changes to be made to the leaflet-providers.js file, so we now have our own fork of that repository at https://github.com/TravelMapping/leaflet-providers

Please open new issues if there are problems with this functionality or for requests for additional tiles of this type (e.g., more colors).
