### ISSUE TITLE
Leaflet: Zoom-out with mouse

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#266]
click left to zoom-in works.
click right to zoom-out as it worked with Google API doesn't work but opens the (useless) context menu.

**Comment by jteresco** [comment]
I hesitate to change any of the default Leaflet map zooming behavior, but could investigate how to do it if there's a general agreement that Leaflet's way is problematic.

**Comment by michihdeu** [comment]
Well, I'm used to navigate with mouse for zooming. I think anyone has it's own way...

**Comment by yakra** [comment]
I would occasionally double right click but usually just go for the mouse wheel.

**Comment by michihdeu** [comment]
I have no mouse (wheel) but just a touch pad

**Comment by michihdeu** [comment]
Workaround: Press SHIFT and click left

More info: https://leafletjs.com/examples/zoom-levels/

**Comment by jteresco** [comment]
I'm going to close, since I will avoid any change like this to default Leaflet behavior.
