### ISSUE TITLE
wpt editor: wpt + label column text not visible

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#271]
The text color of the first two columns is now the same like the background (it wasn't so 2...3 days ago). The text can only being read if the mouse is over the field. The other columns are fine.

btw: Is this the right place for wpt editor issues? Maybe an own repository would be better?

**Comment by jteresco** [comment]
Yes, please report here.

I hope to be back to these kinds of HDX fixes tomorrow.
