### ISSUE TITLE
mapview: display by country and/or continent

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#274]
Wouldn't it be lovely if, instead of typing
http://travelmapping.net/user/mapview.php?units=km&u=michih&rg=deu-bb,deu-be,deu-bw,deu-by,deu-hb,deu-he,deu-hh,deu-mv,deu-ni,deu-nw,deu-rp,deu-sh,deu-sl,deu-sn,deu-st,deu-th
we could instead just do
http://travelmapping.net/user/mapview.php?units=km&u=michih&country=deu ?
For all of Europe: http://travelmapping.net/user/mapview.php?units=km&u=michih&continent=eur

This would require the info in regions.csv, which I don't imagine is in the DB (at least, in the necessary form) now.

I've done something similar with *yakra/tmtools/canvas*, the meat-n-potatoes being [here](https://github.com/yakra/tmtools/blob/82996d171ab2450118de45652a92b86389b954c6/canvas/canvas.cpp#L298-L315).
Spitballing off of what I've done there...
http://travelmapping.net/user/mapview.php?units=mi&u=oscar&country=USA&continent=NA would give us the lower 48 + Alaska + Puerto Rico + US Virgin Islands.
http://travelmapping.net/user/mapview.php?units=mi&u=oscar&country=USA&continent=NA&excluderg=AK,PR,VI would give us just the lower 48, arguably more conveniently than http://travelmapping.net/user/mapview.php?units=mi&u=oscar&rg=AL,AR,AZ,...(44_more_regions)...,WY

**Comment by jteresco** [comment]
Everything's there in the DB to make this happen.  It's a matter of the right SQL JOIN or similar to have it pull out what we are looking for on a given view.

**Comment by michihdeu** [comment]
Yep, please refer tp #54

**Comment by jteresco** [comment]
Unfortunately, my SQL skills are still pretty poor, but I think I have an idea about it.  Hope to experiment with it soon.  Part of me has been avoiding any web front end stuff knowing that the redesign (#268) is in the works.

**Comment by jteresco** [comment]
This was a little messier than I thought, so all I did so far was to add a country= parameter that can be specified only when no rg= is there, and it can only be one country at a time.  But it is at least an improvement.  Please test it out on the tmtest.teresco.org server and if this is at least a little useful and it seems I didn't break anything, I can put it on the main site.

**Comment by vdeane** [comment]
I was testing it out and using http://tmtest.teresco.org/user/mapview.php?u=vdeane&country=US only gives me the interstates.  Canada works fine, though.

**Comment by jteresco** [comment]
For historical reasons, when no valid region(s), and now country, is specified, the system defaults to showing only the usai system.  You want country=USA instead, but be sure your browser is ready to work.

**Comment by vdeane** [comment]
It just gives me a "blank" map centered on Siena College when I try country=USA.

**Comment by jteresco** [comment]
Looks like a memory limitation trying to load a full USA map.  When I view the source, I see an error message on the 376,014th line of JS code generated by waypoints.js.php that I ran out of memory, this on Safari on my MBP with 16 GB of RAM:

<pre>
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 983040 bytes) in <b>/home/www/tmtest/lib/tmphpfuncs.php</b> on line <b>98</b><br />
</pre>

I'm not sure whose limit that exceeds.

The map always defaults to center on my office at Siena and pans/zooms to loaded data on any successful load.

**Comment by jteresco** [comment]
I increased PHP's "memory_limit" from 128MB to 1GB, but no change in behavior.

**Comment by jteresco** [comment]
Looks like I was not successful in increasing the memory_limit, as php -i still shows a 128 MB limit.  There must be another place I need to set it.

**Comment by jteresco** [comment]
I believe I've now successfully raised the memory limit for PHP but I am not on a network where I can test it at the moment to see if @vdeane's map will load.

**Comment by michihdeu** [comment]
I can load tmtest.teresco.org/user/mapview.php?u=vdeane&country=USA

**Comment by jteresco** [comment]
Nice!  Is pan/zoom functionality at least somewhat usable?

**Comment by michihdeu** [comment]
I've only loaded it... I'll try again.

**Comment by michihdeu** [comment]
Yep, works 👍

**Comment by michihdeu** [comment]
The initial load took about 4 minutes (I'm in a hotel with limited access)

**Comment by vdeane** [comment]
I found that it worked quite well.  Doing the continent still overloads it, though we probably don't want to push the server too hard.

**Comment by jteresco** [comment]
The country= parameter is now on the main site.  Leaving this open pending enhancements.

**Comment by ssoworld** [comment]
Great work everyone – nice to have it load.  It zooms all the way out but that’s nothing a few wheel clicks can fix 😊

**Comment by jteresco** [comment]
Next up is to have a way to get this through the main user interface rather than URL editing.

**Comment by jteresco** [comment]
Remaining idea here is superceded by new Issue #475.  Closing.
