### ISSUE TITLE
Incorrect rank for routes driven within a region

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#278]
http://forum.travelmapping.net/index.php?topic=2578.msg10409;topicseen#msg10409

I took a quick look hoping to see a typo I could fix quickly but didn't notice anything obvious, so I'm opening up this issue.

Relevant URLs for testing:

http://travelmapping.net/user/region.php?units=miles&u=cinx&rg=AUT shows rank 1 but should be 2

http://travelmapping.net/user/region.php?units=miles&u=panda80&rg=AUT shows rank 2 but should be 1

**Comment by jteresco** [comment]
Link from old #206 issue: http://forum.travelmapping.net/index.php?topic=2152.0;topicseen

**Comment by jteresco** [comment]
http://forum.travelmapping.net/index.php?topic=2994.0

**Comment by yakra** [comment]
> http://forum.travelmapping.net/index.php?topic=2578.msg10409;topicseen#msg10409
> http://forum.travelmapping.net/index.php?topic=2994.0

## Topics merged
New URLs:
http://forum.travelmapping.net/index.php?topic=2152.msg10409;topicseen#msg10409
http://forum.travelmapping.net/index.php?topic=2152.msg13666#msg13666

**Comment by yakra** [comment]
See /user/region2.php on lab2 for a fix.
The existing /user/region.php is still there for comparison purposes.
Big thanks to mikeandkristie on the forum for finding the bug & sorting out the SQL queries.
Next up, system.php!

**Comment by jteresco** [comment]
@yakra time to get you on the TM payroll, if only we had one...  Thanks for getting your hands into the PHP and SQL stuff to tackle some of these longstanding issues.

**Comment by yakra** [comment]
LOL, I hear that knowing PHP & SQL can be valuable skills to help get a Real Job™, so there's that!
I've wanted to learn PHP & SQL for a little while now, just needed something to hack, a bit of a Hello World. TM's served pretty well for that; I think it's been easier for me setting up a TM instance, diving into the code & seeing how things are done that it would have been to just start from scratch.

There is now a fix on lab2 at /user/system2.php.

With this sorted, back to #91...
