### ISSUE TITLE
graphs page: .zip archive link broken

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#283]
http://travelmapping.net/graphs/
>  If you would like a local copy of all of the latest graphs, you can download [a zip archive of all of them](http://travelmapping.net/graphs.zip). Beware that this is a large file!

Also, when the .zip archive did exist, how was it created?

**Comment by jteresco** [comment]
A definite thing to fix.  The script used to zip them up before transfer.  I wonder if I lost that functionality when I created and start to use the localupdate.sh script.

**Comment by yakra** [comment]
Possibly... I did find this:
https://github.com/TravelMapping/DataProcessing/blob/ec688eb5b256b33f590285f049b630061427e1b6/siteupdate/python-teresco/xferlogs.sh#L14-L15

Looks like you're well ahead of me at fixing this (and https://github.com/TravelMapping/DataProcessing/issues/104#issuecomment-420085302), and it can probably be closed soon...

**Comment by jteresco** [comment]
Should be set now.  It was in fact a step forgotten when I combined siteupdate.sh and xferlogs.sh functionality into localupdate.sh .
