### ISSUE TITLE
HB: display more info about user and overall travels/clinch for each route

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#284]
The HB pages have tables that are fairly tall and skinny so there's plenty of room for more columns.  Some possibilities:

For current user, a column showing % traveled on that route.

For all users, columns showing the number/% of users who have traveled/clinched that route.

**Comment by michihdeu** [comment]
Especially the start page travelmapping.net/hb/ could get more data for the systems itself

**Comment by jteresco** [comment]
My thinking on this has changed.  I would like to keep user stats out of the true "browser" pages like the list of systems and routes within a system/region from the old HB, and from the new findroute.  Those kinds of stats are things that system.php and region.php are for.
