### ISSUE TITLE
New contributor and region

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#295]
@rmihailucian now that you have a system going to preview status, you probably want to add yourself to the credits.php list of contributors.  Also if there were any Morocco-specific resources used to help draft the routes, please add them to that file as well.  Thanks.

**Comment by michihdeu** [comment]
The same for @ntallyn

**Comment by rmihailucian** [comment]
Thank you, I added myself to the list. I have no specific sources, just OSM and French Wikipedia.

**Comment by ntallyn** [comment]
Pull request submitted.

**Comment by michihdeu** [comment]
@jteresco I think the issue can be closed now.

**Comment by jteresco** [comment]
Yes, thanks.
