### ISSUE TITLE
Graph index page updates for traveled graphs

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#299]
With the changes in https://github.com/TravelMapping/DataProcessing/pull/201 coming online, corresponding changes will need to be made to the graph download page.

**Comment by yakra** [comment]
* Simple, collapsed, and traveled graphs now.
* Possibly add links to HDX-Lite pages?
  - Simple & collapsed graphs are supported now.
  - I'll have to update it to support the traveled graph format.

**To further complicate things...**
What about adding .NMPs to the mix? I had [the idea](https://github.com/TravelMapping/DataProcessing/issues/211) of making .NMP files for each graph, not just regions, and backburnered it as *not quite* straightforward, but would still like to look into it at some future point.
If a `GraphListEntry` were added for each, could the HDX then automatically load them?
While this isn't something I plan on implementing right away, if we decide it's a good idea, it could effect the layout of the download page, and might be something to take into account.

**Comment by jteresco** [comment]
I'm ok with adding links to HDXlite pages.  Whether you want to have traveled versions also or not, I can add the links.  I'd like to keep NMPs separate, but we could make a page of links if there's interest.

**Comment by jteresco** [comment]
I'm going to add a field to `GraphListEntry` and the DB table for number of travelers, so that information can be included on the updates version of this page.

**Comment by jteresco** [comment]
Don't have HDXlite links in yet, but we're otherwise good.

**Comment by jteresco** [comment]
The description of the traveled file format is also now live on site http://courses.teresco.org/metal/graph-formats.shtml

**Comment by yakra** [comment]
> I'd like to keep NMPs separate, but we could make a page of links if there's interest.

No problems here; we can keep on going as we have been.
The per-graph .NMP sets are low priority for me; we can save any discussion of a link page for if/when these actually appear.

> I'm going to add a field to `GraphListEntry` and the DB table for number of travelers, so that information can be included on the updates version of this page.

Found https://github.com/TravelMapping/DataProcessing/commit/17e2111de3e3cc431046b2ef4fa8aa64f7947c6f and [did the same in C++](https://github.com/TravelMapping/DataProcessing/pull/219/commits/4987cf668845c9a3105029dab495e26b923e9b24).
Incidentally, `write_master_tmg_traveled` doesn't need to return the traveler count, as it uses the same `traveler_lists` variable created earlier.

> I'm ok with adding links to HDXlite pages. Whether you want to have traveled versions also or not, I can add the links.
...
> Don't have HDXlite links in yet, but we're otherwise good.

I want to have traveled versions, yes. It only makes sense to have tmg2html compatible with each type of graph.
* Updating tmg2html will be easy enough *(I'm thinking, initially add just enough support to parse the file, ignoring the traveler info & displaying the graph as we would a collapsed graph, and add more enhancements/functionality later)*, but I don't see myself getting to it straight away.
* Once that's ready, sort out:
  - Where to keep the .tmg.html links on the server?
  - How to include on graphs/index.php? Maybe a separate line in the "Download Link" column?

> The description of the traveled file format is also now live on site http://courses.teresco.org/metal/graph-formats.shtml

Looks good!

**Comment by jteresco** [comment]
Let's open a new issue for addition of the HDXLite links.  Closing this one.
