### ISSUE TITLE
README.md: ~/.my.cnf

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#305]
```
[clienttmapadmin]
password = YOURPASSWORDFORTHISUSER
```

Looks like `clienttmapadmin` should be `clienttravmapadmin` per the previously suggested names for the MySQL users.

Also need to add plain `[clienttravmap]` & a password, due to some more recent code:
https://github.com/TravelMapping/DataProcessing/blob/master/siteupdate/python-teresco/localupdate.sh#L58

**Comment by jteresco** [comment]
I think the documentation is consistent and works with the localupdate.sh code, but it's possible I'm missing something.

**Comment by yakra** [comment]
> `
CREATE USER 'travmapadmin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YOURPASSWORDFORTHISUSER';`
`CREATE USER 'travmap'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YOURPASSWORDFORTHISUSER';`

Users `travmapadmin` & `travmap` are created.

> To be able to update the database remotely by ssh, a file `~/.my.cnf` can be created on the server with the password for travmapadmin:
>
> `[clienttmapadmin]`
> `password = YOURPASSWORDFORTHISUSER`

Does not match the `travmapadmin` user we created.
I had to change my file to `[clienttravmapadmin]` to get it to work.
We also need to add
`[clienttravmap]`
`password = YOURPASSWORDFORTHISUSER`

https://github.com/TravelMapping/DataProcessing/blob/b2f0fdb4e653fc4a10f113614a7040cc5d5089d7/siteupdate/python-teresco/localupdate.sh#L58
The line in question:
echo "show processlist;" | mysql --defaults-group-suffix=travmap -u **travmap**

**Comment by jteresco** [comment]
So on both Linux VMs I created recently for testing of the https://github.com/TravelMapping/DataProcessing/issues/551 work, I have a `~/.my.cnf` with `password` entries under `[clienttmapadmin]` and `[clienttravmap]`.  The mysql users are `travmap` and `travmapadmin`.  @yakra I guess I'm not seeing why a `[clienttravmapadmin]` is needed in your case if it wasn't in mine.  Best I can tell, the names don't have to be related to each other at all, as long as we specify the right `--defaults-group-suffix` and `-u` on the `mysql` commands in the scripts.

**Comment by jteresco** [comment]
Additional test on the CentOS 7 VM.

I created a new user `'fred'@'localhost'` and gave it the same permissions as `'travmapadmin'@'localhost'`.  I created a new entry in `~/.my.cnf` as `[clientgeorge]`.  Then used `--defaults-group-suffix=george` and `-u fred`, and all works.

**Comment by yakra** [comment]
If I'm reading this correctly, it sounds like I just need to change `[clienttravmapadmin]` to `[clienttmapadmin]`in `~/.my.cnf`. I'll give it a try this evening.

**Comment by yakra** [comment]
I guess I just wrongly assumed back in 2019 that the username and suffix needed to be the same. Changed `~/.my.cnf`; just finished a successful run of the latest siteupdate.sh on lab2.
