### ISSUE TITLE
hb.php: page title

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#31]
How about instead of simply "Travel Mapping Highway Browser (Draft)" as the page title, include info on what route is being displayed?
For example, the CHM HB will say "Map of Maine US1 Bus Damariscotta, ME"... (Listing the hwy system the route is part of isn't important, IMO.) Even just saying "ME US1BusDam" would suffice.
This would be very helpful when multiple windows or tabs are open, or when going backward & forward thru my web browser history.

**Comment by michihdeu** [comment]
I had the same thought yesterday but don't want a hasty reaction. I think the whole header should get a different style. The main page (thing342 one's, not Jim's "ugly" main page) already has a nice header which should be used for all pages like highway browser, user stats, update list,... The page title should be integrated into the header - and the "Draft" suffix should be removed.

The other stuff should be displayed in the same style. For instance, I think the "Show Markers" text is too big. And it's directly continued by the system and route shortcut and my personal amount of clinched mileage which looks odd ("Show Markers BEL R33: 0.00 of 3.32 miles (0.0%) clinched by michih."). I think the latter could be integrated into a table.

**Comment by yakra** [comment]
I mean, specifically, the page title in the <title> HTML tags, that displays in the browser Windows's top title bar in most GUIs

**Comment by jteresco** [comment]
I think it's important that the "Draft" stay on all of our pages until things are put together more carefully and we have fully acknowledged all contributors and sources.  That said, I have no problem modifying the page title for the window's title bar to have the route info for easier navigation among tabs/icons/etc.
