### ISSUE TITLE
HB maps broken when using alternate database

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#310]
Routes contained in the standard "production" databases, `TravelMapping` or `TravelMappingCopy`, whatever's pointed to by `tm.conf`, work as expected.
http://travelmapping.net/hb/index.php?units=miles&u=yakra&r=me.me127&dbname=TravelMappingTest

Routes in a database specified with the `dbname=` parameter show up as expected.
http://travelmapping.net/hb/index.php?units=miles&u=oscar&sys=null&rg=TX&dbname=TravelMappingTest
Some TX FM Roads are down bottom.

When we view a route *not* in the production DB, the HB breaks.
http://travelmapping.net/hb/index.php?units=miles&u=oscar&r=tx.fm0051&dbname=TravelMappingTest
We still have Route Stats & Waypoints tables. Clicking a waypoint label pans the map OK.
The map itself lacks any waypoint markers or segment polylines.

mapview.php, system.php & region.php are all OK. Tested on my server with usatxf as a preview system. The .sql file I gave Jim to install as `TravelMappingTest` in this example only has usatxf as a devel system. :(

**Comment by yakra** [comment]
`if ($routeparam != "") {`
https://github.com/TravelMapping/Web/blob/b1d888cb1813ee2f3b107d71ad0eea7b1425d56d/hb/index.php#L178
https://github.com/TravelMapping/Web/blob/36f71d380a836eeb123ac0370d05ca75d76ffcaa/lib/waypoints.js.php#L293-L295
The array key exists, and selecting a single route is what we're doing.
https://github.com/TravelMapping/Web/blob/36f71d380a836eeb123ac0370d05ca75d76ffcaa/lib/waypoints.js.php#L224-L225
The query is straightforward; we should get the same one whatever DB we're using.
https://github.com/TravelMapping/Web/blob/36f71d380a836eeb123ac0370d05ca75d76ffcaa/lib/tmphpfuncs.php#L91-L99
Straightforward enough. What's `tmdb`, then?
https://github.com/TravelMapping/Web/blob/36f71d380a836eeb123ac0370d05ca75d76ffcaa/lib/tmphpfuncs.php#L83
https://github.com/TravelMapping/Web/blob/36f71d380a836eeb123ac0370d05ca75d76ffcaa/lib/tmphpfuncs.php#L36-L50
The same function gets called whatever DB we're using, and if `dbname` is present, `tmdbname` gets overwritten with it. This all looks good.

It looks like we have the same `tmdb` object, being accessed by the same `tmdb_query` function used in mapview.php, system.php & region.php, in the same way.
I don't see anywhere else the DB name is specified.
I have no idea what's going on.

**Comment by jteresco** [comment]
You just did the investigation I would have done, suspecting that somewhere a DB name remained hard-coded or something.

Next to consider: is the dbname= QS parameter being honored by all files?  Again, should be, but that would be my next place to look.

**Comment by yakra** [comment]
the strings `dbname` & `tm.conf` are each only contained in tmphpfuncs.php & graphs/index.php.
tmphpfuncs.php, we just discussed above. graphs/index.php does the same basic thing as `tmdb_query`, without going thru the `tmdb_query` middleman itself.
So I don't see anywhere else we'd be reading in `tm.conf`.
> is the dbname= QS parameter being honored by all files?

Everywhere I've looked, functionality eventually goes to `tmdb_query`, which should already have `tmdb` constructed with the right `tmdbname` value if I'm understanding tmphpfuncs.php correctly.

> suspecting that somewhere a DB name remained hard-coded or something.

My suspicion, yes, or part of it at least. I was looking more at the flow of the code, and not searching exhaustively for any remaining rogue occurrences of "TravelMapping" as a string. I'll do that now.

**Comment by yakra** [comment]
> graphs/index.php does the same basic thing as `tmdb_query`, without going thru the `tmdb_query` middleman itself.

My 1st thought was *"and the graphs page shouldn't be affecting what we see in the HB anyway"*, but on 2nd thought I do see some similar behavior, suggesting we're accessing the wrong DB.

We can't see this on noreaster, where *usatxf* is devel, but on lab2, *usatxf* is preview. `/graphs/` & `/graphs/?dbname=TravelMappingCopy` both report 12780 vertices & 14580 edges, same on noreaster.

Just to be absolutely sure, I queried TravelMappingCopy:
```SQL
mysql> select * from graphs where filename = 'TX-region-collapsed.tmg';
+-------------------------+---------------+----------+-------+-----------+-----------+----------+
| filename                | descr         | vertices | edges | travelers | format    | category |
+-------------------------+---------------+----------+-------+-----------+-----------+----------+
| TX-region-collapsed.tmg | Texas (State) |    14720 | 17089 |         0 | collapsed | region   |
+-------------------------+---------------+----------+-------+-----------+-----------+----------+
1 row in set (0.00 sec)
```

**Comment by jteresco** [comment]
Can you easily tell if this is still a problem with the new HB/showroute?

**Comment by yakra** [comment]
Easily, no. Not knowing the state of TravelMappingTest on noreaster, I'd have to set up a test on lab2, which means updating its Web software.

**Comment by jteresco** [comment]
I can update TravelMappingTest to current data if you want, or we can not worry about this now.

**Comment by yakra** [comment]
https://forum.travelmapping.net/index.php?topic=3102.msg19665#msg19665

> Attempting to update lab2 with (almost) the latest Web commits...
> https://github.com/yakra/Web/tree/lab2redo
> https://github.com/yakra/Web/tree/517ebc0898d11985bfaac5fdec2d5f0c8749dbf2
> 
> **HB is broken:**
> • No waypoints listed in table
> • Map stays centered at Siena,  and `Processing Route Waypoint Data...` message doesn't go away.
> 
> Mapview broken too; same basic symptoms as the 2nd bullet point.
> 
> For now, reverting to the previous head I'd been using...
> https://github.com/yakra/Web/tree/lab2
> https://github.com/yakra/Web/tree/4c7f5d9c607a0bc32c6478830214f9f83ce50000
> It will take some detective work to find just where things broke.

**Comment by jteresco** [comment]
Sounds like a symptom of a bad DB query leading to unparsable JSON.

**Comment by yakra** [comment]
> Sounds like a symptom of a bad DB query leading to unparsable JSON.

Something that's fine in MySQL 5.7 but not 8.0?

**Comment by jteresco** [comment]
Put in a console.log(data) before any potentially offending 

<pre>
    let responses = $.parseJSON(data);
</pre>

If it's good, you'll get some big output.  If not, you'll see what is hopefully a meaningful SQL error message.

**Comment by yakra** [comment]
> ```
> <?
> // big output
> ?>
> ```
> 
> ---
> :exclamation: :arrow_down_small: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data [[Learn More]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/JSON_bad_parse)
>   parseRouteStats http://192.168.2.4/lib/showroutefuncs.js:313
>   :arrow_down_small: jQuery 4
>   u
>   fireWith
>   k
>   n

**Comment by jteresco** [comment]
Odd that it doesn't give you a more detailed traceback.   Usually in that case, I see an (often-helpful) SQL error message where I expect to see data.

**Comment by yakra** [comment]
Would it help if I pasted in the JSON data?

**Comment by jteresco** [comment]
Yes, I think so.

**Comment by yakra** [comment]
**showroutefuncs.js:312:13**
```
<?
// read information from the TM database about the
// routes for the HB showroutes Route Stats table:
// mileage and traveler stat info
//
// Author: Jim Teresco, Travel Mapping Project, June 2020
//
$params = json_decode($_POST['params'], true);

// $params has 2 fields:
// roots - array of TM chopped route roots (e.g., ny.i090)
// traveler - user whose stats are to be included

// note that roots are in connected-route order for a connected route with
// multiple chopped routes, will be a single route for a chopped route
// or a connected route with just one chopped route

// need to buffer and clean output since tmphpfuncs generates
// some output that breaks the JSON output
ob_start();
require "./tmphpfuncs.php";
ob_end_clean();

// initialize the array of responses
$response = array();

$roots = $params['roots'];

// total number of users
$result = tmdb_query("SELECT COUNT(DISTINCT traveler) as numUsers FROM clinchedOverallMileageByRegion");
$response['numUsers'] = $result->fetch_assoc()['numUsers'];
$result->free();

// gather info about each chopped route
$response['mileage'] = array();
$response['listNames'] = array();
$response['numDrivers'] = array();
$response['numClinched'] = array();
$response['drivers'] = array();
$response['clinchers'] = array();
$response['avgMileage'] = array();
$response['clinchedMileage'] = array();
foreach ($roots as $root) {
    $result = tmdb_query("SELECT ROUND(mileage,4) as mileage, region, route, abbrev, banner FROM routes WHERE root='".$root."'");
    $row = $result->fetch_assoc();
    array_push($response['mileage'], $row['mileage']);
    $listName = $row['region']." ".$row['route'].$row['banner'].$row['abbrev'];
    array_push($response['listNames'], $listName);
    $result->free();

    $sql_command = <<<SQL
      SELECT
          COUNT(*) as numDrivers,
          IFNULL(SUM(clinched), 0) as numClinched,
          GROUP_CONCAT(traveler SEPARATOR ',') as drivers,
          GROUP_CONCAT(IF(clinched = 1, traveler, null) separator ',') as clinchers,
          ROUND(AVG(mileage),4) as avgMileage
        FROM clinchedRoutes
        WHERE route = '$root'
SQL;
    $result = tmdb_query($sql_command);
    $row = $result->fetch_assoc();
    array_push($response['numDrivers'], $row['numDrivers']);
    array_push($response['numClinched'], $row['numClinched']);
    array_push($response['drivers'], $row['drivers']);
    array_push($response['clinchers'], $row['clinchers']);
    array_push($response['avgMileage'], $row['avgMileage']);
    $result->free();
    
    if ($params['traveler'] != null) {
        $sql_command = "SELECT round(mileage,4) as mileage FROM clinchedRoutes where traveler='".$params['traveler']."' AND route='".$root."'";
        $result = tmdb_query($sql_command);
        $row = $result->fetch_assoc();
	if ($row != null) {
            array_push($response['clinchedMileage'], $row['mileage']);
	}
	else {
	    array_push($response['clinchedMileage'], "0.0");
	}
	$result->free();
    }
}

$tmdb->close();
echo json_encode($response);
?>
```

---
**showroutefuncs.js:423:13**
```
<?
// read information from the TM database about the
// routes for the HB showroutes Route Stats table:
// mileage and traveler stat info
//
// Author: Jim Teresco, Travel Mapping Project, June 2020
//
$params = json_decode($_POST['params'], true);

// $params has 2 fields:
// roots - array of TM chopped route roots (e.g., ny.i090)
// traveler - user whose stats are to be included

// note that roots are in connected-route order for a connected route with
// multiple chopped routes, will be a single route for a chopped route
// or a connected route with just one chopped route

// need to buffer and clean output since tmphpfuncs generates
// some output that breaks the JSON output
ob_start();
require "./tmphpfuncs.php";
ob_end_clean();

// initialize the array of responses
$response = array();

$roots = $params['roots'];

// total number of users
$result = tmdb_query("SELECT COUNT(DISTINCT traveler) as numUsers FROM clinchedOverallMileageByRegion");
$response['numUsers'] = $result->fetch_assoc()['numUsers'];
$result->free();

// gather info about each chopped route
$response['mileage'] = array();
$response['listNames'] = array();
$response['numDrivers'] = array();
$response['numClinched'] = array();
$response['drivers'] = array();
$response['clinchers'] = array();
$response['avgMileage'] = array();
$response['clinchedMileage'] = array();
foreach ($roots as $root) {
    $result = tmdb_query("SELECT ROUND(mileage,4) as mileage, region, route, abbrev, banner FROM routes WHERE root='".$root."'");
    $row = $result->fetch_assoc();
    array_push($response['mileage'], $row['mileage']);
    $listName = $row['region']." ".$row['route'].$row['banner'].$row['abbrev'];
    array_push($response['listNames'], $listName);
    $result->free();

    $sql_command = <<<SQL
      SELECT
          COUNT(*) as numDrivers,
          IFNULL(SUM(clinched), 0) as numClinched,
          GROUP_CONCAT(traveler SEPARATOR ',') as drivers,
          GROUP_CONCAT(IF(clinched = 1, traveler, null) separator ',') as clinchers,
          ROUND(AVG(mileage),4) as avgMileage
        FROM clinchedRoutes
        WHERE route = '$root'
SQL;
    $result = tmdb_query($sql_command);
    $row = $result->fetch_assoc();
    array_push($response['numDrivers'], $row['numDrivers']);
    array_push($response['numClinched'], $row['numClinched']);
    array_push($response['drivers'], $row['drivers']);
    array_push($response['clinchers'], $row['clinchers']);
    array_push($response['avgMileage'], $row['avgMileage']);
    $result->free();
    
    if ($params['traveler'] != null) {
        $sql_command = "SELECT round(mileage,4) as mileage FROM clinchedRoutes where traveler='".$params['traveler']."' AND route='".$root."'";
        $result = tmdb_query($sql_command);
        $row = $result->fetch_assoc();
	if ($row != null) {
            array_push($response['clinchedMileage'], $row['mileage']);
	}
	else {
	    array_push($response['clinchedMileage'], "0.0");
	}
	$result->free();
    }
}

$tmdb->close();
echo json_encode($response);
?>
```

**Comment by jteresco** [comment]
So it's not _running_ the PHP program, just _returning_ the text of the PHP program.  Looks like a web server configuration option is needed.

**Comment by yakra** [comment]
Oh boy. I started Googling without a clear idea of what to Google, and after some messing around with yum, php is no longer talking to MySQL...

**Comment by yakra** [comment]
mysqli... *is and is not* installed? Maybe? Oy vey...

**Comment by yakra** [comment]
Grumble. OK, so we're back. Somehow I ended up with both PHP 7.2.31 (with mysqli) and PHP 7.2.19 (without) installed.

@jteresco, any idea whether I'd want to look in php.ini (more likely) or httpd.conf (less likely) or what?
Any ideas on some good keyword combos to Google?

**Comment by jteresco** [comment]
You're welcome to check out /usr/local/etc/apache24/httpd.conf, /usr/local/etc/apache24/extra/httpd-vhosts.conf, and /usr/local/etc/php.ini-production on noreaster for clues.  

In particular, these lines look relevant:

<pre>
httpd.conf:LoadModule php7_module        libexec/apache24/libphp7.so
httpd.conf:    DirectoryIndex index.html index.shtml index.php
httpd.conf:    AddType application/x-httpd-php .php
</pre>

**Comment by jteresco** [comment]
Can you create and load a simple hello.php type of program and have it get executed and return the PHP output instead of just the code being returned as the result?

**Comment by yakra** [comment]
Not 100% sure I follow.
I did create a foo.php page:
```php
<?php                                                                                      
  echo "foo!<br>";                                                                         
  if (1 < 2) echo "Ayuh!<br>";                                                             
  else echo "Nope.<br>";                                                                   
  for ($a = 0; $a < 10; $a++) echo $a;                                                     
?>                                                                                         
```
The output is what one would expect.
So do I want to create another PHP file that somehow attempts to call the first one as a function?
FWIW, the "JSON data" pasted above is getRouteStats.php in its entirety.

**Comment by jteresco** [comment]
Looks like a problem with the POST request made by the AJAX call that doesn't happen on a standard PHP page load.

**Comment by yakra** [comment]
In here?
https://github.com/TravelMapping/Web/blob/9775ed79aec36bde4a98ec15c77ff0fea1f2e6de/lib/showroutefuncs.js#L284-L296

**Comment by jteresco** [comment]
Yes, that's a standard call as far as I know.  Must be something in the server that's deciding not to execute it.

**Comment by yakra** [comment]
Did you ever have to change anything to that effect in your server config, or did you more or less use Apache & PHP as they came out of the box in that regard.
I'd have no trouble believing that CentOS & FreeBSD come with different default config params.
I'll have to look at the files mentioned upthread in a bit, and compare to my own...

**Comment by jteresco** [comment]
I'm sure I made changes over the years, but my servers were already doing some PHP before TM came alone.

**Comment by yakra** [comment]
My current thinking is that there's more than one case of a `<?` instead of a `<?php?`, [which noreaster is OK with but not lab2](https://github.com/TravelMapping/Web/commit/47730f681f266e43167d5569316642114761066a), beyond getRouteStats.php as quoted above. Scouring the php files...

**Comment by yakra** [comment]
SUCCESS

**Comment by jteresco** [comment]
Wow, good catch.

**Comment by yakra** [comment]
@jteresco [wrote](https://github.com/TravelMapping/Web/issues/310#issuecomment-649073029):
> Can you easily tell if this is still a problem with the new HB/showroute?

Still a problem.
![RM3474](https://user-images.githubusercontent.com/13720877/86429974-11b3e880-bcbf-11ea-86fd-44596e7f0d44.png)

**Comment by jteresco** [comment]
How about if you leave off &sqldebug?

**Comment by yakra** [comment]
Same.

**Comment by jteresco** [comment]
Any clues in the generated page source?  If you'd like me to load up TravelMappingTest on noreaster, you can upload the file somewhere and I can populate that DB to try it there.

**Comment by yakra** [comment]
> Any clues in the generated page source?

Nope. The "good version" & "bad version" are identical.

> If you'd like me to load up TravelMappingTest on noreaster, you can upload the file somewhere and I can populate that DB to try it there.

Currently uploading ~yakra/TravelMapping/DataProcessing/siteupdate/cplusplus/TravelMappingCopy-20200702.sql (277722023 B)

**Comment by yakra** [comment]
graphs/index.php appears to always load from the DB pointed to by tm.conf, and not check the `dbname` param. Which makes sense, as there will only be one set of graph files stored on the server to download.

**Comment by yakra** [comment]
uploaded ~yakra/TravelMapping/DataProcessing/siteupdate/cplusplus/TravelMappingCopy-20200702.sql (277722023 B)

**Comment by jteresco** [comment]
TravelMappingTest on noreaster has been populated with that .sql file.

**Comment by jteresco** [comment]
Definitely still a problem in many places.  The dbname= QS parameter isn't being passed from page to page, and definitely not on to the AJAX calls.  This should be fixable.  I am hesitant to put the dbname into a browser cookie but that's probably the easiest.  We just don't have a way to switch DBs except through URL editing.  This could be something for an "advanced options" tab on a future implementation of #351.

**Comment by jteresco** [comment]
Note: I changed tm.conf on tmtest for now to point to the TravelMappingTest DB by default and I can see the usatxr routes everywhere I've tried.

So if we're going to support the dbname= QS parameter (something worth thinking about before major fixes) some work needs to be done to pass the parameter from page to page and to get it to the AJAX calls.

**Comment by jteresco** [comment]
So the question, probably for the collaborators part of the forum, is to see who thinks they might ever want to access an alternate DB, and if we can serve the needs of those who do by leveraging tmtest or creating additional instances of the site where the tm.conf file can be pointed to alternate DBs as needed.

**Comment by yakra** [comment]
I'm less concerned about the dbname= parameter being persistent than about the route just not showing up at all in the HB.

**Comment by jteresco** [comment]
I bet no one other than the two of us have used dbname, so I think it should go, and when you want to use an alternate DB, you set it in tm.conf.

**Comment by michihdeu** [comment]
> So the question, probably for the collaborators part of the forum, is to see who thinks they might ever want to access an alternate DB

I think that there are situation where it could help. E.g. when we have split DEU, ESP and FRA. Having the old and the new versions live for comparsion. Or for reviewing the revised active routes in Mexico. _Or the revised routes in BIH._

**Comment by jteresco** [comment]
> > So the question, probably for the collaborators part of the forum, is to see who thinks they might ever want to access an alternate DB
> 
> I think that there are situation where it could help. E.g. when we have split DEU, ESP and FRA. Having the old and the new versions live for comparsion. Or for reviewing the revised active routes in Mexico. _Or the revised routes in BIH._

But is the ultimate utility different than having two instances of the site, each pointed at a different version of the DB through their tm.conf entry?  I'd say anyone going to the trouble of and capable of loading an alternate version of the DB can easily enough modify the tm.conf of an alternate instance of the main site.  I can set up additional test servers (like tmtest.teresco.org) in maybe 10 minutes on request.

**Comment by jteresco** [comment]
See an upcoming forum post for new info about development and staging servers in addition to tmtest that I think can help eliminate the need for dbname=

**Comment by michihdeu** [comment]
I remember that you said it's not possible (anymore) to use tmtest with different DB data.... Was it when we split France? Or/and when we talked about Mexico...

**Comment by jteresco** [comment]
It is possible now.

**Comment by jteresco** [comment]
I used `dbname=` quite a bit the last few days as I was testing some changes.  It was a bit more convenient than editing `tm.conf` for what I was doing.  I still don't think there's much reason to go to the extent of trying to make sure `dbname=` is persistent.  I'm going to close the issue.
