### ISSUE TITLE
Removing code related to old "show hidden markers" checkbox

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#311]
A while back, some of our pages with maps included a "show hidden markers" checkbox.  It doesn't seem any current page has that, but the support for it is still in the code.  I'm guessing no one has a desire for this, since I haven't heard any complaints about it not being there.  Unless I hear that someone really needs this kind of functionality, I'm going to clean it out throughout the code base soon.

**Comment by yakra** [comment]
No big objection here. If I want to look at that info I can just load up a simple graph.

**Comment by jteresco** [comment]
Another thought: for individual routes, those who would care about the existence of and especially the labels of hidden waypoints would likely just load up the .wpt in the WPT Editor anyway.
