### ISSUE TITLE
Mapview: Unit conversion does not apply to connection popups

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#315]
Only `Length: 0.9841` is displayed w/o unit indication and the value does not change when switching from miles to km.

**Comment by jteresco** [comment]
This should be fixed on tmtest.  Please make sure it looks good and if so I'll get it on the production site.

**Comment by jteresco** [comment]
HDX functionality will be addressed separately after summer work on new AVs and other features is complete.  https://github.com/TravelMapping/EduTools/issues/88

**Comment by michihdeu** [comment]
Looks fine. Thanks 👍

**Comment by jteresco** [comment]
Live on the main site.
