### ISSUE TITLE
Shift-click to select multiple segments in mapview, produce .list entry in popup

### ISSUE THREAD

**Issue by mapcat** [TravelMapping/Web#316]
The new "edge/connection popups" feature (http://forum.travelmapping.net/index.php?topic=3105.msg14409;topicseen#msg14409) made me wonder if something like this would now be feasible.

Click to select a segment (edge) at one end of the route you travelled, and then shift-click another segment on the same route. The entire set of segments between the two would be highlighted, and the text in the popup would be formatted as a .list  entry.

Example: click on US 9 just north of I-84. Then shift-click on US 9 just south of US 44. Everything on US9 from I-84 to US 44 would be highlighted, and the popup would produce

NY US9 I-84 US44

The user could then just copy paste that into the .list file.

**Comment by jteresco** [comment]
Sounds like a nice feature.

One quick thought.  This might be easier to do in the highway browser, since there we know that there is just one route displayed at a time.  A number of complications could arise with Mapview for this, with the ambiguity about which route is selected when a segment carries a concurrency.

**Comment by yakra** [comment]
I like it. Also: the total distance for that segment.
Today I found myself clicking on several segments back-to-back, and adding up the mileage in my head. :)

**Comment by michihdeu** [comment]
#226 
> Like the HDX allows selection of start and end vertices for Dijkstra's algorithm, the HB could have a way to select start and end waypoints for a traveled segment and then generate a .list entry with the appropriate region, route, and waypoint labels that can easily be copied into a .list file.

**Comment by michihdeu** [comment]
> Example: click on US 9 just **north of** I-84. Then shift-click on US 9 just **south of** US 44. Everything on US9 from I-84 to US 44 would be highlighted, and the popup would produce
> NY US9 I-84 US44

I like the idea very much but I think the result should be `NY US9 NY52 HofSt` since the segments selected should be included!

For `NY US9 I-84 US44` you would need to click **south of** I-84 and **north of** US44.

**Comment by mapcat** [comment]
> Sounds like a nice feature.
> 
> One quick thought. This might be easier to do in the highway browser, since there we know that there is just one route displayed at a time. A number of complications could arise with Mapview for this, with the ambiguity about which route is selected when a segment carries a concurrency.

IMO the feature would be a lot more helpful in Mapview, since I picture it being an aid to users adding to their .lists after a multi-route trip. Continuing my example, A user could have taken US 9 from I-84 to US 44, then US 44 to the Taconic State Pkwy, then the Taconic to I-90. In Mapview, since all routes are on the map at the same time, the process of creating one .list line after another would be simplified.

> I like the idea very much but I think the result should be `NY US9 NY52 HofSt` since the segments selected should be included!
> 
> For `NY US9 I-84 US44` you would need to click **south of** I-84 and **north of** US44.

No, clicking on the segment north of I-84 and the one south of US 44 should produce a multi-segment line stretching from I-84 to US 44, making I-84 and US44 the endpoints of that segment (I-84 is south of US 44).

**Comment by michihdeu** [comment]
@mapcat yes, I was wrong. Sorry.

**Comment by jteresco** [comment]
I was considering this instead of working on the much less interesting thing I need to accomplish today.  I don't think it's too bad to do in Mapview.  A user could select as many segments as he or she wishes, then we can generate a set of .list entries that correspond to all selected.

**Comment by vdeane** [comment]
The only thing I can see with Mapview is, there are some spots where segments are drawn practically on top of each other but don't overlap, so there would need to be a way of dealing with those.  MA 79/US 6 in Fall River comes to mind.

**Comment by yakra** [comment]
> The only thing I can see with Mapview is, there are some spots where segments are drawn practically on top of each other but don't overlap, so there would need to be a way of dealing with those. MA 79/US 6 in Fall River comes to mind.

Not familiar enough with Leaflet to know how it handles events for clicking on two polylines in the same place (though, how does TM's tier stacking work now? Do lower-tier routes not *have* polylines on the map? Are they still there, only transparent?) or two polylines at almost but not exactly the same place? Leaving this aside while I brainstorm...

Maybe if there's >1 route within whatever radius of the coordinates clicked

**Comment by yakra** [comment]
@vdeane [wrote](https://github.com/TravelMapping/Web/issues/316#issuecomment-526425322):
> The only thing I can see with Mapview is, there are some spots where segments are drawn practically on top of each other but don't overlap, so there would need to be a way of dealing with those. MA 79/US 6 in Fall River comes to mind.

Not familiar enough with Leaflet to know how it handles events for clicking on two polylines in the same place (though, how does TM's tier stacking work now? Do lower-tier routes not have polylines on the map? Are they still there, only transparent?) or two polylines at almost but not exactly the same place? Leaving this aside while I brainstorm...

Maybe if there's >1 route within whatever radius of the coordinates clicked, produce a dialogue box of the routes nearby & allow the user to select.

@jteresco [wrote](https://github.com/TravelMapping/Web/issues/316#issuecomment-508961958):
> A number of complications could arise with Mapview for this, with the ambiguity about which route is selected when a segment carries a concurrency.

To simplify the thought process, I'll take a few parts of the OP literally...
@mapcat wrote:
> Click to select a segment (edge) at one end of the route you travelled, and then shift-click another segment **on the same route**. The entire set of segments between the two would be highlighted, and the text in the popup would be formatted as a .list entry.
>
> Example: click on **US 9** just north of I-84. Then shift-click on **US 9** just south of US 44. Everything on US9 from I-84 to US 44 would be highlighted
* If the first click was on a segment of solo US9, and the shift+click was also on US9, highlight US9 from Point A to Point B, and do the popup as described.
* If the first segment is on US9 concurrent with (or very closely overlapped with as @vdeane described) something else? I'm thinking probably select one of these routes upon the initial click as I described above.

**Comment by jteresco** [comment]
I'm going to go ahead and close this, since the new showroute (HB) that will be going live soon has this functionality, and adding it to Mapview doesn't seem like as good of a fit for this functionality.
