### ISSUE TITLE
wpt editor: always center map option

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#322]
Load a route and zoomed-in deep. Now, click on a line of the wp table on the left, and you'll get the wp displayed in the center of the map. If you click on a different line on the table, the wp is also displayed in the center again. However, if the 2nd wp is already displayed on the map - not center but anywhere else on the map - the map is not centered to that wp.

When I review a route, I click from wp to wp and check the position. It's quite annoying when the map is not centered and I need to move it manually so that I can see the name of the intersecting route et cetera. That happens when the wp is in the corner of the map view.

I don't know whether the current behavior is needed but I'd minimum like to be able to switch to the "always centered" option.

We do have the same behavior in HB. Maybe it's fine there as-is?

Thoughts?

**Comment by yakra** [comment]
I have to wonder if this is a "feature" of the way `panTo` works in Leaflet, and whether there's a way around it. I agree, this is annoying and needs a fix.

I like to be able to click on a line on the wp table and have the map centered there so the `Street View` button will link to the right place. This doesn't work a lot of the time, and I have to waste time manually scrolling the wp out of the viewport before I click the wp table.

> I don't know whether the current behavior is needed but I'd minimum like to be able to switch to the "always centered" option.

I don't have much use for the current behavior personally, and would be fine with having only the "always centered" option.

**Comment by michihdeu** [comment]
Did we have the same behavior in the past? With the Google API? Or even with Leaflet API? Has it changed? I haven't used the wpt editor when I was traveling in May/June and when I was back Mid June, it started to annoy me. The behavior might be fine in HB but **not** in wpt editor.

**Comment by jteresco** [comment]
The most recent edit to any WPTEdit code is over a year ago.  But behavior could have changed when I upgraded our Leaflet version.

**Comment by yakra** [comment]
Not 100% certain on this, but I think leaflet has always behaved this way.
Google would always center the map.

**Comment by jteresco** [comment]
It looks like Leaflet provides a setView method that might force centering, unlike panTo, which seems to just ensure that the point is visible within the view.

**Comment by michihdeu** [comment]
https://gis.stackexchange.com/questions/283487/leaflet-setview-vs-panto

**Comment by yakra** [comment]
It looks like the `panTo` operation is interrupted by opening the popup before it can finish.
https://github.com/TravelMapping/Web/blob/74cd2d4e4cfccb7e0fe48d72813da5e7df2a417a/wptedit/wptfunctions.js#L417-L418
When I change the order of these two lines, wptedit will pan right to the center when I click on a wp in the table.
Demo online on lab2. Pull request shortly.
