### ISSUE TITLE
lab2: HERE tiles do not work

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#326]
On yakra's [mirror site "lab2"](http://205.209.84.174), both HERE tiles do not load. I was not sure yesterday whether it's a general issue but today it works on our main site http://travelmapping.net but it does still not load on lab2.

I've not check all tiles.

Edit: Hell, I wanted to close the tab now and it's loaded now. It seems that it just takes very long (> 30s) till it's loaded!?!?

**Comment by michihdeu** [comment]
I've closed all browser windows to empty cache.... No it was loaded immediately ❔ ❗️ I don't get it..... 😠

**Comment by yakra** [comment]
> Edit: Hell, I wanted to close the tab now and it's loaded now. It seems that it just takes very long (> 30s) till it's loaded!?!?

> I've closed all browser windows to empty cache.... Now it's loaded immediately :grey_question: :exclamation: I don't get it..... :angry:

I bet what happened here was you opened a map on noreaster that showed the same tiles, which were then loaded from your browser cache. I've seen similar behavior.

---

I never bothered getting the id/code/key/token for Here, or Mapbox, or Thunderforest, and in the past had just had all of these disabled.
Apparently I zapped that when I was bringing in Jim's changes from GitHub, or reverting some test changes of my own or something.
Disabled again.

**Comment by michihdeu** [comment]
> I bet what happened here was you opened a map on noreaster that showed the same tiles, which were then loaded from your browser cache. I've seen similar behavior.

yep. Exactly. But why did it persist after browser closing and opening again?

but it's fine when it's disabled. Never mind!

**Comment by yakra** [comment]
> But why did it persist after browser closing and opening again?

Just tested it out & got the same behavior.
