### ISSUE TITLE
mapview / HDX: Popup does not open at the "click position"

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#327]
Zoom-in to limit, click on a connection and the popup does often not open at this position but recenters everything so that the map is at a different position and the popup does not appear where I've clicked.
I don't care where the popup appears but the map "jumps" to a different position and I need to zoom-out, look where I'm, go back to the previous position and zoom-in again.

I don't understand the behavior. It sometimes works but especially when zoomed-in deep, it's crap.

**Comment by yakra** [comment]
Weird. The first time I click on a connection, the popup appears near its midpoint.
Subsequent clicks popup at the coords where I clicked. Even if I click on a second connection, then back on the first connection again.

**Comment by jteresco** [comment]
The problem here is that the Polyline ended up with multiple popups bound to it, with a new one added each time.  I have a fix for this as part of the "put the popup at the northernmost point" experiment on tmtest.

**Comment by michihdeu** [comment]
Still the same behavior and popup is **not** at northernmost position. Where have you changed it, mapview? http://tmtest.teresco.org/user/mapview.php

**Comment by jteresco** [comment]
I have and it's working for me here.  First, let's make sure your browser isn't caching old JS file versions.  If that doesn't help we can investigate further.

**Comment by michihdeu** [comment]
I had not seen your forum post:
> I've also changed it so at zoom levels 12 and up, it does not force the popup at the northernmost point.

I'll have another try.

**Comment by michihdeu** [comment]
I was zoomed-in too much. When I zoom out, the popup appears at the northernmost point 👍 
Since the issue reported happens when I'm zoom-in deep, your recent change does not apply here and does not fix the issue.

**Comment by jteresco** [comment]
I think I misunderstand the issue then.  When zoomed in close, the popup will appear at the center of the given segment.  If the popup comes up in an area off the map, it will be scrolled so you can see it.  It should no longer jump around seemingly randomly, since I removed the duplicate popups that were causing that problem.

**Comment by michihdeu** [comment]
Got it! Yes, it's not "randomly" anymore. That's a step forward. I think it's "good enough" for mapview and HB but.... maybe I should explain what I wanna do:

When I wanna add or move a wp to an existing route, I usually open HDX first to figure out whether there are concurrent routes. Then, I check the exact route name(s) in the popup. I often zoom in close to check the exact position with a satellite tile and then click on the segment to get the popup for the route name(s).
If there is already a wp where I need to "connect" a new route, I check both existing segments because it might be possible that route A and route B start or end here and the wp label for the new route C would be A/B.
HDX and the popups are very useful here.

Thought: Is it possible to open the popup at the center of the given segment within the display? Only consider the visible part of the segment for calculating the center position?

**Comment by jteresco** [comment]
How about when zoomed in close enough (I chose 12 pretty arbitrarily, maybe should be a little higher or lower) I see if I can get the popup right at the click point so the map should never need to move/zoom or anything else to display it?

**Comment by michihdeu** [comment]
yep, also fine or even better 😃

**Comment by jteresco** [comment]
OK, check it out on tmtest now.  Popup at click point when zoomed in deep.

If when working with it, you think the threshold should change one way or another, just let me know.

**Comment by michihdeu** [comment]
THANKS! I've checked it with http://tmtest.teresco.org/user/mapview.php?rg=LIE and http://tmtest.teresco.org/user/mapview.php?rg=QC

I would change the threshold to 13 for LIE but to 11 for QC. So, leave as-is at 12.

Is there also a test HDX?

**Comment by jteresco** [comment]
You can see an HDX with these changes (and more) at http://courses.teresco.org/metal/hdxtmtest/

**Comment by jteresco** [comment]
The changes for this are in GitHub and on tmtest, but can't easily go live until we have a fix for #328.

**Comment by jteresco** [comment]
Looks like I broke something and popups are further south, not furthest north in some cases.  Working on it.

**Comment by jteresco** [comment]
The current problem is that sometimes the array of points that make up a Polyline is just an array of 2-element arrays of numbers (mapview), sometimes that array is an array of LatLng objects (HDX).

tmtest will be breaking occasionally while I see what I can do about this.

**Comment by michihdeu** [comment]
hdxtmtest... I've just tried tmtesthdx

**12 is also fine to me on HDX.**

**Comment by jteresco** [comment]
Is this still relevant?
