### ISSUE TITLE
HB: extraneous LEFT JOIN?

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#333]
https://github.com/TravelMapping/Web/blob/003643c07d33500e7fcad5d95dd6e7453ad63310/hb/index.php#L365-L375

Is this LEFT JOIN necessary? We don't appear to use any of the data from `systems`.

**Comment by jteresco** [comment]
Just noticed this one.  Seems worth removing.

**Comment by yakra** [comment]
FWIW, this is the same query in #288.

**Comment by michihdeu** [comment]
Remove "question" label?

**Comment by jteresco** [comment]
Yes.

**Comment by jteresco** [comment]
Turns out we do actually use data from systems to get the tier and level.  Leaving alone.
