### ISSUE TITLE
tools.php: Deprecated link to CHM manual

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#336]
http://cmap.m-plex.com/tools/manual.php does not work anymore and should be removed.

**Comment by yakra** [comment]
I archived it at one point, and hope I still have a copy available.
...somewhere other than that thumb drive I physically broke...

**Comment by jteresco** [comment]
Unfortunately, it didn't have a public link, so the Internet Archive doesn't have a copy.

http://web.archive.org/web/*/http://cmap.m-plex.com/tools/manual.php

**Comment by jteresco** [comment]
In any case, it's about time we had our own.  We have lots of people good at developing and reviewing highway data.  Let's make it happen.

**Comment by yakra** [comment]
Found a copy right here on my main desktop, in an out-of-the-way place I didn't expect to look at first. I'll fix some of the links up to not point to cmap.m-plex.com, and then put it online.

**Comment by yakra** [comment]
http://yakra.teresco.org/manual/manual.html
It's chock full of outdated info, but it's a start. Better than having all this just disappear on us.

I'll see about updating some of the info there. Maybe. ;)
