### ISSUE TITLE
General: server using https: instead of http:

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#337]
I'd like to get the current location functionality implemented (#211) but this likely requires our server to run with https instead of http.

Anyone have experience setting up a web server with https and getting the needed certificates, etc.?

**Comment by jteresco** [comment]
https://letsencrypt.org/ looks promising.

**Comment by vdeane** [comment]
I've heard good things about Let's Encrypt, though I haven't used them myself.  If I remember right, they use short-duration certificates with automated renewal.

**Comment by jteresco** [comment]
The conversion is complete and both the main site and forum are running over https.  Please open new Issues if any problems are noted as a result of this conversion.
