### ISSUE TITLE
mapview: "update in progress" banner

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#338]
Observed on lab2:
If I load mapview.php during a DB update, the red "Travel Mapping database update in progress" banner initially appears as the page first loads. When loading finishes, the banner is gone.

To duplicate this on noreaster, I'll have to know when an update is happening.
Hopefully, next time I see one happening I'll remember to try it out.

**Comment by jteresco** [comment]
Quick guess: the map ends up on top of it.
