### ISSUE TITLE
Manual: step-by-step to introduce a new highway system

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#343]
Quick thoughts:

1) discuss on the forum, present sources
2) develop routes and csvs in devel status
3) when first complete draft is in the HB, promote to preview (add systemupdates entry)
4) request peer review
5) make changes based on peer review or explain why they should not be made
6) clear datacheck and NMP issues
7) activate (add systemupdates entry)
8) maintain (add updates entries as needed)

**Comment by michihdeu** [comment]
I'd add the pre-condition for new hwy data managers:

> Some experienced users volunteer to help the project. If this interests you, start by reporting problems with existing highway data. Those who have learned the project's structure and highway data rules and guidelines can help greatly by providing review of new highway systems in development. Highly experienced users can learn how to plot new highway systems under the guidance of experienced contributors.

step 1 might (or should/must ?) start with opening a new thread on the right board
step 2 needs a detailed description including Github data structure
step 3 might be split into several sub-systems with partial preview promotion (?)
step 4 should be an active trigger, not a hidden notice
step 6 (or earlier?) concurrencies with existing routes should be checked

_second parts of step 1 and step 5 would be really great @si404_

**Comment by jteresco** [comment]
Maybe a second step-by-step list for "how to become a highway data contributor".

1) become an active user to be familiar with the system
2) catch up on previous discussions and follow current discussions on the forum about highway data updates
3) report updates and problems in existing systems
4) participate in peer review of a preview system
5) take responsibility for updates in an unclaimed region, or by requesting to become the maintainer for a region from someone looking to unload some of theirs
6) develop a new system

**Comment by michihdeu** [comment]
> become an active user to be familiar with the system

Which system? I think you mean project strucure or something like this?

**Comment by jteresco** [comment]
> > become an active user to be familiar with the system
> 
> Which system? I think you mean project strucure or something like this?

By this I mean become familiar with it from the user's point of view.  Creating list files, finding highway names, seeing how routes are organized into highway systems.

**Comment by yakra** [comment]
> 5. take responsibility for updates in an unclaimed region, or by requesting to become the maintainer for a region from someone looking to unload some of theirs
> 6. develop a new system

I'd put these in reverse order. The reason being, someone new to the editing/contribution process may not intuitively have all the finer points down; point placement, labeling, datacheck, etc.
A new system will first need to undergo peer review. During that process we should have all these aspects under the magnifying glass, and offer direction as how to best Do All The Things.
Letting a new contributor go to town on active data without first instilling that sense of best practices could potentially add a lot of noise to the signal, stuff to have to clean up.

**Comment by michihdeu** [comment]
> I'd put these in reverse order. 

I had the same thought. Technically, I'm with you but considering that we still have some "unclaimed regions", Jim's order has advantages too. We might merge step 5+6 and call it "ask on the forum for taking responsibility of an active system or for developing of a new system."

**Comment by michihdeu** [comment]
> 6. clear datacheck and NMP issues

**Example on Georgia of How To use HDX for checking concurrencies and NMPs:**
http://forum.travelmapping.net/index.php?topic=215.msg17077#msg17077

**Comment by michihdeu** [comment]
> 4. request peer review

#342

**Comment by michihdeu** [comment]
> develop routes and csvs in devel status

If there are already routes in that region (active or preview), check them first. Then, add wp labels to them you need for your new system.

**Comment by michihdeu** [comment]
> 1. discuss on the forum, present sources
> 2. develop routes and csvs in devel status

please refer to #400

**Comment by michihdeu** [comment]
@jteresco please close the issue!
