### ISSUE TITLE
Manual: connected route csvs

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#344]
https://github.com/TravelMapping/Web/blob/8aa4dba1b77c6be2cfeab2030504ae62e1fd98ba/devel/manual/syshwylist.php#L147

This "FIXME" came in from CHM.

**Comment by yakra** [comment]
That was me, post-CHM. ;)
Fixed a few things or made notes, on that page only, but didn't get too far with it.

**Comment by michihdeu** [comment]
This is not a "rule". The change does not require a poll.

**Comment by michihdeu** [comment]
@jteresco wrote [here](https://github.com/TravelMapping/Web/issues/505#issuecomment-650189168):
> In the case of new highway data managers, I think "don't use Excel, if you want a spreadsheet download OO" would be sufficient.

https://travelmapping.net/devel/manual/syshwylist.php#intlatin

**Comment by michihdeu** [comment]
https://github.com/TravelMapping/Web/pull/529
