### ISSUE TITLE
Manual: defunct static maps from CHM manual

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#345]
https://github.com/TravelMapping/Web/blob/8aa4dba1b77c6be2cfeab2030504ae62e1fd98ba/devel/manual/points.php#L36

The CHM manual used to have static maps showing examples of waypoint positioning.  These are all now commented out.  If we want these, we'll have to make some new maps.

**Comment by michihdeu** [comment]
I think that the textual description is sufficient: https://travelmapping.net/devel/manual/points.php#interchanges

**Comment by jteresco** [comment]
I agree that these are not necessary.  Closing.
