### ISSUE TITLE
Manual: additional waypoint labeling rules

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#346]
https://github.com/TravelMapping/Web/blob/be1ed22d580e69cc77413eea38e61b0f164197b5/devel/manual/wayptlabels.php#L680

Anyone aware of waypoint labeling rules we've adopted since CHM's rules were last updated?

**Comment by yakra** [comment]
Exit numbers are now allowed on United States Numbered Highways.

**Comment by michihdeu** [comment]
- [alt labels should be allowed in preview systems](http://forum.travelmapping.net/index.php?topic=65.msg15405#msg15405)
- [Truncated, visible cross road name & Truncated junction name - for freeways/expressways with official destination-based named junctions](https://github.com/TravelMapping/HighwayData/pull/3073#issuecomment-532717386) seems to be outdated?

**Comment by yakra** [comment]
> - [alt labels should be allowed in preview systems](http://forum.travelmapping.net/index.php?topic=65.msg15405#msg15405)

Agree, they should be allowed, if for no other purpose than letting the maintainer take notes.
However, the manual never explicitly forbade them before, right? If that's the case, there's nothing to change, and this could probably be simply left out for simplicity's sake.

> - [Truncated, visible cross road name & Truncated junction name - for freeways/expressways with official destination-based named junctions](https://github.com/TravelMapping/HighwayData/pull/3073#issuecomment-532717386) seems to be outdated?

Mm... I remember that thread being a bit tricky, and needing... some kind of new consensus. I don't think that consensus ever fully developed, though. I lost track of that thread, forgot what was going on a bit...

**Comment by michihdeu** [comment]
I didn't check the manual but only had these links on my offline to do list. It was getting confusing, so I sorted everything into the issues here 😄

I think that the "alt label" thing must be generally described anywhere. Likely here and in the "How to develop a new system" topic #343 It's a MUST for active but a SHOULD for preview systems.

Truncated invisible cross road names are used all over Europe and likely Asia, Africa,... I think that the "visible" is a MUST in USA (and Canada?) but a SHOULD or COULD in ROW (rest of world).

I remember the **"59E" etc. wp labels in canmbp** system which are often not signed....... this is also not covered by the current manual version.

**Comment by yakra** [comment]
> I think that the "visible" is a MUST in USA (and Canada?)

ISTR the definition of "visible" being a potential sticking point -- visible just on maps (e.g. OSM), or visible in the fields on blade signs etc.?

> I remember the **"59E" etc. wp labels in canmbp** system which are often not signed....... this is also not covered by the current manual version.

There may well be similar examples on section line roads in Oklahoma. And who knows wherever else...

**Comment by michihdeu** [comment]
visible on maps is fine to me 😄 We should clarify it on the manual. Maybe SHOULD be visisble on-site (GSV) but MUST be visible on any map (available as HB layer? prefered OSM?)

**Comment by michihdeu** [comment]
- [the route number to list will often but not always be the lower-numbered one](http://forum.travelmapping.net/index.php?topic=3227.msg17272#msg17272) but can also be the higher-numbered one if this route is more important and/or the only signed route (e.g. where A164, A1035 and A1174 intersect)

**Comment by michihdeu** [comment]
[For auxiliary routes connecting to the parent route at both ends, mention only the parent route (even if it is concurrent with other routes) and add direction suffixes.](http://forum.travelmapping.net/index.php?topic=3056.msg17593#msg17593)
vs.
[Putting two highways in a waypoint label](http://forum.travelmapping.net/index.php?topic=3056.msg17597#msg17597)

http://travelmapping.net/hb/index.php?r=wa.wa240busric

**Comment by michihdeu** [comment]
This is more complex and needs to be checked down the road...

**Comment by michihdeu** [comment]
[Fake Exit Numbers](https://forum.travelmapping.net/index.php?topic=2923)

**Comment by michihdeu** [comment]
> * [ ]  [For auxiliary routes connecting to the parent route at both ends, mention only the parent route (even if it is concurrent with other routes) and add direction suffixes.](http://forum.travelmapping.net/index.php?topic=3056.msg17593#msg17593)
> vs.
> [Putting two highways in a waypoint label](http://forum.travelmapping.net/index.php?topic=3056.msg17597#msg17597)

Proposal for forum poll: Remove the whole [Waypoints for ends of auxiliary routes](https://travelmapping.net/devel/manual/wayptlabels.php#auxroutes) paragraph because the [Putting two highways in a waypoint label](https://travelmapping.net/devel/manual/wayptlabels.php#2highways) only says `Two numbered highways may appear in a waypoint. You can use two designations` but does not say that one MUST add both. The auxilary routes message could be integrated into that like the `If one of the two highways is already long as a label....` exception.

**Comment by michihdeu** [comment]
> Exit numbers are now allowed on United States Numbered Highways.

- [x] Already changed: https://github.com/TravelMapping/Web/pull/512

**Comment by michihdeu** [comment]
This will only **require one poll** for wps with more than one intersecting highway. The rest is already addressed.

**Comment by michihdeu** [comment]
Poll: https://forum.travelmapping.net/index.php?topic=3725

**Comment by michihdeu** [comment]
The remaining rule change was rejected.
