### ISSUE TITLE
System Highway Lists: zero-padding

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#347]
https://github.com/TravelMapping/Web/blob/8aa4dba1b77c6be2cfeab2030504ae62e1fd98ba/devel/manual/syshwylist.php#L71-L73

Some systems (GBNA, USAXTL, USATXS) are padded out to 4 digits. USANES only uses 2 digits.

Sometimes, for an asciibetical rather than a numeric filename sort, it makes sense to not pad with zeros. I believe this is the case with EURE, right? (Ping @si404)

Will a simple `(number padded with zeroes as needed)` suffice?

**Comment by jteresco** [comment]
My assumption about the EURE exception to the zero-padding is because the "E" is part of the route designation.  If that's the case, it could be stated as such.  We've also not put in the zero-padding in other places where route "numbers" start with a letter like VT F5 and FL A1A.

**Comment by si404** [comment]
The lack of zero padding for E Roads is that some routes are E0xx - Tim, foresaw the problem of same-named route files (though there wouldn't be as routes stand) clashing and changed eure to drop trailing zeros. Even where they are signed (eg E01 in Ireland) due to Spain, France and Scandinavia not signing them. It has nothing to do with the numbers being alphanumeric (cf the UK, Ireland, France, Benelux, Spain where padding is included).

But the problem isn't that bad. In Galicia there's PO10 (A Spanish city motorway) and PO010 (A Galician expressway). sh datacheck.sh pulled it up on that, so I gave the newer, less important, route a suffix (Vig for Vigo) that I just didn't mention outside the file name and it worked. There wouldn't be a list clash as one has the trailing zero.

dnkpr is padded to 2 digits, but I can't remember why I did that but 3-digited all the other ones that have a max of two digits (which is really rather common).

gbna was the first I padded to 4 digits. Simple reason of a lot of four digit routes and this meant better ordering in folders/lists. Good to see that it's been used elsewhere.

Should also point out that routes with decimal places are written so that the digit beyond the decimal place is beyond the standard number. So the A11.1 in France is fra.a0111, with the A11 as fra.a011.

**Comment by michihdeu** [comment]
> In Galicia there's PO10 (A Spanish city motorway) and PO010 (A Galician expressway). sh datacheck.sh pulled it up on that, so I gave the newer, less important, route a suffix (Vig for Vigo) that I just didn't mention outside the file name and it worked. There wouldn't be a list clash as one has the trailing zero.

Sorry, I don't get it. Why does datacheck pull it up?

> dnkpr is padded to 2 digits, but I can't remember why I did that but 3-digited all the other ones that have a max of two digits (which is really rather common).

Since DNK is mine now, I couldn't change it. No big deal, just let me know.

> gbna was the first I padded to 4 digits.

Same for France.

**Comment by si404** [comment]
No idea why we can't have ESP-GA/espa/espga.po010 and ESP-GA/espga/espga.po010 when they have separate list names (PO10 and PO010 respectively), but we can't.

**Comment by si404** [comment]
writing some update entries and twigged why you can't have two files with the same root, even if they are different systems (and thus different folders). I mean it's really not a problem - it was a quickly fixed error message.

**Comment by michihdeu** [comment]
why? Because wpt file name is exactly the same?

**Comment by yakra** [comment]
when you plug `r=espga.po010` into the HB, which one is going to load?

**Comment by yakra** [comment]
So, ESPA is a system where we *do* normally want to pad to 3 digits, I presume?

**Comment by si404** [comment]
@yakra - worked that out as soon as I was a bit more awake! ;)

espa, as originally done, only had 1- and 2-digit routes (by definition), but had the leading zeros. It now has a couple of three digit routes (as I changed the definition). Pretty sure dnkpr is the only system that is 1-/2-digits by definition that isn't padded to three digits.

**Comment by yakra** [comment]
So there's no clear definition from Spain that we can use, and need to settle on our own definition for TM purposes, one of those deals?

> Pretty sure dnkpr is the only system that is 1-/2-digits by definition that isn't padded to three digits.

In [usanes](travelmapping.net/hb/?sys=usanes) The numeric part of the designation corresponds to one of Nebraska's 93 counties. The letter "suffix" is in effect the *real* "route number" therein.

> gbna was the first I padded to 4 digits. Simple reason of a lot of four digit routes and this meant better ordering in folders/lists. Good to see that it's been used elsewhere.

Definitely the sensible thing to do in that system.
And usala too, can't forget about that.
Back in the CHM days, TXLp1604 was the only 4-digit route I'm aware of, hanging out with a bunch of 3-digit routes in usansf. I kept that arrangement when transitioning over to usatxl.
TXSpr1966 was added after usatxs's initial import, and I did the same thing, letting just the one odd route hang out. I mean like whatever. With the [more recent addition of TXSpr1570](http://www.dot.state.tx.us/tpp/hwy/ss/ss1570.htm), padding out to 4 digits is more obviously the right thing to do.

Had trouble understanding [this post](https://github.com/TravelMapping/Web/issues/347#issuecomment-526891867)... Before I get too far into the weeds, @si404, did you mean "leading" when you said "trailing"?

I suppose that I don't need to understand the eure situation in complete detail to address the OP...
> Will a simple `(number padded with zeroes as needed)` suffice?

gbna and usala have shown that in some cases it's sensible to pad out to 4 digits, and the instruction re 3 digits should probably go. Contributors should be able to see what's the right thing to do for a given system. In the rare Cases of the Less Obvious, we can sort that out in the forum during development.

**Comment by si404** [comment]
> Had trouble understanding this post... Before I get too far into the weeds, @si404, did you mean "leading" when you said "trailing"?

Yes I meant "leading". I was tired - it was 20 to 8 in the morning, and I had dealt with the PO10 vs PO010 problem just 6 hours earlier.

**Comment by michihdeu** [comment]
This is not a "rule". The change does not require a poll. Any objections?

**Comment by yakra** [comment]
[This looks like a rule to me](https://travelmapping.net/devel_new/manual/syshwylist.php#croot).

**Comment by michihdeu** [comment]
ok, another poll to come.....

**Comment by yakra** [comment]
Personally I think we're fine without a poll, to go ahead and change the rule; there's enough precedent for different amounts of zero padding, that the "new rule" has already been adopted.

Though if you'd still want to open the topic up to discussion on the forum, get advice on wording or whatever, that's cool. :)

**Comment by michihdeu** [comment]
It is described at two locations of the manual right now. Even differently and less detailed where it is more important.

I think it should only be described where we create the wpt files https://travelmapping.net/devel_new/manual/hwydata.php#zeropadded and a link to it should be put to the csv description at https://travelmapping.net/devel_new/manual/syshwylist.php#croot

@yakra / @si404 What does this mean: `(number padded with zeroes for three digits unless the number is 100+)` I think it should it be `1000+`, shouldn't it?

**Comment by yakra** [comment]
Three digits including *but not limited to* zeros

**Comment by michihdeu** [comment]
Where this will be described, I need to add a little info how it is stored on github hwy_data/_region_/_system_

**Comment by michihdeu** [comment]
Poll: https://forum.travelmapping.net/index.php?topic=3712
