### ISSUE TITLE
Feature: New "Tier" column in highway browser

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#35]
I think the column should be added because it's also available in the user stats and it's helpful if you browse by region, for instance http://tm.teresco.org/devel/hb.php?sys=&rg=ltu has tier 2, 3 and 4 roads.

**Comment by Thing342** [comment]
Don't remember when it happened, but it seems like the desired functionality has been added.

**Comment by michihdeu** [comment]
??? No, it isn't! **Tier** column is not displayed in the HB, e.g. http://tm.teresco.org/hb/index.php?sys=null&rg=DEU!

**Comment by Thing342** [comment]
Shoot, didn't realize you were talking about when the filters are applied, my bad. I'll add this in an upcoming pull request.

**Comment by michihdeu** [comment]
Hmmmm, it displayed on the [url=http://tm.teresco.org/hb/]start page[/url] but not when a [url=http://tm.teresco.org/hb/index.php?sys=null&rg=DEU]region[/url] or [url=http://tm.teresco.org/hb/index.php?sys=deua&rg=null]system[/url] is selected (okay, the latter seems to be useless but should be displayed as "info").

**Comment by jteresco** [comment]
I have only installed today's changes on tmtest so far, not tm.

**Comment by michihdeu** [comment]
Ah, I see :). Looks a little bit odd that the order is different to the start page...
