### ISSUE TITLE
mapview: rte= bug when no user in cookie

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#366]
Delete your cookie, or start with a fresh browser that doesn't have one.
Then check out http://travelmapping.net/user/mapview.php?rte=ME11
The routes are stitched together in asciibetical order:
* There's an edge connecting the end of ME11 to the start of ME11ACha.
* There's an edge connecting the end of ME11ACha to the start of ME11ASan.
* There's an edge connecting the end of ME11SAan to the start of ME11BMil.

OK, got that? Now, check out http://travelmapping.net/user/mapview.php?rte=A1 :laughing:
Clicking on any edge, even the ones that represent legitimate highway segments, does not produce a popup.

**Comment by michihdeu** [comment]
The IP of your local network? 😉

**Comment by yakra** [comment]
Oops. And the other link was somehow missing the http:. Fixed both.

**Comment by jteresco** [comment]
Am I correct that this is not relevant in the current mapview, as the rte= is no longer doing the simple pattern match?

**Comment by jteresco** [comment]
This seems to have been fixed long ago, or maybe just become irrelevant with changes to how Mapview works.  Closing.
