### ISSUE TITLE
datacheck.php: link to HB centered at error

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#368]
It might be useful to use the new `lat=`, `lon=`, & `zoom=` HB parameters to link from datacheck.php to the HB directly zoomed in on the point(s)in the DC entry.

The center of our panning position will be different depending on whether the entry has 1, 2 or 3 waypoints. To obtain coords to pan to, I tried out a conditional join of the waypoints table.
However, since all we have to work with for joining are waypoint labels, we get duplicate results when a waypoint label shows up > once in a route file (i.e. DUPLICATE_LABEL) or when a given waypoint route+label combo shows up > once in the DC entry list.

**So, that's no good.**
Plus, the query gets up to ~1.9s by the time we're querying the FP table.

If this feature would be useful, we could add lat, lon, and maybe zoom to the datacheckErrors table at siteupdate time.

**Comment by michihdeu** [comment]
datacheck.php loding time is already very high. I agree that the required data should be generated during the siteupdate

OTOH, I agree that the feature would help to identify FPs but when there is a real error to be fixed, one needs to load the wpt file into wpt editor. It makes no sense at all to check DL errors in HB. I think that DL errors don't need a HB link on datacheck.php.

**Comment by yakra** [comment]
> OTOH, I agree that the feature would help to identify FPs but when there is a real error to be fixed, one needs to load the wpt file into wpt editor.

Yes.

> It makes no sense at all to check DL errors in HB. I think that DL errors don't need a HB link on datacheck.php.

* If the DLs are hidden points, the HB certainly won't help here.
* If they're visible, we can still click on the labels in the table to pan to the points and see what the road names are, or how the junctions & routes are laid out, and see what we need to fix and how.

So I think the HB link would still function (*some of the time*, in the case of DLs) as a quick-n-easy way to inspect what what we need to fix before fixing it.
Even if, for a `datacheck_always_error`, we *do* need to load the file into wptedit, I see no harm in keeping the datacheck.php code simple and leaving the HB link in place. ...It'll avoid adding more loading time to datacheck.php, at least. :smiley:

**Comment by michihdeu** [comment]
It's up to you. I just wanted to find a solution for your DL issue. I still think that it makes no sense. The HB link only makes sense when one checks for FPs.

To be honest, when one can easily check what's to be changed - WITHOUT WPT EDITOR - one might really just change the wpt file without loading it into the wpt editor. This way new errors might happen... On editing just the wpt file. format gets more easily be broken ending up in issues witht the site update et cetera....

But again, up to you.

**Comment by yakra** [comment]
> It's up to you. I just wanted to find a solution for your DL issue.

Aah, gotcha. It's not just DCs though, also
> when a given waypoint route+label combo shows up > once in the DC entry list.

...such as [NB772 & NB845](http://travelmapping.net/devel/datacheck.php?rg=NB&showmarked=on).

In any case, 
> To be honest, when one can easily check what's to be changed - WITHOUT WPT EDITOR - one might really just change the wpt file without loading it into the wpt editor. This way new errors might happen... On editing just the wpt file. format gets more easily be broken ending up in issues witht the site update et cetera....

You have a point here. It's pretty common to see errors creeping into datacheck (e.g. `LONG_UNDERSCORE`, `SHARP_ANGLE`, `DUPLICATE_LABEL`...) that could easily be prevented by loading the route into wptedit and fixing what's reported there before committing the file.
One could argue that any feature that enables contributors to go straight to a text editor and bypass wptedit enables sloppy editing...

**Comment by yakra** [comment]
2 other possibilities avoid having to add anything new to the DB:
* Have PHP determine if `label2` exists, and make another tiny query to look up its coords. Else, query `label1`. These individual queries take 0.00s on lab2. Even `select * from datacheckErrors;` takes up only 0.03s, but in the event that repeating the process 14912 times starts to add up and makes datacheck.php take too long to load, we can save calculating the coords until someone actually wants to follow the link, and...
* Handle it purely on the PHP/Javascript side. This avoids any additional SQL queries. A new `at=` param in the HB could take its argument in the form of a waypoint label, then search for its coords and initialize the map there. (If the label doesn't exist, then zoom/pan to fit as per normal.)

**Comment by yakra** [comment]
Option #1 implemented on lab2

**Comment by michihdeu** [comment]
> Option 1 implemented on lab2

Like it 👍 

Is it possible:
- to opened the link in a new TAB (like it's done athttp://205.209.84.174/hb/)
- to opened the popup window of the relevant wp?

VD errors center the HB map at the 2nd wp right now.

**Comment by yakra** [comment]
> to opened the link in a new TAB

I'd rather not do that, and give the user the option. Shift+click is easy enough. :)

> to opened the popup window of the relevant wp?

Possible, yes. I don't know how, though it should be easy to learn. What I *do* know is that it would involve much greater modifications to the code, and changes to the HB itself. So, more of an Option 2 than an Option 1. Option 1 was easily done with just an extra small SQL query added to the datacheck page, using the existing lat/lon/zoom parameters added to the HB a while back.
I'll just hand-wave it away with a "the waypoint is right there, ready to be clicked on" :)

> VD errors center the HB map at the 2nd wp right now.

That was my intent. Sort of like how in wptedit, the error is flagged on the second waypoint in the segment. Figure the user can just zoom out until the other point is visible (mouse wheel is ideal).
Thinking about it some more...
* Panning directly to midway between the two listed visible points bookending the segment is easily doable...
  - LONG_SEGMENT would work the same way; makes sense
  - The average of two DUPLICATE_COORDS = the right coords! :)
* OTOH, what if there are hidden points between the two visible endpoints?
  - We'd need a check separating out how DUPLICATE_COORDS cases are handled. (Don't wanna just include all the points along a beltway & just pan directly to the middle...)
  - Checking all our intermediate shaping points to find max/min lat/lon I think might start to make the whole operation a bit costly and affect loading time. There are *a lot* of VISIBLE_DISTANCE errors...
* What about zoom? If we want to zoom to fit both points in the map pane...
  - We could have leaflet do it, which would mean changes to hb/index.php. So this is starting to look more like an "Option 2" scenario again.
  - Maybe use some HTML wizardry to estimate what the eventual map size would be once the HB was opened, but...
    - This is a bit ahead of where I am on the learning curve
    - No guarantee we'd get 100% consistent results across different platforms
    - Computational complexity and loading time

So, I don't really want to pursue finding an optimal zoom level.
I could still *maaaybe* get talked into panning directly to the center of a VISIBLE_DISTANCE segment, but then, we'd wind up with stuff like [this](http://192.168.2.7/hb/?units=miles&u=yakra&r=me.i095&lat=45.115577&lon=-68.68977&zoom=17). I run Firefox maximized on a 1680x1050 display; the actual map pane is 1405x804. The route trace is not visible at all in the map pane until I zoom out once. I don't see the waypoints until I zoom out a total of 5 times.
At least just by panning to the 2nd point, one of the segment is guaranteed to be within view. The user can click on the point at the center and quickly get their bearings. Yes, I think I like this. It may not be *perfect*, but it's good enough. :)

**Comment by michihdeu** [comment]
Fine to me. I just wanted to give feedback...

VD was not a request but a simple statement. Kinda question "Was it intented or did you miss it" (was intent) or a hint for anyone else who might check it out.... 😄 

> > to open the link in a new TAB
> I'd rather not do that, and give the user the option. Shift+click is easy enough. :)

shift + click opens a new window, not TAB

**Comment by yakra** [comment]
Oops, I meant Ctrl+click

**Comment by michihdeu** [comment]
😮 I also tried ctrl but it didn't work. 2..3 attempts, nothing. I also googled for 'firefox shortcut tab'.
I tried it again now and.... works 🤐

**Comment by yakra** [comment]
Ack, weird
