### ISSUE TITLE
A NAME

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#369]
`<a name>` tags before each individual rule followed by a link to itself will provide handy click-n-copy citations to paste into the forum.

**Comment by yakra** [comment]
Applied to wayptlabels.php, live on lab2

**Comment by michihdeu** [comment]
The icon looks funny - quite prominent - but I like it 😃 

http://205.209.84.174/devel/manual/wayptlabels.php#distanttown
http://205.209.84.174/devel/manual/wayptlabels.php#noprepositions
http://205.209.84.174/devel/manual/wayptlabels.php#loopsuffix

**Comment by yakra** [comment]
The icon isn't done with an `<img src=...>` tag, but is a unicode charachter &#x1f517; (`&#x1f517`) which will display differently on different systems.

**Comment by michihdeu** [comment]
Not yet implemented for:
- hwydata.php
- includepts.php
- maintenance.php
- syshwylist.php

**Comment by michihdeu** [comment]
maintenance.php addressed with https://github.com/TravelMapping/Web/pull/417 😄

**Comment by michihdeu** [comment]
All locally done except of
- syshwylist.php

**Comment by michihdeu** [comment]
Addressed with https://github.com/TravelMapping/Web/pull/418

**Issue can be closed**
