### ISSUE TITLE
Links missing

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#37]
The current main page or any other page have no links to:

- [Highway data updates](http://tm.teresco.org/devel/updates.php)
- [Highway data errors](http://tm.teresco.org/devel/datacheck.php)
- http://tm.teresco.org/logs/
- http://tm.teresco.org/devlogs

**Comment by michihdeu** [comment]
A link to the forum should be added too:
http://tm.teresco.org/forum

**Comment by jteresco** [comment]
I think I have all of the old links plus the forum link now on the main index.  Not pretty, but at least they're there.
