### ISSUE TITLE
hb/index.php opening comments

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#371]
https://github.com/TravelMapping/Web/blob/77a161993ad4b3b43e0900e0067fc83ba6d78a7d/hb/index.php#L4-L13

I didn't update the opening comments along with #318.
Should do so, for good housekeeping & documentation.
I'm unsure about what that last line is & how to parse/format it though.
`([r [u]] [rg | sys]) `
I only *sorta* get it.
Used to look like this: https://github.com/TravelMapping/Web/commit/023cd47b8129678e5cf627ca175b211a0f8ef276#diff-c440b37159b0aa80563b7d8165cf15d4L38-R37
Would I want to change it to `([r [u] [lat lon zoom]] [rg | sys])`?
Ping @jteresco, @Thing342

**Comment by jteresco** [comment]
As I interpret it, r is optional, and if specified, it is followed by an optional u.

**Comment by yakra** [comment]
Looks like I may have it right, then.

Is `([r [u]] [rg | sys])` equivalent to `([r [u]] [rg] [sys]) `?

**Comment by jteresco** [comment]
If rg and sys are mutually exclusive, I'd keep them as an "or"  with the '|'.

So for your lat/lon/zoom, it's all three or nothing at all, correct?

**Comment by yakra** [comment]
> If rg and sys are mutually exclusive,

[They're not.](http://travelmapping.net/hb/?units=miles&u=yakra&rg=ME&sys=usanh)

> I'd keep them as an "or" with the '|'.

Being most used to C++, I'd interpret '|' as meaning a simple **or** as opposed to **xor**.
Which is it here?

> So for your lat/lon/zoom, it's all three or nothing at all, correct?

Correct.

**Comment by jteresco** [comment]
Intended as "or" not "xor"

**Comment by yakra** [comment]
Hm. For consistency with the way the other args are shown,. should it be `([r [u]] [rg] [sys])`, then?
Update it to `([r [u]] [rg] [sys])`?

**Comment by jteresco** [comment]
Yes, I think so.

**Comment by yakra** [comment]
Too quick on the copy-paste.
I *meant* to say:
> Update it to `([r [u] [lat lon zoom]] [rg] [sys])`?

**Comment by yakra** [comment]
```
<!--
 ***
 * Highway Browser Main Page.
 * If a root is supplied, a map will show that root's path along with its waypoints.
 * Otherwise, it will show a list of routes that the user can select from, with filters by region and system availible.
 * If all three of lat, lon, and zoom are provided, the map will initialize to those coordinates and zoom level.
 * Otherwise, the map will pan and zoom to fit the entire route at the center.
 * URL Params:
 *  r - root of route to view waypoints for. When set, the page will display a map with the route params. (required for displaying map)
 *  u - user to display highlighting for on map (optional)
 *  lat - initial latitude at center of map
 *  lon - initial longitude at center of map
 *  zoom - initial zoom level of map
 *  rg - region to filter for on the highway browser list (optional)
 *  sys - system to filter for on the highway browser list (optional)
 *  ([r [u] [lat lon zoom]] [rg] [sys])
 ***
 -->
```
Look good?

**Comment by yakra** [comment]
```
<!--
 ***
 * Highway Browser Main Page.
 * If a root is supplied, a map will show that root's path along with its waypoints.
 * Otherwise, it will show a list of routes that the user can select from, with filters by region and system availible.
 * If all three of lat, lon, and zoom are provided, the map will initialize to those coordinates and zoom level.
 * Otherwise, the map will pan and zoom to fit the entire route at the center.
 * URL Params:
 *  r - root of route to view waypoints for. When set, the page will display a map with the route params. (required for displaying map)
 *  u - user to display highlighting for on map (optional)
 *  lat - initial latitude at center of map
 *  lon - initial longitude at center of map
 *  zoom - initial zoom level of map
 *  rg - region to filter for on the highway browser list (optional)
 *  sys - system to filter for on the highway browser list (optional)
 *  ([r [u] [lat lon zoom]] [rg] [sys])
 ***
 -->
```
Look good?

**Comment by jteresco** [comment]
Yes, I think so.  If you have r, you can optionally have u and/or all three of lat/lon/zoom, can always have rg or not, can always have sys or not.
