### ISSUE TITLE
HB: Show system name

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#379]
The system name (full name + abbrev.) of the route loaded should be displayed.

E.g.: http://travelmapping.net/hb/?r=eng.quetun
NEW: gbna
NEW: Great Britain A Roads

It's _important_ since we can load routes from mapview now and we can also jump from one route to another. When we started TM, it was only possible to load routes from anywhere where the system name (abbrev.) was visible

**Comment by yakra** [comment]
ISTR CHM would show the system name as part of the page's title.

**Comment by jteresco** [comment]
See tmtest for an initial implementation.  Also added a message for preview and devel systems.

**Comment by michihdeu** [comment]
I clicked through and it looked fine. Then, I was here: http://tmtest.teresco.org/hb/?u=michih&r=deuni.indstrmit

route pic
route name
system name
route name

**Comment by michihdeu** [comment]
I like the preview message http://tmtest.teresco.org/hb/?r=deuhe.l3224 and the devel message: http://tmtest.teresco.org/hb/index.php?r=ago.tah3 The devel message might be in red.

**Comment by jteresco** [comment]
I agree it might be better to have the system name above the route shield.  Moving things around and adding some title text and links.  What do you think?

**Comment by michihdeu** [comment]
I like it, also the link to the overview. Great!

**Comment by jteresco** [comment]
Thanks, I'm going to put it on the main site now.

**Comment by michihdeu** [comment]
Thanks. Closing!
