### ISSUE TITLE
HB: Center map at wp (for hwy data issue reports)

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#385]
With #179 we have lat/lon/zoom in url now. The url is only updated when changing to another route (and removed with 'Zoom to fit').

When we click through the routes and find hwy data issues, it's nice to copy the HB link to the forum. When another person opens the link, a wp is centered and one might think that that's the relevant wp. But it isn't, see [recent report](http://forum.travelmapping.net/index.php?topic=3401). I must admit that @yakra has the wrong route. It should be DN1 or E60 centered at DN19 wp.

Nevertheless, when I wanna center the map so that the hwy data manager directly seen the wp I'm talking about, I need to center the wp in HB. It's possible by clicking on the wp line of the wp table to the left. However, the url is not updated! And that's the request.

**Comment by yakra** [comment]
I've had thoughts about adding a "link here" button...

**Comment by yakra** [comment]
For Zoom to Fit, maybe `&#x26F6` ?
# ⛶

Best I've seen so far; Unicode is a lot less helpful than I'd like here...

**Comment by michihdeu** [comment]
fine to me

**Comment by yakra** [comment]
https://leafletjs.com/reference-1.6.0.html#map-zoomlevelschange

**Comment by jteresco** [comment]
Here's an idea that's not thought through yet.  Add code to popups that appear when a waypoint is clicked that is a "permanent link" to this route centered at the given waypoint, using the current zoom level.

https://github.com/TravelMapping/Web/blob/c21e89573a42e2eb19835103f240e13c6cb63e4a/lib/tmjsfuncs.js#L945-L949

**Comment by yakra** [comment]
I like it, but think a "link here" that would work anywhere would be more versatile.
Should be doable, I think; I may have a look into it soon.

**Comment by yakra** [comment]
Can use CSS tricks to overlay a 🔍 on top of a ⛶

**Comment by jteresco** [comment]
"Link Here" button is now on tmtest's showroute.php.  @yakra @michihdeu can you see if this functionality meets you needs related to this issue?

In any case, I think we have a few separate Issues discussed here.  If there's anything that's not addressed by the Link Here button maybe new Issues should be opened?

**Comment by michihdeu** [comment]
Works, thanks 😄
