### ISSUE TITLE
datacheck.php: HB links when label lookup fails

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#387]
#383 introduced some undesired behavior for MALFORMED_URL, MALFORMED_LAT and MALFORMED_LON cases, because these points [don't get added to the DB](https://github.com/TravelMapping/DataProcessing/issues/57#issuecomment-450404359).

The resulting link will be something like http://travelmapping.net/hb/?r=me.i295&lat=&lon=&zoom=17, which initializes the HB view to (0°, 0°) near the Gulf of Guinea.

**Comment by yakra** [comment]
`rou.dj104e;+@;;;LABEL_INVALID_CHAR;;` references an AltLabel. AltLabels don't get added to the DB. Lookup by label similarly fails.

However *these* are handled, per the case in the OP, we *will* be attempting to look up labels that aren't in the DB, and some form of graceful degradation is in order.
* If our query returns an empty array, don't include the lat, lon & zoom parameters in the link.

**Comment by yakra** [comment]
MALFORMED_LAT, once implemented, will also be affected.
https://github.com/TravelMapping/DataProcessing/issues/302

**Comment by yakra** [comment]
https://github.com/TravelMapping/DataProcessing/issues/62
https://github.com/TravelMapping/DataProcessing/issues/97

**Comment by michihdeu** [comment]
Not sure if it is the same or should be a new issue.

https://travelmapping.net/devel/datacheck.php?show=DUPLICATE_LABEL

If a DL error is a visible wp, it works.
**If a DL error is a hidden wp, the HB link fails**, e.g. for MS US51 X01 it has **no lat/lon**: https://travelmapping.net/hb/showroute.php?r=ms.us051&lat=&lon=&zoom=17

**Comment by yakra** [comment]
`X01` is what's shown on the datacheck page. `+X01` is what's stored in the database to be looked up.
Good catch!

This issue is a good enough place for that. It will be something to think about as I pursue a solution.

**Comment by yakra** [comment]
related:
[all proposed CSV datachecks](https://github.com/TravelMapping/DataProcessing/issues?q=is%3Aopen+label%3ACSVs+label%3Adatacheck)

**Comment by yakra** [comment]
If we keep this issue within the scope of keeping HB links valid when label lookup fails, then #623 closes this.
Any discussion on the merits of linking to elsewhere, such as [wptedit](https://github.com/TravelMapping/Web/issues/372) or [CSV files](https://github.com/TravelMapping/DataProcessing/issues?q=is%3Aopen+label%3ACSVs+label%3Adatacheck) on GitHub depending on the type of error, can happen in another issue.

@michihdeu [wrote](https://github.com/TravelMapping/Web/issues/387#issuecomment-753281307):
> https://travelmapping.net/devel/datacheck.php?show=DUPLICATE_LABEL
>
> If a DL error is a visible wp, it works.
> **If a DL error is a hidden wp, the HB link fails**, e.g. for MS US51 `X01` has **no lat/lon**: https://travelmapping.net/hb/showroute.php?r=ms.us051&lat=&lon=&zoom=17

In the immediate term, #623 does clear this up. Label lookup still fails, but the HB link will no longer fail because of it. We'll get a link to the route as a whole, keeping in line with the purpose of this issue.

We could restore a link to a visible, index-able point by making changes on the DataProcessing side...
`DUPLICATE_LABEL` gets flagged 4 different ways:
**1.** a new primary label already exists in `alt_label_hash`
**2.** a new primary label already exists in `pri_label_hash`
**3.** a new alternate label already exists in `pri_label_hash`
**4.** a new alternate label already exists in `alt_label_hash`
In the first 3 cases, we can just flag the primary label, and life goes on; this will work even without #623. For scenario **4** though, we'd need changes to both DataProcessing and Web to get something more specific than the basic HB link we've had all along. What that link might end up being and how to accomplish it, is another discussion for another issue.

MALFORMED_LAT also falls under the "link to something other than the HB" umbrella.
