### ISSUE TITLE
Manual: System status

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#389]
There is a description on the start page and it's indicated here: http://tmtest.teresco.org/devel/manual/maintenance.php

It should be linked from the [preview + devel message in HB](https://github.com/TravelMapping/Web/issues/379#issuecomment-569571454) and from the start page description to make users and developers more aware of it.

The system description itself might be enhanced a little bit
- Note about the green-yellow-red colors in HB and user stats
- Note why there are active & active+preview user stats

**Comment by jteresco** [comment]
Are you thinking more detail on the maintenance.php page, or a new page?

**Comment by michihdeu** [comment]
I think that a new page would be better. I think that maintenance.php is more for developer, but I just wanna show the system status for _normal user_

**Comment by michihdeu** [comment]
An extended description for _normal users_ (warning for preview + devel systems) is now availabel in the HB (tooltip): https://github.com/TravelMapping/Web/blob/master/hb/index.php (this text should be copied one day so that it's identical)

**Comment by michihdeu** [comment]
Thie rest is now addressed with https://github.com/TravelMapping/Web/pull/411
The system description is on _sysdef.php_ ([temporary link](https://github.com/TravelMapping/Web/blob/master/devel_new/manual/sysdef.php))
