### ISSUE TITLE
wpt editor: Automated loading of unused alt labels

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#395]
Once we can load the wpt file from Git, see #372 the next step would be loading the unused alt labels for this route automatically.

http://travelmapping.net/logs/unusedaltlabels.log

**Comment by yakra** [comment]
We can load pointsinuse (#391, https://github.com/TravelMapping/Web/issues/372#issuecomment-557870268), but not unused alt labels. These aren't actually loaded into anything in wptedit, or used in any way.
We could *produce* a list, sure. As long as the pointsinuse box is populated, we have all the info we need. This wouldn't even be contingent on loading the wpt file from GitHub.

But where to store it? In a way, we have this info at hand already:
AltLabels are in the boxes in the WP table at the left that are more than a single row tall. Unused ones are the ones that aren't red. This should be enough for somebody editing the route IMO; do we really need the info displayed in an alternate format?

**Comment by michihdeu** [comment]
> Unused ones are the ones that aren't red. This should be enough for somebody editing the route IMO

I agree! Closing!
