### ISSUE TITLE
Manual: Revision of "System Highway Lists" or "How to create csv files"

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#398]
A general check and revision of http://travelmapping.net/devel/manual/syshwylist.php

There is a discussion on the forum about routes of the same Route+Banner combination, which route should get city abbreviation: http://forum.travelmapping.net/index.php?topic=2038.msg17365#msg17365
That should be made clear, e.g. removing "significantly"?

Out of scope:
_Rework this section, as connected route CSV files are no longer generated by script._ see #344

**Comment by yakra** [comment]
Under `Chopped Routes File (e.g., usai.csv) format:`, we need to clarify which fields can only accept standard Latin and not multi-byte international characters.
http://forum.travelmapping.net/index.php?topic=3147.msg18099#msg18099

**Comment by michihdeu** [comment]
I think that we will need poll(s) here to agree with the required changes. We will see...

**Comment by michihdeu** [comment]
- [ ] Add links to [wpt file description](https://travelmapping.net/devel/manual/hwydata.php#filename) for [chopped route csv description](https://travelmapping.net/devel/manual/syshwylist.php#columns) - _reduce text to avoid redundant description?_
- [ ] Add links to chopped route csv for [connected route csv description](https://travelmapping.net/devel/manual/syshwylist.php#conncolumns) - _reduce text to avoid redundant description?_

**Comment by michihdeu** [comment]
- [ ] [For like route numbers](https://travelmapping.net/devel/manual/syshwylist.php#rsuffix) (imported from CHM): Is it _correct_ English or shouldn't it be `For identical route numbers`?

**Comment by michihdeu** [comment]
- [ ] [Concurrencies within which not all concurrent routes are signed](https://travelmapping.net/devel/manual/syshwylist.php#concurrencies) describes how to split routes. This should be moved. Likely to [Highway Data (.wpt) Files](https://travelmapping.net/devel/manual/hwydata.php) where we already describe that routes must be [split at borders](https://travelmapping.net/devel/manual/hwydata.php#fileborder). Likely a new paragraph for this and another one for the file name.

**Comment by michihdeu** [comment]
- [ ] Do we still need the [Example system: Takoma National H Routes (tach)](https://travelmapping.net/devel/manual/syshwylist.php#examplesystem)?

**Comment by michihdeu** [comment]
https://github.com/TravelMapping/Web/pull/535
