### ISSUE TITLE
datacheck: troubleshooting info for each datacheck type 

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#403]
https://github.com/yakra/Web/issues/13 isn't very visible, so moving here instead.

> Create a new datachecktypes.php or something, listing all the types, with an `<a name=` for each.
Provide a description of what each error is and how to fix it.
What flags this as an error? When, if ever, is it a false positive? How can it be fixed; what ways?
Link back to the main datacheck page
>
> On datacheck.php, Link to the appropriate section from the `Error` column in the tables, using a `#`. So like, [VISIBLE_HIDDEN_COLOC](http://travelmapping.net/devel/datachecktypes.php#VISIBLE_HIDDEN_COLOC)

OTOH, tooltips or a dialog box may be more user-friendly.

Related: https://github.com/TravelMapping/Web/issues/374

**Comment by michihdeu** [comment]
The manual has the error description now (not yet final): https://github.com/TravelMapping/Web/issues/388

The only open issues I see are
* Link from datacheck.php to the correct manual line
* Link from HB table to the correct manual line

_I'll remove the documentation label and add the others._

**Comment by yakra** [comment]
> The manual has the error description now (not yet final): https://github.com/TravelMapping/Web/issues/388
> 
> The only open issues I see are
> * Link from datacheck.php to the correct manual line

Yes. @michihdeu, with your recent enhancements to the manual, this is the best solution.
* [ ] I'll make the change once syserr.php "goes live" and is in `devel/` rather than `devel_new`.

> * Link from wpt editor table to the correct manual line

Hmm... The wptedit table works by clicking (where applicable) on a cell overall.
A given waypoint can have multiple errors listed.
Having traditional links within the table cell may be inconsistent & awkward, but should certainly be possible. Don't know if there would be any complication with the existing \<span\> elements & tooltips.

However, I was already thinking about [clicking on the table cell to produce a dialog box listing FP entries](https://github.com/TravelMapping/Web/issues/375).
Perhaps, from here, we could have have a **`?`** button next to each  FP entry, linking to the manual.

**Comment by michihdeu** [comment]
> elements & tooltips.
> However, I was already thinking about clicking on the table cell to produce a dialog box listing FP entries.
> Perhaps, from here, we could have have a ? button next to each FP entry, linking to the manual.

You wrote anywhere that you wanna get rid off the tooltips. Well, get rid of the (now redundant) text in the php or js file.
The `?` button in the FP box sounds good to me. However, it must even be opened if FPs would not be allowed*1. I don't know whether it would be possible to provide the manual link in the tooltip?

*1 The _filter_ to provide FP entries is in `datacheck.php` right now. If we add this to `wptedit` it would also be redundant. Maybe using a library function like `wptfunctions.js` for both?

**Comment by michihdeu** [comment]
btw: the link would be quite simple. It's just `/devel_new/manual/syserr.php#` + actual error code, e.g. https://travelmapping.net/devel_new/manual/syserr.php#BAD_ANGLE or https://travelmapping.net/devel_new/manual/syserr.php#BUS_WITH_I

quite generic...

**Comment by yakra** [comment]
> You wrote anywhere that you wanna get rid off the tooltips.

You mean when I said [this](https://github.com/TravelMapping/Web/issues/374#issuecomment-625525247)? A passing thought, not one I'm super married to. They don't do much harm, can provide a bit more info... While getting started making the changes I've been working on for #374, it's been easier to just roll with the way the page is already set up, so I've been adding new \<span\>s & tooltips for new datachecks, rather than attempt to remove them altogether.

> Well, get rid of the (now redundant) text in the php or js file.

Unsure what you mean here. What's the now-redundant text you're referring to?
Oh wait -- the tooltip info? (Duh...) I think it can provide a little more detailed info if we need it.
Could also potentially remove them, as more of a long-term task.

Might ask in the forum about that...

> The `?` button in the FP box sounds good to me. **However, it must even be opened if FPs would not be allowed*1**.

I know your comments before on other issues have favored getting to the important information with as few clicks as practicable. :)

> I don't know whether it would be possible to provide the manual link in the tooltip?

I don't know either, but there are simpler ways...
How about we decide that traditional links within the **Err.?** table cell may be a little inconsistent, but they don't have to be awkward? We could have a small **`?`** icon next to the datacheck codes to link to the manual. Clicking on the codes themselves could open the [dialog](https://github.com/TravelMapping/Web/issues/375).

> *1 The _filter_ to provide FP entries is in `datacheck.php` right now. If we add this to `wptedit` it would also be redundant. Maybe using a library function like `wptfunctions.js` for both?

The filter in datacheck.php is written in PHP, as it constructs the HTML tables.

Other than
```PHP
<?php
  require $_SERVER['DOCUMENT_ROOT']."/lib/tmphpfuncs.php";
  tm_common_js();  
  ?>
```
wptedit/index.php is straight-up Javascript.
So we end up doing the task 2 slightly different ways, in 2 different languages.
Not a bit deal at all though. It's short & simple code as far as these things go, and this little bit of duplication won't be detrimental.

**Comment by michihdeu** [comment]
Agree with all but:

>  I think it can provide a little more detailed info if we need it.

Disagree! There should be **one** description of a data error. The manual and the tooltip should provide the very same information. since not all errors can be detected by wpt editor and since the wpt editor only indicates the actual errors with the loaded wpt file, the manual should be the location where the errors and their elimination help is described. And from wpt editor, I would just link to it. If we would improve one text one day, we must think of updating both and I'm quite sure that this would not be done anywhere down the road and when there is one outdated text, there will be more and more outdated texts soon. I'd like to avoid this from the beginning!

**Comment by yakra** [comment]
Fair enough; I'm convinced.
* [ ] After my PR for #374, I'll look into eliminating the tooltips.
* [ ] Links can come later, when syserr.php is in `devel/`.

**Comment by michihdeu** [comment]
> Links can come later, when syserr.php is in devel/.

I think it will be there by June 28
