### ISSUE TITLE
NP/PP/SP abbreviations

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#404]
may be more useful at wayptlabels.php#nearbytown than at wayptlabels.php#park

http://forum.travelmapping.net/index.php?topic=3245.msg18019#msg18019

**Comment by michihdeu** [comment]
@yakra I don't get what should be changed ❓  The abbreviations are described:

http://travelmapping.net/devel/manual/wayptlabels.php#park
`Use NP for national park, PP for provincial park, SP for state park.`

Maybe just adding a link from http://travelmapping.net/devel/manual/wayptlabels.php#nearbytown to http://travelmapping.net/devel/manual/wayptlabels.php#park ❓ 

And/or split the point

`* Truncated, nearby town name - for a town immediately served by the unnamed cross road. If a localized national park or tourist attraction is immediately served by the cross road, a truncated version of its name could also suffice. `

into two points:

`* Truncated, nearby town name - for a town immediately served by the unnamed cross road.`
`* Truncated version of a localized national park or tourist attraction if it is immediately served by the cross road.`

❓ 

If I hear nothing, I'll suggest this change on the forum and wait for the poll result.

**Comment by michihdeu** [comment]
Poll: https://forum.travelmapping.net/index.php?topic=3687

**Comment by michihdeu** [comment]
https://travelmapping.net/devel/manual/wayptlabels.php
