### ISSUE TITLE
Tutorial for mapview url options

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#41]
Maybe there's already a tutorial on any forum but I think there should be a tuturial on the web page which options are possible, e.g.

u = user
r = route
rte = route
rg = region
sys = system
colors (with tier option)
db = database
...

There should be an example for each option.
Some options can only be add manually at the moment. If there's a way to get an automatically created link, it should be described how to get it.

Quick example (w/o links or screen shots): How to check which segments of a specific route has been traveled? Click on Traveler States, enter your user name, click on the desired country line of the region table. The traveled segments are displayed pink, the not yet traveled segements are displayed grey. The clinched mileaged is display on the top. You can zoom into the map and choose a different map layer.

**Comment by Thing342** [comment]
With the creation of GUI tools for mapview, this has largely been addressed. The other params are not meant for regular users, so they should probably go on a wiki page somewhere.
