### ISSUE TITLE
Manual: How to create a user list file

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#413]
http://forum.travelmapping.net/index.php?topic=5 should make it into the manual on the site

**Comment by jteresco** [comment]
I agree that this belongs on the site, where it would be kept up-to-date, with a link to the page placed in that topic on the forum.

**Comment by michihdeu** [comment]
Should be added to `contribute.php`

**Comment by michihdeu** [comment]
Initial draft with https://github.com/TravelMapping/Web/pull/417 but not yet complete.

**Comment by michihdeu** [comment]
Adding the examples completes this: https://github.com/TravelMapping/Web/pull/420
