### ISSUE TITLE
Manual: How data is organized on Github

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#414]
https://github.com/TravelMapping/HighwayData/blob/master/README.md should make it into the manual on the site.

Prio low.

**Comment by jteresco** [comment]
This one I don't agree with.  A link from the manual to the info on GitHub should be more than enough.  We should not maintain redundant info, and if it's in one place, the repository is what makes sense to me.

**Comment by michihdeu** [comment]
yes, I was not sure. I want to have everything in one place. But the Github structure........ should be on Github. A link from the manual to Github should be enough. Period. 👍
