### ISSUE TITLE
Feature: User selection

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#42]
Note from vdeane: http://tm.teresco.org/forum/index.php?topic=43.0

> it might be a good idea to replace the null user stats page with an index of all the users

**Comment by Thing342** [comment]
Implementation notes: have pages requiring usernames redirect to stat.php if a user is not selected

**Comment by michihdeu** [comment]
If one selects an user from [stats](http://tm.teresco.org/stat.php), for instance [michih](http://tm.teresco.org/user/?u=michih), it's possible to open the [highway browser for regions](http://tm.teresco.org/hb/?rg=DEU) or systems. Unfortunately, there's no user selection (which is not required at first glance) and it's not specified in the link address. If one opens a [specific route](http://tm.teresco.org/hb/index.php?r=deu.a001], **no user is preselected**. One has to [select the user manually](http://tm.teresco.org/hb/index.php?u=michih&r=deu.a001) for each route. I've recently had to open dozens to add new routes traveled!

**Comment by Thing342** [comment]
Added in #96
