### ISSUE TITLE
view entire ConnectedRoutes in HB

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#421]
This will be key once [Multi-region list file entries](https://github.com/TravelMapping/DataProcessing/issues/58) are implemented.
Semi-related: #101
http://forum.travelmapping.net/index.php?topic=3604.msg18493#msg18493

**Comment by michihdeu** [comment]
Is it also related to https://github.com/TravelMapping/Web/issues/192 where we want to jump manually to the route in the next region?
And how to deal with https://github.com/TravelMapping/Web/issues/199 the interrupted connected routes?

**Comment by yakra** [comment]
@michihdeu [wrote](https://github.com/TravelMapping/DataProcessing/issues/58#issuecomment-320461105):
> _*I think about a "one click" HB feature to expand the loaded route to all connected routes..._

**Comment by yakra** [comment]
> Is it also related to https://github.com/TravelMapping/Web/issues/192 where we want to jump manually to the route in the next region?

No. That's for links to the prev/next chopped route within a connected route.
The idea for this issue is to display an entire connected route in the HB at once, to facilitate [Multi-region list file entries](https://github.com/TravelMapping/DataProcessing/issues/58).
What I'm thinking is that
http://travelmapping.net/hb/?cr=me.me113
http://travelmapping.net/hb/?cr=nh.me113con
http://travelmapping.net/hb/?cr=me.me113fry
http://travelmapping.net/hb/?cr=nh.me113cha
http://travelmapping.net/hb/?cr=me.me113whi
would all end up displaying the same thing, the entire ME113 connected route.

> And how to deal with https://github.com/TravelMapping/Web/issues/199 the interrupted connected routes?

I'm still not 100% clear on what you mean by an "interrupted connected routes", but AIUI this is unrelated.

**Comment by michihdeu** [comment]
> I'm still not 100% clear on what you mean by "interrupted connected routes", but AIUI this is unrelated.

If memory serves, Jim called it this way.

Connected routes = one line in the _con.csv file
Interrupted connected routes = more than one line in the _con.csv file

**Comment by michihdeu** [comment]
_Just thinking out loud.... Why do we have more than one line in _con.csv files at all? Why don't we merge the [ME 4A lines](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/usame_con.csv#L4) into one? Isn't that exactly what we want?_

**Comment by yakra** [comment]
Because the routes are not connected. They are separate routes.

**Comment by michihdeu** [comment]
> Because the routes are not connected. They are separate routes.

ok, if that's important, fine.

And this is what we call _Interrupted connected routes_

**Comment by yakra** [comment]
Thoughts:
* Don't include a .list name above the waypoint table, because a connected route can have more than one .list name.
* Instead, include in waypoints table and waypoint popups along with the label. This way each waypoint will have the text string that uniquely identifies it within a connected route.

**Comment by michihdeu** [comment]
seconded!

**Comment by yakra** [comment]
> And this is what we call Interrupted connected routes

"We" is the first person plural. Indicating either the speaker and the listener, or the speaker and a third party. This listener sure doesn't call anything Int\*rr\*pt\*d c\*nn*ct\*d r\*\*t\*s, and upon searching the forum and GitHub, I have not seen anybody else use the phrase.

I don't see the idea as being useful.

> _Just thinking out loud.... Why do we have more than one line in _con.csv files at all? Why don't we merge the [ME 4A lines](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/usame_con.csv#L4) into one? Isn't that exactly what we want?_

This comment exhibits a misunderstanding of what a ConnectedRoute is.
If this were what we did, it would render the _con.csv file as nothing more than a place all the ME4As, all the same Route+Banner designated routes, get grouped together. And what then? This would leave the _con.csv files serving no useful purpose, as at that point they would not contain any more information then could be gained by processing the regular chopped routes CSV file. We can see that there are bunch of ME4As or US1Alts in there. OK. We can query the DB for sets of routes (whether of the chopped *or* connected variety as needed) that have the same Route+Banner designation, and we're grand. IIUC, this is all this concept seems to be about. Conflating it with the idea of ConnectedRoutes only muddies the waters, and makes the term not descriptive of what it's describing.

**Comment by jteresco** [comment]
A few dozen commits currently only on the "hb" branch implement this functionality.
