### ISSUE TITLE
HB table headline line break

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#43]
"Route Name" column has a line break if the names are short, for instance here: http://tm.teresco.org/devel/hb.php?sys=kaza. Checked with FF44 and IE11.

**Comment by michihdeu** [comment]
Screen shot: http://tm.teresco.org/forum/index.php?topic=92.0.

**Comment by jteresco** [comment]
Fixed on tmtest server, soon to be on primary server.  Closing.
