### ISSUE TITLE
Scrollable Mapview: Display city names like old Mapview in route table?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#437]

**Comment by michihdeu** [comment]
Since you added the _question_ label.... I don't use the table on mapview but I think it makes no sense to omit the city name. There would be two or more identical "Routes" displayed - how should one distinuish them?

**Comment by jteresco** [comment]
As I currently have it, it shows by .list name, so the banner and abbrev are included to distinguish.  The advantage of leaving the full names out is that everything fits on single lines, and I can probably make the table even a bit narrower.

**Comment by michihdeu** [comment]
Can you provide a link? The direct navigation to mapview on tmtest didn't work (yesterday)

**Comment by jteresco** [comment]
http://tmtest.teresco.org/user/mapview.php?units=miles&u=terescoj&v

The "v" is the only important part to trigger the new "visible area" functionality.  You can leave off or replace the other two QS params.

**Comment by michihdeu** [comment]
Like it!

> Display city names like old Mapview in route table?

Does John Doe know what NY5TrkSch is? That it refers to Schenectady?
Well, with just one click the route is opened in HB and you get the city name there.

OTOH, one could want to copy the table to a text editor..... because it could really help to figure out the routes one has not yet clinched.... _(a button "copy to clipboard" might help and this might add the city name?)_

**Comment by michihdeu** [comment]
Maybe the wrong place but... I zoomed-out, moved the map to Europe and... well, it's still loading after 5 minutes... How should the feature work in the end? Only in combination with https://github.com/TravelMapping/Web/issues/211? Or how can I start at a desired location?

**Comment by jteresco** [comment]
> Maybe the wrong place but... I zoomed-out, moved the map to Europe and... well, it's still loading after 5 minutes... How should the feature work in the end? Only in combination with #211? Or how can I start at a desired location?

An implementation for #431 will address this.  Most people don't want to start browsing every time in Loudonville, New York, or at least don't want to have to pan half way around the world to find their area of interest.

**Comment by yakra** [comment]
>  Well, with just one click the route is opened in HB and you get the city name there.

This.
Full city names could potentially take up a lot of real estate onscreen. I like the idea of keeping the table tidier & less obtrusive.

**Comment by jteresco** [comment]
Assuming no objections to keeping the table entries on Mapview short, omitting city.
