### ISSUE TITLE
First HB table headline is not displayed when scrolled

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#44]
Please select a system with many routes and scroll down, for instance http://tm.teresco.org/devel/hb.php?sys=deua. The headline is the 2nd row like:

The "Select Route to Display" row is scrolled instead of fixed. The "System | Region | Route Name | ..." row is fixed though. That means that the first line is a route line. Checked with FF44 and IE11. It looks like:

deua	DEU	A2	DEU A2	active	deu.a002
System | Region | Route Name | ...
deua	DEU	A4 (Dresden)	DEU A4	active	deu.a004

**Comment by jteresco** [comment]
@michihdeu since the HB code has changed quite a bit, could you see if the issue you describe is still problematic?

**Comment by michihdeu** [comment]
Still the same: http://tmtest.teresco.org/hb/index.php?sys=deua.

**Comment by michihdeu** [comment]
A pic showing the issue: http://tm.teresco.org/forum/index.php?action=dlattach;topic=285.0;attach=33;image

**Comment by jteresco** [comment]
As I mentioned in the forum thread, I'm thinking it's a CSS issue and that the header staying put was intentional by the original author of the code.  I'm happy to try out any CSS improvement, but since it wasn't obvious to me, it's not something I can investigate now.

**Comment by Thing342** [comment]
The second headline is meant to float. I decided to not have the top headline float, as it would make the times when the table can be scrolled upwards less obvious. 
Going to mark this as wontfix unless someone has a major problem with this.

**Comment by michihdeu** [comment]
Well, I think it look damn ugly because the "floating" line is not at the top while there's a line above... There's already a scrollbar which indicates that you can scrol upwords.
