### ISSUE TITLE
Scrollable Mapview: Highlight clinched routes

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#440]
The table should highlight the routes 100% clinched of the selected user in a different color like it's done in HB table.

**Comment by jteresco** [comment]
Do we want that?  Existing Mapview doesn't.  Is this a place we'd want some sort of shading to indicate percentage of each route being clinched?

**Comment by michihdeu** [comment]
Only in combination with #442 
I thought it's the purpose of the **new table** (not saying of the scrollable map itself)

**Comment by yakra** [comment]
>  Is this a place we'd want some sort of shading to indicate percentage of each route being clinched?

I think so.

**Comment by michihdeu** [comment]
More opinions: http://forum.travelmapping.net/index.php?topic=3640.msg19033#msg19033

**Comment by jteresco** [comment]
Is there anything related to this Issue that needs to be addressed in the new Mapview on tmtest?

**Comment by michihdeu** [comment]
It's fine.
