### ISSUE TITLE
Scrollable Mapview: Select user in start box?

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#441]
Still in development, but we start with: http://tmtest.teresco.org/user/mapview.php?v

I don't know how the section box will look like when it will be live on the site, but it should be possible to select the user.

workaround: Add user name http://tmtest.teresco.org/user/mapview.php?v&u=michih ane reload the site.

Maybe just an issue because it's not yet integrated?

**Comment by jteresco** [comment]
This is (I think) only because you hadn't used tmtest recently enough to have the username cookie.  So I think it's not worth the clutter on the popup box to select a user when the vast majority of the time, it's coming from the cookie anyway.

**Comment by michihdeu** [comment]
sure.

How will it work on the production site travelmapping.net? How will I open mapview? When it is ensured that the cockie knows the user first, it's fine. If not, the user selection should be there.

If mapview will be opened as it is opened today - from user stats - it's fine.

However, I like the idea of opening mapview at a location I've never been before, e.g. Australia. It is currently not possible to open mapview (without editing the url) for a region or system (or location with scrollable mapview) I do not yet have mileage.

It would be useful to plan travel in advance. The current _focus_ of TM is on mapping travels, not on planning travels.

**Comment by michihdeu** [comment]
_sorry, I don't wanna open a can of worms 😉 I don't want to discourage you but appreciate your effort!_

**Comment by jteresco** [comment]
I'm not sure how best to link in this new functionality.  Perhaps on each user page, a link?  In that case it would have a u= from the cookie for sure.

I think the only time a control on this page for selecting the user would be useful to get started would be if someone's first-ever visit to the page came before any other page where a user would have been selected.

**Comment by michihdeu** [comment]
> if someone's first-ever visit to the page

When I close my browser, cookies are cleaned-up. That means, it happens to me every day.

**Comment by jteresco** [comment]
For both this once added and for the in-development topstats, changes in user and units should be stored in the cookie to be consistent.
