### ISSUE TITLE
Scrollable Mapview: Clinched and overall mileage for loaded segments only?

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#442]
The table shows the clinched and overall mileage for the whole route. Is it possible to limit it to the loaded graph segments? So that I can check the actual clinch status of the selected (loaded) area? An figure ou twhat I still have to chlinch here?

Should it be possible to switch the modes or should the "liimited" version be the only one?

**Comment by jteresco** [comment]
I considered this and decided to use only full route information for a few reasons.

- Does anyone worry about whether they've traveled all the routes on an arbitrary area that happens to fit in your browser at a given zoom level and map location?  I think most people are interested in regions and systems, and those stats are on other pages.
- The full-route traveled information is readily available from the DB while visible-only information would need to be computed on the fly on each pan/zoom.  The code wouldn't be difficult and the amount of time to do the computation would fairly small, though.
- We can't get finer than a per-segment granularity, meaning such numbers would always be inaccurate, with segments only partially-visible on the screen counting fully toward the stats.

**Comment by mapcat** [comment]
> * Does anyone worry about whether they've traveled all the routes on an arbitrary area that happens to fit in your browser at a given zoom level and map location?

To be honest that's what I expected to happen. When I looked at the default (Jim's travels around Albany) I noticed some of the roads were less than 100% and initially wondered how you hadn't managed to drive something within a few miles of your workplace. Then I saw that some of the routes were hundreds of miles long and realized it was including mileage outside the current view.

I'm not saying this needs to change, only that people might be confused by it initially.

**Comment by michihdeu** [comment]
> > Does anyone worry about whether they've traveled all the routes on an arbitrary area that happens to fit in your browser at a given zoom level and map location?
>
> To be honest that's what I expected to happen

Me too! I can plan my travels this way. Sure, it is difficult to adjust the map exactly around my location but..... why should I open mapview this way - and look at the table - when I cannot do that?

I would only use the table if that's possible. If not, I don't need the table.

> I'm not saying this needs to change, only that people might be confused by it initially.

I was confused first. I loaded the map where I've traveled all routes and wondered why the clinched mileage is not 100%.

**Comment by yakra** [comment]
I hadn't paid attention to the data in the tables yet, but my expectation would have been what's actually implemented,with info in the tables based on the route as a whole.

If it were me planning my travels based on what fits within a certain viewport, I'd just look at the clinched/unclinched colors onscreen, and not pay much attention to the table.

In the OP, @michihdeu wrote:
> Should it be possible to switch the modes or should the "liimited" version be the only one?

If this is implemented, it should be possible to switch modes.

**Comment by michihdeu** [comment]
> If it were me planning my travels based on what fits within a certain viewport, I'd just look at the clinched/unclinched colors onscreen, and not pay much attention to the table.

Agree, That's how I do it. But how to spot small unclinched segments when almost everything is clinched? I use the system or region table for that today.

Scrollable mapview opens new possibilities. It's no longer limited to regions or systems...

_again, all my comments.... if we didn't had the table on mapview at all, I would not miss anything._

**Comment by jteresco** [comment]
I'm thinking of something like this, assuming I wouldn't hit any snags in implementation details.  3 columns:

1) route list name
2) visible clinched 31.32/60.23 (52.0%)
3) route clinched 89.45/192.33 (46.5%)

Three concerns:

1) This would likely make the table a bit wider, an issue on small screens.
2) As noted above, the visible would be an estimate in that it would include segments only partially visible.  While I could do the math to clip out off-screen subsegments, I don't think I want to...
3) A buffer around the visible area to limit reloads for small pan operations as mentioned in #428 could make the estimates worse, or at best complicate the code since each segment would also need to be checked if it's actually on screen.

**Comment by jteresco** [comment]
I think I've got a decent compromise up on tmtest.  Check it out.

**Comment by michihdeu** [comment]
yep, fine to me!

**Comment by jteresco** [comment]
Please report any further problems or offer suggestions related to this new functionality in the Forum thread or in a new Issue here.
