### ISSUE TITLE
Scrollable Mapview: Hangs

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#443]
When you zoom in and out multiple times with mouse wheel - not too fast, just normal but multiple times, you'll get a movie for a couple of minutes till the browser tab hangs.

E.g., enter location "ulm", zoom out till you see whole Central Europe. Zoom in to the initial zoom level. Repeat three times. Wait about one minute till it freezes.

**Comment by jteresco** [comment]
I would like to see what I can do on #424 before looking into this, as I think what you describe might be a timing issue where multiple AJAX requests are being issued to read info from the DB with callbacks being invoked to process that data.

**Comment by mapcat** [comment]
(I left the same comment in #424)

Not sure if this is related to the slow response, but is it necessary to generate the table on each scroll, especially if a user is scrolling multiple times in quick succession? For example, I waited for the original location (Siena) to load fully, then scrolled to the west multiple times until it was focused on northern Ohio, and waited for the segments to be drawn. I don't know if the number of times the table regenerated matched the number of click-drags, but it populated with data from Pennsylvania at least twice, even though nothing from that state showed on the initial or final map.

**Comment by jteresco** [comment]
I expect recent changes have improved by not fixed this kind of problem.  I suspect it has to do with cases where multiple queries are in progress at once.

**Comment by mapcat** [comment]
As far as I can tell from testing today, this issue is no longer occurring.

**Comment by michihdeu** [comment]
It's much better but it still happens. Zoom out with mouse wheel till you see the whole planet. Zoom into Asia, out again, zoom into Africa, out, zoom into Europe,... I did it about 5...6 times and I'm anywhere in Greenland now. I only see the map, no graph, no table. The browser says "website is slowing down the browser do you want to stop it?" text is in German though 😉

**Comment by jteresco** [comment]
I don't think there's a bug here, just time taken by large queries and map updates.  When I've gotten the "page not responding" types of warnings, I've been able to have it continue and eventually the requested data is displayed.  It is possible with what you described, you've queued up a couple of large requests.
