### ISSUE TITLE
6-field format for user list files

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#445]
To be added when https://github.com/TravelMapping/DataProcessing/issues/58 is live.

> A new 6-field format is now supported:
> `Region1 Route1 Waypoint1 Region2 Route2 Waypoint2`
> The two routes must be in the same connected route.

Not under `First steps with email submission` but under `Advanced features`.
However, `More examples of how to break down your travels` describes the actual multi-region handling and must be changed too. Maybe splitting the chapter into two chapters `Multi-region segments` and `Beltways`.

t.b.d.

**Comment by jteresco** [comment]
I think just make it clear that the current way to specify still works and will continue to work.  The new format is strictly a convenience for mapping travels across boundaries.

**Comment by michihdeu** [comment]
Modify [.list file sorting](http://travelmapping.net/devel_new/participate.php#blanklines):
a) By travel
b) By system
c) By region (likely use of 4-field entries only)

https://github.com/TravelMapping/DataProcessing/issues/58#issuecomment-636434986

**Comment by michihdeu** [comment]
Current version:
`Many users break up list files into chunks by region or highway type to make it easier to read or manage.`

Version on next update:
`Many users break up list files into chunks by system, region or individual travel to make it easier to read or manage. We recommend sorting by system to keep the .list file small.`

Omit `or region` on purpose in the last sentence to be future-proof.

Future version:
`Many users break up list files into chunks by system, region or individual travel to make it easier to read or manage. We recommend sorting by system to enable using the multi-region .list file option and to keep the .list file small.`

**Comment by jteresco** [comment]
I'd just state it as this, and not "recommend" anything:

TM users organize their list files in different ways to make them easier to read and manage.  Some prefer to organize by system, region, or individual travel.  The order doesn't matter to the TM system, so do whatever works best for you.

**Comment by michihdeu** [comment]
If there are no objections, I'll change it tomorrow to:
`Many users break up list files into chunks by system, region or individual travel to make it easier to read or manage.`

**Comment by jteresco** [comment]
I think using the new showroute list entry tool should be mentioned in the manual once that version's up on the main site.

**Comment by michihdeu** [comment]
https://travelmapping.net/participate.php
