### ISSUE TITLE
Scrollable Mapview: omit devel systems

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#447]
http://forum.travelmapping.net/index.php?topic=3640.msg18912#msg18912

**Comment by jteresco** [comment]
Fixed on main site.

**Comment by mapcat** [comment]
This seems to have crept back in. cannf routes appear in the Vancouver, for example. I'm viewing http://travelmapping.net/user/mapview.php?units=miles&u=mapcat&rg=ID&v
