### ISSUE TITLE
HB: Systems with "devel" status should not be displayed by default

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#45]
The highway browser should only display active and preview systems by default. Systems in development should not be displayed because "normal end user" should not get in touch with them. 

However, it should be possible, for instance for TM collaborators, to browse devel systems.

I think there could be a simple check box to show the devel lines. I think the check box should be at a "hidden" position, e.g. below of the table, so that normal users don't see it at first glance.

See previous discussion about not including new devel systems in the system update list: https://github.com/TravelMapping/HighwayData/pull/410.

**Comment by vdeane** [comment]
I don't see the need to hide the checkbox.  While we wouldn't want someone to think they can map those systems when they can't, I don't see the need to make their existance "top secret".  The checkbox could be named something like "Show in development systems (incomplete/not mappable)".  CHM had many of the in development systems visible, even the boundaries for the maps.

**Comment by yakra** [comment]
I've opinion (#110) has evolved a bit -- I'm moving from ~~"I don't see much to gain in"~~  closer to "*There could be some benefit from* putting the time & effort into 'hide by default' functionality."

If added to the HB, I would like to see a cookie that remembers whether the box is checked or not, so I don't have to muck about with making sure a certain argument is contained in the URL.

**Comment by jteresco** [comment]
This isn't something likely to come to the top of my list any time soon, but I'll leave the issue open in case anyone wants to tackle it.

**Comment by jteresco** [comment]
This issue isn't relevant to the showroute.php that I'm hoping to take live very soon, but will be if I decide to tackle the route lookup portion of the old HB functionality.

**Comment by michihdeu** [comment]
The issue is open for so long and I don't remember that anyone complaint. I think there is no need for it. Closing.
