### ISSUE TITLE
Manual: DISCONNECTED_ROUTE datacheck error

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#454]
CONRTE_COORD_MISMATCH mismatched route endpoints within connected routes
FPs are not allowed: https://github.com/TravelMapping/Web/issues/455

http://forum.travelmapping.net/index.php?topic=3652.msg19014#msg19014

https://github.com/TravelMapping/DataProcessing/issues/337

**Comment by yakra** [comment]
Error code renamed DISCONNECTED_ROUTE.
Errors are reported in pairs.
There are 3 potential underlying causes.
http://forum.travelmapping.net/index.php?topic=3652.msg19104#msg19104
