### ISSUE TITLE
No FP entries for CONRTE_COORD_MISMATCH datacheck error

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#455]
datacheck.php should not provide FP entries for CONRTE_COORD_MISMATCH datacheck errors.

https://github.com/TravelMapping/DataProcessing/issues/337

**Comment by yakra** [comment]
#451 already has this covered.

**Comment by michihdeu** [comment]
No, it doesn't! Just the LABEL_TOO_LONG!

**Comment by yakra** [comment]
It does in fact have this covered:
It checks whether a given error code is ***not** a member* of the list of codes for which FPs are allowed. CONRTE_COORD_MISMATCH is not and will not be on that list.
https://github.com/TravelMapping/Web/pull/451/files

**Comment by yakra** [comment]
Oops - I see that `LABEL_TOO_LONG` was erroneously included on the list where FPs are allowed. Will remove.

**Comment by michihdeu** [comment]
>

> 
> 
> Oops - I see that `LABEL_TOO_LONG` was erroneously included on the list where FPs are allowed. Will remove.

😃 yep, that's why I was confused. I read it again and again now and was about to ask why the hell FPs for LABEL_TOO_LONG should be allowed!

**Comment by yakra** [comment]
https://github.com/TravelMapping/Web/commit/466b7db440abc75f6cd7af185759e2724f5386e9
