### ISSUE TITLE
Mapview: Falling through to Scrollable Mapview when rte= not found?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#456]
From @yakra on the forum:

http://travelmapping.net/user/mapview.php?units=miles&u=yakra&rte=A-30&sys=deua (what am I looking for, a Quebec Autoroute?) takes me to the TM Scrollable Mapview setup dialog, even though I didn't specify the &v qs param.

**Comment by jteresco** [comment]
I suspect I have an "else" that might need to be an "else if".

**Comment by jteresco** [comment]
Since the code that caused this has been ripped out with the version of Mapview that I hope will be going live before long, I'm going to close this one.

**Comment by jteresco** [comment]
Not fixing in the old version, as the code that cause this has been ripped out, but once rte= functionality is added to the new version, we should verify that this does not occur or at least decide that it's the desired functionality (if it is).

**Comment by yakra** [comment]
My expectation would be to ignore the bad param, as if http://travelmapping.net/user/mapview.php?units=miles&u=yakra&sys=deua had been entered

**Comment by jteresco** [comment]
The new Mapview should now cleanly leave you at the Siena College location on the map with "No Routes on Map" if whatever combination of QS params and values is specified ends up not matching anything.
