### ISSUE TITLE
Rounding in % clinched calculations?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#464]
From @mapcat on the forum:

New(?) bug: something hinky with the clinched % calculations.

https://drive.google.com/file/d/1SQjPO08fbYsGCnPbU6coQ3Jqj1PJWKok/view

Note US 9W, route overall: 129.14 out of 129.15. Yet I'm credited with 129.15 out of 129.15 here: http://tmtest.teresco.org/hb/?units=miles&u=mapcat&r=ny.us009w. And I'm credited with 129.14 out of 129.14 here: http://tmtest.teresco.org/user/mapview.php?units=miles&u=mapcat&rte=US9W

**Comment by jteresco** [comment]
The actual mileage as stored in the DB is 129.1445770264.  Need to see if two different ways are being used to round to 2 decimal places.  Guess: somewhere is getting it out as 129.145 and rounding up to 129.15, somewhere else has more digits and is rounding down to 129.14 (correctly).

Both JS and PHP are "helpful" by letting values convert back and forth between string and numeric representations.

**Comment by yakra** [comment]
I was worried about undoing some of the changes made in #348. I checked out a few routes in the HB and they looked good, however...
There's the cautionary tale of [that time a difference in Oscar's travels on ME103 of about the width of 40 human hairs was rounded off to about the length of a semi trailer](http://forum.travelmapping.net/index.php?topic=3014).
Even rounding to 4 decimal places, we still have the potential for that problem.
IMO, we should avoid rounding via SQL when extracting data from the DB, and instead round via PHP, introducing our loss of precision at the very end of the process just before display.

**Comment by jteresco** [comment]
Reopening as a reminder to do a review of all rounding to ensure we are always rounding last.  A lot of the original TM code tried to round in DB queries and some might still be around, as well as other places where we're just querying with default precision which is not always sufficient.

**Comment by mapcat** [comment]
Found some more examples here.

http://tmtest.teresco.org/user/mapview.php?units=miles&u=mapcat&sys=usai

Specifically these 3:
MO I-29
FL I-110
OH I-670

**Comment by jteresco** [comment]
Another place default precision from the query was not good enough, so I've forced it to give me 4 places.  Should be good now, thanks for the report.

**Comment by jteresco** [comment]
Please report examples where this is still a problem, if any are found.
