### ISSUE TITLE
Coloring of segments on maps

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#466]
Idea relevant to this: let Mapview users choose from among different criteria for coloring segments:

- clinched/not clinched and systems.csv colors (current functionality)
- number of users who have traveled and systems.csv colors
- color with same scheme as HDX uses when displaying graphs, based on the number of concurrent routes on each segment

_Originally posted by @jteresco in https://github.com/TravelMapping/Web/issues/277#issuecomment-633126042_

**Comment by jteresco** [comment]
I'm branching this off #277 and will close that Issue, as I think it's request would be taken care of by what is proposed here.

In Mapview and the HB and perhaps other places, we can offer multiple options for how to color/shade the segments on the map.

- Traveled or not by the current user.  In Mapview, this is done with systems.csv colors and different opacities to indicate traveled or not.  In the HB, it's currently either grey or pink.
- Frequency of travel by all TM users, or at least by the subset of TM users who have traveled the route/region/system at all.  This could retain systems.csv colors and use opacities to indicate travel frequency, or could use the same "heat map" color scheme being added to tables throughout the project.
- Color by number of concurrent highways on the segment (see above).
- A fixed color for all segments.
- Others?

**Comment by michihdeu** [comment]
> Frequency of travel by all TM users,

or just traveled by any TM user or not traveled at all.

**Comment by jteresco** [comment]
Of use or interest to have an option to color segments by visible length?  Red = shortest to Blue = longest, or the other way around?

**Comment by yakra** [comment]
> Of use or interest to have an option to color segments by visible length? Red = shortest to Blue = longest, or the other way around?

Not IMO

**Comment by michihdeu** [comment]
yep, I see no benefit.

**Comment by jteresco** [comment]
I don't think this should be done on the HB.  If people want to see something other than clinched/unclinched by the current user, they can use Mapview.  So I'm closing this one.
