### ISSUE TITLE
Missing WV shield(s)

### ISSUE THREAD

**Issue by rickmastfan67** [TravelMapping/Web#47]
I just happened to notice that only the WV routes 2-99 are rendering shields.  All routes 100+ don't even get the 'state abbreviation' shield like other states that don't have any shields yet in the DB.

Has shield: http://tm.teresco.org/devel/hb.php?r=wv.wv098
No shield: http://tm.teresco.org/devel/hb.php?r=wv.wv103

This might have to do with possibly no 3d shield, but I'm not sure.  Just thought I'd mention this so it could be looked into at least.

@Thing342 @jteresco

**Comment by theFXexpert** [comment]
It appears that [template_usawv_wide.svg](https://github.com/TravelMapping/Web/blob/master/shields/template_usawv_wide.svg) is just an empty SVG file.

**Comment by jteresco** [comment]
I've removed the template_usawv_wide.svg file and removed offending generated images from the cache.  Also removed template_usawv.svg for consistency of display.

**Comment by Thing342** [comment]
To be fixed in an upcoming bugfix pull request.

**Comment by Thing342** [comment]
Fixed via #85. Should be live on tmtest.
