### ISSUE TITLE
Manual: Concurrency check with mapview

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#478]
[Concurrency check](http://travelmapping.net/devel/manual/syserr.php#concurrency) currently describes the HDX option only. With the latest improvements to [mapview](http://travelmapping.net/user/mapview.php) improvements it is now possible to make the check here. Both options should be described but dealing with mapview is likely simpler.

However, mapview still lacks a proper region selection, see https://github.com/TravelMapping/Web/issues/475
Once this will be implemented (and mapview development will be settled*), we should add the option to the manual.

*No more behavior and wording changes.

**Comment by jteresco** [comment]
I think it's fine to add now, since rg= can be specified on mapview.php to load an entire region.  I do intend to add the options for #475 but not sure when.

**Comment by michihdeu** [comment]
But it must be done manually by editing the url.
The only link is from a user page if the user has any travel in the region.
