### ISSUE TITLE
WPT Editor: More datacheck error detection

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#480]
Some of the errors (like the ones related to illegal labels) could and should be detected in the WPT Editor.

**Comment by michihdeu** [comment]
Which errors do you mean? I'm only aware of #362 and #335

**Comment by michihdeu** [comment]
ah, sorry! You mean NEW Data checks. But these should be done to wpt editor AND the site update scripts!

**Comment by yakra** [comment]
> Some of the errors (like the ones related to illegal labels) could and should be detected in the WPT Editor.

Duplicate of #374
