### ISSUE TITLE
Manual: use relative links when possible

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#482]
As part of #337, I'm replacing a bunch of http:// links to the main site and the forum with https:// links, but really these should be relative links.  I'm not doing that now in case it's being done because of the old and new manuals coexisting, but this should be taken care of when the new manual goes live.

**Comment by jteresco** [comment]
Of course forum links should remain absolute, so it's just the ones that are within the main site that can be simplified when the time is right.

**Comment by michihdeu** [comment]
Thanks, I already wanted to start 😄 There are not many absolute links and it should be simple to find them.
