### ISSUE TITLE
Mapview: Place lookup failed messaging

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#485]
From @michihdeu in the Forum:

> When I type in something stupid, e.g. "ewfssr4r" there could be a message "invalid location" or "location not found" or whatever message.

The feedback is limited from Nominatim, but if any error is reported by Nominatim, it should be reported to the TM user.

**Comment by jteresco** [comment]
Feedback is very limited: either it worked or it didn't.  Introducing a popup message for cases where no matching location is found.  This doesn't mean the match makes any sense, but that's what we get from Nominatim.

**Comment by michihdeu** [comment]
The "yielded no results" box is fine to me.
