### ISSUE TITLE
Feature: HB: More accessible list,or drop down box to select regions

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#49]
Please refer to forum's discussion from:
http://tm.teresco.org/forum/index.php?topic=131.msg724#msg724.

> **MichiH**: Sweden and Norway only appear if you enter the (correct but unknown) country code in the region filter box
> 
> **Si**: I'd imagine that the issue of country codes will be sorted. A more accessible list, or a drop down box (like CHM had), or something.

**Comment by michihdeu** [comment]
There are currently two special "countries", Europe and Asia. Both have more than one system. I think they should only appear in the region browser (as soon as it is available) and it should be removed from the country list.

If the region selection will be a drop down box, I think it should be as follows:

`Asia`
`Europe`
`--------`
`Albania`
`Andorra`
`Armenia`
`Austria`
`Barbados`
....
`United Kingdom`
`USA`

It's just a proposal though. Maybe it should be discussed on the forum before implementiation.

**Comment by ajfarina** [comment]
I agree with that idea. It's not just Europe and Asia, however. Currently, countries with more than one region do not appear in the region list at all (Canada, China, India, Mexico, Russia, UK, US, etc.), so it is difficult to see an entire country as one would Germany or Tunisia. It would be nice to see these in there or a country drop-down, too.

As a suggestion, would it be possible in the short term to have those countries appear in the regions box? Then, to prevent it from becoming even more unwieldy, something a hyphen/dash/bullet appear before the individual regions (like "- Alberta" or "· Michigan") to help offset it?

As a longer-term suggestion, what would everyone think about a country drop-down box including all countries and a regions drop-down box that activates or changes if there are subdivisions available to view in the HB? This would be similar to what was implemented on the old site. Of course the issue might be that things would need to be very reorganized.

Thanks.

**Comment by michihdeu** [comment]
Similar discussion on the forum:
http://tm.teresco.org/forum/index.php?topic=276.msg1317#msg1317
http://tm.teresco.org/forum/index.php?topic=274.msg1302#msg1302
http://tm.teresco.org/forum/index.php?topic=274.msg1305#msg1305

**Comment by michihdeu** [comment]
This already works for a long time. Closing
