### ISSUE TITLE
region.php when a region has no active routes

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#495]
The recent addition of preview routes as the first systems in Chile uncovered a series of divide by 0 errors.  This is something that should be checked throughout.

**Comment by michihdeu** [comment]
Uruguay does also only have one preview system and it works!

**Comment by jteresco** [comment]
I believe this was addressed in most cases on the site a while ago, and in others when the railways side of the project was introduced.  Please open new issues if divide by zero or other errors are noticed.
