### ISSUE TITLE
HB: Zoom to Fit

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#498]
The Zoom to Fit link should be replaced with a JS call that fits the map to the bounds of the current waypoints rather than reloading all of the information from the DB.

**Comment by jteresco** [comment]
This should not result in any functionality loss.

**Comment by yakra** [comment]
It's convenient to get a link with only the `r=` parameter and no `units=` or `u=`, for pasting into the forum or GitHub without messing up people's cookies.

[Link Here](https://github.com/TravelMapping/Web/issues/385) capability could get us a link without `units=` or `u=`, but we'd have extraneous lat/lon/zoom that we'd have to clip off.

This is something I use rarely enough that removing it would probably not make much difference to me, but it's something to consider.

**Comment by jteresco** [comment]
Just implemented it in the new showroute (available soon for testing) and it's a whole lot faster so I'm going with it.
