### ISSUE TITLE
Datacheck web interface suggestions/problems

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#5]
Here's a place to put suggestions and bug reports on the datacheck web interface.

I'll start: I should make the entries in the in the first column links to the route generating the error's HB page.

**Comment by jteresco** [comment]
Should add an rg= parameter to filter by region.

**Comment by jteresco** [comment]
Straightforward, hopefully: break into 4 tables, one with all datacheck errors not flagged as FPs in active systems, one with all datacheck errors not flagged as FPs in in-devel systems, one with FP list entries that did not match any detected error, and one with datacheck errors that were successfully marked as FPs.

**Comment by jteresco** [comment]
Latest version has some of these: each datacheck page entry now has an HB link, and three of the four tables mentioned above exist (one with all datacheck errors not flagged as FPs in active systems, one with all datacheck errors not flagged as FPs in in-devel systems, and one with datacheck errors that were successfully marked as FPs) and are color-coded: pink for active unflagged, blue for in-devel unflagged, grey for flagged.

**Comment by jteresco** [comment]
Is there any value to putting a link on the datacheck page to the GitHub master copy of the file in addition to the link to its HB representation?  I thought it was trivial but I now believe it is not with our directory hierarchy on GitHub.

**Comment by jteresco** [comment]
If/when three tiers (active, in review, in dev) of systems are implemented, datacheck.php will need to break down accordingly.

**Comment by jteresco** [comment]
I think we're reasonably happy with the datacheck system, so I'm closing this.

**Comment by yakra** [comment]
> Should add an rg= parameter to filter by region.

I think this would be a worthwhile addition.

**Comment by jteresco** [comment]
OK, I will reopen and keep this on the list of things to do.  Not hard.

**Comment by yakra** [comment]
Thanks. An option to filter by multiple regions would be good too. Though if it didn't make it into production I wouldn't cry about it.

**Comment by jteresco** [comment]
rg= and sys= parameters and corresponding UI controls are in.  Also a new checkbox to show or not show marked FPs.  I don't think the effort to support multiple regions/systems at this time is worth the effort.  I am also thinking that the idea of filtering out VISIBLE_DISTANCE errors is not worth the trouble.  Open new issues for problems or other suggestions.

**Comment by yakra** [comment]
Thanks to @Thing342's [orClauseBuilder function](https://github.com/TravelMapping/Web/blame/09a176f30c6f80a321eb4017ced27bd6ee7933dc/lib/tmphpfuncs.php#L103-L126), filtering for multiple regions or systems or error codes was easy. The QS parameter support is there on lab2, just not the UI controls, so we've got to manually create our own URLs.
http://205.209.84.174/devel/datacheck.php?rg=me,mb
http://205.209.84.174/devel/datacheck.php?sys=usai,usausb
http://205.209.84.174/devel/datacheck.php?show=HIDDEN_TERMINUS,LABEL_SLASHES
http://205.209.84.174/devel/datacheck.php?hide=VISIBLE_DISTANCE,SHARP_ANGLE

**Comment by michihdeu** [comment]
@yakra You've fixed the error indicating two regions? That's great! I remember that I've reported it but couldn't find the issue right now.

This way, each highway data manager could store ONE link with all his regions. In combination to ignoring VD errors.... GREAT! 😃

**Comment by yakra** [comment]
> This way, each highway data manager could store ONE link with all his regions. In combination to ignoring VD errors.... GREAT!

http://205.209.84.174/devel/datacheck.php?rg=CT,MA,ME,NH,RI,KS,NE,OK,NJ,NY,TX,AB,MB,NB,NS,PE,NL&hide=VISIBLE_DISTANCE
