### ISSUE TITLE
Link broken: UTF-8 to Latin character table

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#505]
https://travelmapping.net/devel/manual/syshwylist.php#intlatin

`Excel doesn't cooperate with this, so if using Excel, consider downloading OpenOffice (it's free), or if you insist on using Excel, you must manually encode the characters. See the UTF-8 to Latin character table.`

The link is https://travelmapping.net/devel/manual/utfconvert.html but there is no `utfconvert.html` - and wasn't before the "activation" of the new manual structure (I still have a copy of the original set before my work has started)

@jteresco @yakra @si404
Do you remember why we didn't apply the page from CHM? Do you know what was displayed there - just a list or was there a converter? _I cannot find the page on http://web.archive.org/web/20190224004937/http://cmap.m-plex.com/index.php_
If it was just a list, maybe you know a good site anywhere on the web?
**Or, do we need the link at all?**

**Comment by jteresco** [comment]
It's been this long that no one noticed we didn't have the page, so I'm guessing it's irrelevant.   Maybe none of our highway data managers use Excel anyway.

**Comment by michihdeu** [comment]
I think @mapcat uses Excel and it'S possible that no one cares about the link since they know exactly what to do? The manual is also for (potential) new hwy data managers...

**Comment by jteresco** [comment]
In the case of new users, I think "don't use Excel, if you want a spreadsheet download OO" would be sufficient.

**Comment by michihdeu** [comment]
Link locally removed. The rest (Excel use etc.) should be addressed with #344. Closing.
