### ISSUE TITLE
Closing "Jump" popup window with "Cancel"...

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#515]
.... doesn't allow to open the "Jump" popup window again.

What happens:
1. https://travelmapping.net/user/mapview.php?v
2. Press Cancel -> Siena, no graph loaded
3. Press Jump -> nothing happens
4. Move map -> graph is loaded because "Always Update Visible Routes" is on per default

3. is a bug and I'm not sure that 4. is what should happen.

**Comment by jteresco** [comment]
The @michihdeu comment about step 4 is not addressed, but I prefer to leave it as-is.  I believe the "Cancel" button now functions appropriately, and the "Jump" button now works again (though likely reset to the default location) after a "Cancel" of a previous popup.
