### ISSUE TITLE
Feature: Ranking page

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#52]
I think almost everyone knows that it's missing but I couldn't find an issue.

It's requested to have a ranking page like we had on CHM: http://cmap.m-plex.com/stat/traveler.php.

> All our participating travelers are listed below along with their total progress in distance traveled and numbers of highways traveled and clinched across all the highways in our database. To clinch a highway means to travel along its entire length.
> Statistics for a single region and for a single highway system are available from the menu above. Those statistics may provide more interesting comparisons than those below.

**Comment by theFXexpert** [comment]
A simple stats page exists here for overall stats: http://tm.teresco.org/stat.php
But yeah, you can't get to it unless you know where is is.
Some filtering by System/Region would be nice down the road.

**Comment by michihdeu** [comment]
Cool, haven't know that this page exists :). I only knew http://tm.teresco.org/devlogs/allbyregion.csv.
Both contain "non-real user" like "eroads_all" or "ten-t_comp" which should be excluded one day.

**Comment by vdeane** [comment]
Perhaps the stats page could be rolled into the user page and used as the main index when no user is chosen?  That's how CHM had it arranged.

**Comment by jteresco** [comment]
I'm rearranging some things and adding more links.  Those changes are mostly still just at http://tmtest.teresco.org for now.  Please have a look there and send along suggestions.  Closing this issue since the requested feature does exist, just needs to be easier to find.
