### ISSUE TITLE
Design of user page

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#530]
Actual design:
![user page](https://user-images.githubusercontent.com/16516970/87868721-587d3000-c999-11ea-85e2-27dc34f3aafe.png)

I think that the size of the new text about scrollable maps and top stats should be aligned with the link to the log file
Wording should also be aligned (once "stats" once "statistics"). And, do we still need "new"? Should the links be here or is there a better place for it?

Suggestions:
- Move the "mapview" link from user page to the header between "Traveler Stats" and "Highway Browser".
- Use same font size for "top stats" as used for "log files"
- Move the (user) "top stats" link under "Overall stats" and use the smaller font size
- Link to https://travelmapping.net/shields/clinched.php should be _visible_ under "Overall stats" (currently "hidden" link on 3rd and 4th line of table)
- Leave the "log file" where it is _or_ move it to "Overall stats" to have all links there?
- Use "stats" only, not "statistics"

**Comment by jteresco** [comment]
This definitely could use a redesign.  I'd like to get more ideas, maybe also over in the forum.  What do people want on the user page?  How best to make it easy to find the log file, scrollable mapview, and topstats, without the ugly links we have there now?
