### ISSUE TITLE
wpt editor: wp coords in info window

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#539]
Just the same we have in HB. It helps to catch up the coords when one has moved a wp which must be applied to another route. One needs to find the right line in the wp list which is sometimes hard if there are hundreds of lines (web browser find feature is a help but when you've moved a wp, the label is shown (and found) many times.
![hb](https://user-images.githubusercontent.com/16516970/93706008-8d853a80-fb22-11ea-9300-3faf145ea875.png)

**Comment by yakra** [comment]
Addressed in #543.

Done not HB-style but rather HDX-style: the link is only the string **Coords.:**, and not the coordinate numbers themselves. I sometimes find it useful to copy that string, and this makes it slightly more convenient to do that.
