### ISSUE TITLE
wpt editor: Call GM with zoom level

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#569]
When we jump from wpt editor to GM, the link is always opened with zoom level 15. When you are zoomed out in wpt editor, jump to GM, it is always confusing and hard to find the route. I mean, I have the map in mind as I see it in wpt editor (usually OSM) and then when you wanna check someting on GM, the map looks totally different and I start to search "where I am".

I think it would help pretty much when the zoom level could be dynamic for the GM call.

**Comment by yakra** [comment]
Implemented for all the link buttons except GMSV.
Acme and HA can't zoom in all the way to level 19, but there's no harm in sending them a value too large; they just zoom in as far as they're able.

**Comment by michihdeu** [comment]
@yakra Thanks for implementing this! I checked it out and it is a great improvement! 😃
