### ISSUE TITLE
Possible errors with concurrency for US62 in Oklahoma

### ISSUE THREAD

**Issue by mvak36** [TravelMapping/Web#57]
I was browsing through the list of concurrencies on the old site and noticed that in Oklahoma, US62 has only  2 very short concurrencies with I-44 (in the Lawton area) and I-35 (in the OKC area). These are maybe a mile long. http://cmap.m-plex.com/stat/showconc.php?rg=ok

I checked my stats on the new site for US62 and it only shows that I have clinched a half-mile of US62. http://tm.teresco.org/devel/hb.php?r=ok.us062. I think it should be more like 10 miles because I have traveled the whole length of I-35 in the state. I know I can fix this by just adding a line in my list file for US62, but I thought I should bring this up here.

If someone does fix it, they would have to fix all the other interstate concurrencies for US62 in the state. Here's what I found:

I-44: Exit 40A to Exit 46
I-44: Exit 107 to Exit 115
I-240: Exit 1B to Exit 4A (I-35 Exit)
I-35: Exit 121B to Exit 130
I-40: Exit 221 to Exit 240

Note: I have also found similar issues with US64, US70, US77, US277(possibly), US281(possibly), and US412 (possibly). I have only checked concurrencies of US highways with Interstates.

**Comment by jteresco** [comment]
I've created a thread in our forum for this: http://tm.teresco.org/forum/index.php?topic=223.0

**Comment by jteresco** [comment]
Closing this issue here, as @yakra is addressing it on the forum.
