### ISSUE TITLE
Upgrade to MySQL 8.0

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#571]
I'd like to move up to MySQL 8.0 on TM's main server.  Given that @yakra has/had an instance of TM running under Linux with MySQL 8.0, I wouldn't expect many if any surprises.  My bigger concern is for the forum's SMF installation.

**Comment by jteresco** [comment]
https://forum.travelmapping.net/index.php?topic=4017.0

**Comment by yakra** [comment]
We could add back in the rank() functionality used on user/index.php that was tested & reverted on MySQL 5.7 <-> 8.0 grounds.
I've kept it live in the branch I use for lab2, merging master back in occasionally. Just need to add back in some of the new color coding functionality that didn't make it thru a merge conflict.

**Comment by jteresco** [comment]
Yes, related to #91

**Comment by jteresco** [comment]
With the unplanned switch to MariaDB on noreaster, we need to decide if there is still any benefit to trying to switch to MySQL 8.0.

**Comment by yakra** [comment]
I'm curious what happened on noreaster.

"[The upgrade unexpectedly removed the (now unsupported) MySQL version we were using.](https://forum.travelmapping.net/index.php?topic=6251)"
Did it install anything else in its place?

**Comment by jteresco** [comment]
No, it didn't install anything in place.  I am sure I missed some kind of warning about it being removed and just blindly said "yes, go ahead, FreeBSD ports manager, update everything!".   I tried MySQL 8.0 but it wasn't working, so I went with the more compatible MariaDB.

**Comment by jteresco** [comment]
MariaDB seems to be working out fine so far, no longer planning to move to MySQL 8.x.
