### ISSUE TITLE
Incorrect shields and links on clinched.php

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#583]
https://forum.travelmapping.net/index.php?topic=4039.msg21723;topicseen#msg21723

**Comment by jteresco** [comment]
Now thinking it might be a data processing problem.  Creating https://github.com/TravelMapping/DataProcessing/issues/400 but will leave this open for now as well in case there's a problem with the `clinched.php` query.

**Comment by jteresco** [comment]
So following on what I just put into https://github.com/TravelMapping/DataProcessing/issues/400 the problem here is that when you are looking at a connected route, the shield generated would come from the first root in the connected route.  In the problematic case here, that's in `LAO`, even though the travels on that connected route are only in `KHM`.

**Comment by jteresco** [comment]
The fact that the shield generated has the `LAO` in it is misleading.  It's not an `LAO` route, it's an "UNESCAP / ASEAN Asian Highways (for review)" route in the international system `asiahr`.  We don't see this in many systems like `usai`, `usaus`, and `eure`, since the state or country name isn't put into the generated shield.

**Comment by jteresco** [comment]
So the fix here is in part with the shield generator for cases where we don't have a template and it uses the region name above the route name in a generic square with rounded corners.

**Comment by jteresco** [comment]
The easier fix, which I am about to try out, is to add the `&cr` to the URL linked for each, as the `clinched.php` page deals with connected routes, not chopped routes.

**Comment by jteresco** [comment]
The `&cr` fix is live on the main site.  What to do about the misleading region name in the shields remains to be determined.

**Comment by jteresco** [comment]
Idea: create a simple "plain" set of shield templates for routes that span multiple regions and don't otherwise have a nice shield like `usai`, `usaus`, `eure`, etc.  In this case, it might make sense to have the "AH" instead of the region name on the top, and only the route number below.

Unfortunately, I don't think the primary author of the shield generator checks in on the project much.  Any volunteers?

**Comment by michihdeu** [comment]
Is this a duplicate of  #121?

**Comment by jteresco** [comment]
> Is this a duplicate of #121? Or related?

Definitely related, but I'd say a separate problem.

**Comment by jteresco** [comment]
With the recent progress on shield generation and the improvements to clinched.php, I'm going to go ahead and close this.
