### ISSUE TITLE
Redundant links on start page

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#59]
I think that the subsequent links are redundant now and should be removed from the start page:

Draft Highway Browser
User and System Logs, Statistical Summaries (click on an entry in the list that will appear)
User and System Logs, Statistical Summaries (with preview systems included as if active)

The HB is linked in the header, log files are linked on the Traveler Stats page now (great improvement :+1: .

**Comment by jteresco** [comment]
The start page is in need of some major reworking now that there's a lot more functionality to find.  So I'm going to close this issue on the understanding that what's on the main list of links on the start page will be put into nicer menus or other links.
