### ISSUE TITLE
bela shields

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#590]
The text in the shields appears to be right justified.  Please close if this behavior is correct.

**Comment by michihdeu** [comment]
Looks good.

**Comment by jteresco** [comment]
Reopening because there is a problem with bela shields in showroute.

https://forum.travelmapping.net/index.php?topic=288.msg21754#msg21754

**Comment by michihdeu** [comment]
The bug is a duplicate of #615 (hunm + belb)

"A1
  " including line break.

**Comment by michihdeu** [comment]
The spaces and line break are still there, but it looks good on showroute now.
