### ISSUE TITLE
chegts shields

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#593]
There appears to be a fancy shield on the web site:

https://www.myswitzerland.com/en-us/experiences/experience-tour/grand-tour-of-switzerland/

Maybe that can be brought in.

**Comment by michihdeu** [comment]
yep. Signs are [brown](https://www.google.com/maps/@47.4403126,7.327311,3a,15y,212.98h,85.01t/data=!3m6!1e1!3m4!1srtRBXcPwrf5Dcltg_SVvyA!2e0!7i16384!8i8192) with the [fancy shield](https://de.wikipedia.org/wiki/Grand_Tour_of_Switzerland#/media/Datei:Grand_Tour_of_Switzerland.jpg) on it

**Comment by jteresco** [comment]
Need to find an SVG version of the shield.

**Comment by michihdeu** [comment]
https://seeklogo.com/vector-logo/346309/grand-tour-of-switzerland
