### ISSUE TITLE
Shields for Routes Départementales in FRA

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#594]
Using the generic for now.  Maybe wait until all of the systems are done?

Some info:

https://forum.travelmapping.net/index.php?topic=288.msg21744#msg21744

**Comment by michihdeu** [comment]
It is the very same for all systems. Black on yellow. I already searched for a template on wikipedia before you've posted this but failed.

> Maybe wait until all of the systems are done?

We have a little bit more than 50% after about 18 months of work. My regions will be done in 2021 but the other regions.... 2025?

**Comment by jteresco** [comment]
Sounds like it's worth getting basic one soon with the right shape and colors, leaving the fancy fonts for another time.

**Comment by si404** [comment]
> Sounds like it's worth getting a basic one in soon with the right shape and colors, leaving the fancy fonts for another time.

I think this applies generally. Get it looking 'good enough' is far more important than the fine detail at the moment.

**Comment by theFXexpert** [comment]
I'm thinking using one template for all of frad may be ideal so that there aren't any duplicate shields/templates and one generated shield (for all of the D 1 routes for example) could be reused for all of the duplicated routes.

**Comment by michihdeu** [comment]
yep, one template for the [black/yellow D routes](https://www.google.com/maps/@45.7244695,3.1476906,3a,15y,162.13h,87.28t/data=!3m7!1e1!3m5!1sphcz8DG3rQ5MVBPju_-qTw!2e0!5s20180601T000000!7i13312!8i6656) would be fine. I'd omit the banner (= departement number).
And aother [white/blue M route](https://www.google.com/maps/@45.7575112,3.1274372,3a,15y,317.11h,93.69t/data=!3m6!1e1!3m4!1syu-s3YUtHAi-0Im6tnMuWw!2e0!7i16384!8i8192) template.

**Comment by michihdeu** [comment]
Thx! frad + fram look good. However, the shield radius seems to be a little bit to big. Not sure whether we need a radius at all. The A, B,... suffixes are usually smaller but I think it would be hard to implement this.
