### ISSUE TITLE
gbnb, nirb, irlr shields

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#597]
white background, black text, prefix, per

https://forum.travelmapping.net/index.php?topic=288.msg21744#msg21744

**Comment by theFXexpert** [comment]
@si404 Would it be better to use borders similar to the [Commons templates](https://commons.wikimedia.org/wiki/Category:Highway_shield_templates_of_the_United_Kingdom) or to leave the borders out since they don't seem use borders around the numbers themselves on guide signs.

**Comment by si404** [comment]
The borders are for the whole sign. So wikipedia's thinking was probably based on these sorts of signs:
https://www.sabre-roads.org.uk/wiki/index.php?title=File:R565_route_confirmation_sign_in_Kerry_-_Coppermine_-_11541.jpg
https://www.sabre-roads.org.uk/wiki/index.php?title=File:2012_0520_007.JPG

And Ireland tends to use the cartouche method with RCSs, ie giving the road number a separate sign
https://www.sabre-roads.org.uk/wiki/index.php?title=File:Route_confirmatory_sign_-_Coppermine_-_2635.JPG
https://www.sabre-roads.org.uk/wiki/index.php?title=File:E20_signed_on_the_N7_-_Coppermine_-_21057.JPG

Whereas the UK has the number as part of the rest of the sign.
https://www.sabre-roads.org.uk/wiki/index.php?title=File:A386_route_confirmation_sign_on_B3233!.jpg

So a case can be made for borders, and more so in Ireland, but I feel that whatever is easiest is fine.

**Comment by si404** [comment]
A further spanner in the works is that some R roads have begun being given [yellow cartouches](https://www.google.co.uk/maps/@53.2741058,-8.9198281,3a,40.8y,105.48h,83.92t/data=!3m6!1e1!3m4!1sFVNPryO_UGJE8TUvEO1chg!2e0!7i16384!8i8192) to mark them out as more important (its some of the former N roads bypassed by motorways).

However they are only on relatively recent signs, and many new signs don't have them. It seems to be something a couple of places have tried and that is.

But note the border around the yellow cartouche on directional signage, just to add to the annoyance. There's not, however, one around the R338 (or its white patch).
