### ISSUE TITLE
coords link in popup

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#613]
The coords link omits trailing zeros, rather than doing a `tofixed(6)` on both lat and lon.
For example, https://travelmapping.net/hb/showroute.php?r=ns.ns105&lat=45.974516&lon=-61.12737&zoom=18
If the zero had been stripped from lat rather than lon, I wouldn't have found the WPT lines. At least, not as easily.

The HDX behaves as desired.

**Comment by michihdeu** [comment]
Was there a recent change? I mean, I also rely on it for border wps. I wanted to be sure and tested it a few months ago and was sure it works.

I just found a case where a trailing zero was missing in a wpt file I've drafted this month....

**Comment by michihdeu** [comment]
Is it possible to compute all my wpt files and output lines where trailing zeros are missing?

**Comment by yakra** [comment]
Maybe it's just 'cuz I'm still working on that first cup of coffee, but I don't see what this has to do with NMPs. NMPs are calculated by distance between points, and are unaffected by presence or absence of trailing zeros. But anyway, to answer the question...

* On noreaster, go to the `hwy_data/` directory.
* Set up a `regions` variable of the regions you want to look at. Based on [this forum post](https://forum.travelmapping.net/index.php?topic=42.msg16963#msg16963), it might be
`regions='FRA-ARA FRA-BFC FRA-GES FRA-HDF FRA-IDF FRA-NOR BEL DNK LTU LUX NLD NOR SWE AUT CHE CZE DEU-BB DEU-BE DEU-BW DEU-BY DEU-HB DEU-HE DEU-HH DEU-MV DEU-NI DEU-NW DEU-RP DEU-SH DEU-SL DEU-SN DEU-ST DEU-TH HUN LIE HRV SVN ARG BRA ECU URY'`
It must be enclosed within quotes, all caps, and space-separated. No whitespace around the `=` sign.
* `for rg in $regions; do egrep -Hsv 'http://www.openstreetmap.org/\?lat=-?[0-9]+\.[0-9]{6}\&lon=-?[0-9]+\.[0-9]{6}' $rg/*/*.wpt | grep http:; done`
*(The grep command at the end filters out blank lines, notes in unprocessed files, etc.)*

**Comment by michihdeu** [comment]
Thanks! I already found 2 manually today....

e.g.:
FRA-GES/fragesm6ae/frages.m04006ae.wpt:A35 http://www.openstreetmap.org/?lat=48.524904&lon=7.66541

> Maybe it's just 'cuz I'm still working on that first cup of coffee, but I don't see what this has to do with NMPs. NMPs are calculated by distance between points, and are unaffected by presence or absence of trailing zeros.

I usually open all files of the region and search for the coords - the **full** osm link. Since I brought in incomplete links, M400 wasn't found when I've realigned the A35 wp. M400's A35 wp and A35's 7 wp are NMPs now

**Comment by yakra** [comment]
I also search for coords, full OSM link, though using my OS's find files feature, or more often lately from the commandline using grep.

I think the popup should do:
* A **minimum** of 6 digits, to expands coords with fewer sig figs to 6 digits as used in wptedit & normally included in .wpt files
* More digits if there are more in the file (and thus DB). After all, we can't find a .wpt line if our search term has too few digits.
(I have a few files with 7+ digits, and even the DB's single 8-digit coord, in my regions. I plan on editing these shortly.)
* I don't think there should be any problem with floating point imprecision (42.00000000008, 41.9999999993, etc); this kicks in at a way greater amount of sig figs than any WPTs have.
* Yeah. it's a bit more complicated to code, but I think would be worth it in the long run...

**Comment by jteresco** [comment]
This shouldn't be hard, and I hope to fix soon.

**Comment by jteresco** [comment]
I think the fix you're looking for was as easy as I thought and is now on tmdevel.teresco.org - look like it solves the problem?

**Comment by jteresco** [comment]
I just did the simple fix.

I'm think the cases of wpt lines with more than 6 digits should be handled separately.   A quick program to read every wpt and write it back out with trailing 0's added and digits beyond 6 removed.

**Comment by yakra** [comment]
> digits beyond 6 removed.

Sounds like truncation. Easier to do yes, though I'd prefer the precision of rounding.
A program to change everything to 6 digits won't help those trying to search for a given URL in the canonical WPTs in the repo itself, IMO.
If shortening the URLs bothers me that much... maybe I can change it myself? ;)

> look like it solves the problem?

https://tmdevel.teresco.org/hb/showroute.php?r=me.me188&lat=45.18012753&lon=-68.36940336&zoom=14
https://travelmapping.net/hb/showroute.php?r=me.me188&lat=45.18012753&lon=-68.36940336&zoom=14
I think also doing a `.tofixed(6)` on the coords themselves in the link *text* is counter-productive.
If a collaborator has `http://www.openstreetmap.org/?lat=45.18012753&lon=-68.36940336` in one file and `http://www.openstreetmap.org/?lat=45.180128&lon=-68.369403` in the other, there's no indication in the HB that the coords are different. A collaborator could end up saying "What the heck? The coords match, why do I have an NMP here?"
Leaving the coords at full precision (however the link address ends up notwithstanding) gives an indication the coords are different.

**Comment by jteresco** [comment]
Yes, rounding not truncation if a program is going to go through and fix all of the too-long URLs.

I guess I'm not seeing why showroute would have any data with more that 6 digits after we fix them all and get them in the repository and in the DB, so it doesn't need to be a tool to find NMPs that result from extra digits in the data.

**Comment by jteresco** [comment]
https://github.com/TravelMapping/DataProcessing/blob/master/SixDigits/SixDigits.java

**Comment by yakra** [comment]
If we fix everything to 6 digits, sure, the repo won't have anything longer. But there's no guarantee more cases won't sneak in in the future. I don't think there should be any expectation that all collabs "fix" their URLs; 6 digits is only how everything has traditionally been formatted, not a requirement.
While adding extra zeros to shorter URLs gives us the same coordinates, just with a different URL, removing zeros from a longer URL gives different coordinates from the point itself when copying the link.
Beyond just NMPs, this can break intersecting/concurrent routes. For me at least, copying coords from the popup in the HB is my go-to when creating new routes.

**Comment by michihdeu** [comment]
All of us have to deal with the files manually. There is a high risk that non-6-digit-coords will appear again. It sometimes happens to me with the last digits of the file when I create a new file and remove the empty line at the end.....

Since there are still some hwy data managers who don't want their files being touched.... and those who only have their own local copy and would not apply the corrected files....

I think that we should just try to avoid anyone catching up an incomplete on showroute, wpt editor or anywhere else on the site.

**Comment by yakra** [comment]
> Since there are still some hwy data managers who don't want their files being touched.... and those who only have their own local copy and would not apply the corrected files....

Also, ISTR someone somewhere sometime might have used the 7th decimal place to break concurrency detection.

**Comment by jteresco** [comment]
Is what's now on tmdevel an improvement?

**Comment by michihdeu** [comment]
> Is what's now on tmdevel an improvement?

No!

https://tmdevel.teresco.org/hb/showroute.php?r=fraara.d0001b01

The trailing zero on the info window of D1 but when you copy the link (context menu copy link) it is still missing: http://www.openstreetmap.org/?lat=46.38307&lon=4.883002

**Comment by jteresco** [comment]
Wait, I thought we didn't want to change the link text.

**Comment by michihdeu** [comment]
I only care about what I can pick up.

**Comment by yakra** [comment]
I prefer:
* link *address*:
  * pad to 6 decimal places iff <6.
  * go beyond 6 places iff point coords have greater precision.
* link *text* at full precision for whatever the coordinates are. I don't care about missing zeros here.

**Comment by jteresco** [comment]
I think maybe I now understand and maybe I now have something better on tmdevel.

**Comment by yakra** [comment]
https://tmdevel.teresco.org/hb/showroute.php?r=wi.wi107&lat=45.20555&lon=-89.73469&zoom=19
https://tmdevel.teresco.org/hb/showroute.php?r=ab.sheparkfwy&lat=53.518033&lon=-113.4396775&zoom=19
I like what I see!

**Comment by jteresco** [comment]
OK, good.  So as long as @michihdeu is ok with or at least I didn't break anything for him, I'll get this on the main site.

**Comment by michihdeu** [comment]
I've only checked https://tmdevel.teresco.org/hb/showroute.php?r=fraara.d0001b01 and it's fine. Thanks 👍

**Comment by jteresco** [comment]
Live on the main site.
