### ISSUE TITLE
Link to main user page from top link bar?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#622]
A request for a link to the user page from topstats in the forum got me thinking that it might be nice to have a link right to the user page in the link bar that's on all pages.  Thoughts?  I tend to use TM on devices at least as large as an ipad, and usually a laptop or desktop with plenty of browser real estate.  I don't want to cause annoyance to those who might try to access on phones.

**Comment by michihdeu** [comment]
I generally like the idea.

Would it be disabled if no user is selected?

**Comment by jteresco** [comment]
Candidate implementation on https://tmstage.teresco.org/

**Comment by jteresco** [comment]
> Would it be disabled if no user is selected?

Yes, the link is omitted if no user has been selected by URL or browser cookie.

**Comment by michihdeu** [comment]
Thanks 👍 
The user name is missing in the text on updates.php + devel.php + all over the manual etc. though.

**Comment by jteresco** [comment]
Ah, it doesn't work (yet) on pages that previously did not need to know about the user.

**Comment by jteresco** [comment]
I think all pages should have it now.

**Comment by jteresco** [comment]
I think we've got it.  Thanks to @michihdeu for the testing.
