### ISSUE TITLE
mapview loading times - line width?

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#628]
Just out of curiosity: Has the width of the graph lines we need to draw an influence on the loading times in mapview? Or is the loading time mostly only depending on getting the graph(s) from the database?

e.g. when loading: 
https://travelmapping.net/user/mapview.php?u=michih&rg=FRA-HDF,fra-idf,fra-nor,fra-ara,fra-bfc,fra-ges

if so, we might use a thiner line on low zoom level?

**Comment by jteresco** [comment]
I think Leaflet drawing a line would be a fixed cost at any width, but I really don't know.  Even if so, I think the actual rendering time is a tiny fraction of the cost.  It's all about waiting for the DB query to produce and package up the data, waiting for that data to be transmitted to your browser, then JS on your browser unpacking it and putting it onto the Leaflet map.

**Comment by michihdeu** [comment]
ok, thanks.
