### ISSUE TITLE
Options to include devel systems, exclude preview

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#64]
Soon we'll see both active and preview systems on most of the web front end pages.  I'd like to add options to exclude preview when someone wants to do so, and include devel.  The latter doesn't make sense for pages dealing with clinched segments, as the site update ignores any entries in list files for devel systems, but it might make sense to be able to include them on some maps to allow highway data contributors and peer reviewers to see them in another way.

**Comment by michihdeu** [comment]
It should generally be possible all over the site to select a minimum system status level.: devel, preview or active.

**Comment by jteresco** [comment]
I feel like we've moved past this.  OK to close?

**Comment by michihdeu** [comment]
I think it was desired to exclude preview systems back in 2016 (not by me!).
My wish to include devel systems is obsolete now.

I tend to closing.
