### ISSUE TITLE
jpne shields

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#682]
A tier 1 system w/o shield yet: https://travelmapping.net/hb/index.php?sys=jpne
Is there a specific shield?

@denishanson ?

**Comment by denishanson** [comment]
I believe a green? shield is commonly used, though the text on it varies a
lot. I'm on vacation right now, but when I return mid-November I will check
this. If you need an interim shield, use the Shuto Expwy shield.

**Comment by denishanson** [comment]
That response was for the jpntk shield question.

**Comment by denishanson** [comment]
National expressway shields exist but are infrequent. They are green,
hexagonal?, showing the route number with text underneath. I don't remember
if the text is the highway name or something else.

Most signage references to the expressways show E## as white text within a
green box.

**Comment by denishanson** [comment]
Found an example expressway shield

**Comment by michihdeu** [comment]
> If you need an interim shield, use the Shuto Expwy shield.

**I'm not going to work on this.** I just realized that some shields are missing, and went through the European tier 1 and tier 2 systems to collect available info. Many shields are _similar_ i.e. many are white/green. I just hope that anyone who is familar with svg files and our shield generator might work on this. Info should be available for starting the work.

I was surprised that there are still so many European tier 1+2 systems w/o shield, and also checked the systems from the rest of the world but w/o doing any research! Since @denishanson is familar with Japan, I thought I could trigger you to get required info (say, kinda "specification") so that anyone (Maybe @theFXexpert ?)  can start working on it if interested.

That's it. sorry, if anyone is annoyed by the high number of new issues 😃

**Comment by denishanson** [comment]
I am planning on creating the shield for Japanese national highways, so I
could attempt doing the other Japanese systems too. There are svg templates
for them on Wikipedia that I can work with.

**Comment by michihdeu** [comment]
jpne and jpnh are live on the production server now: https://forum.travelmapping.net/index.php?topic=4248.msg28178#msg28178

jpntk: https://github.com/TravelMapping/Web/issues/690
