### ISSUE TITLE
Sort functionality on main user page broken

### ISSUE THREAD

**Issue by ntallyn** [TravelMapping/Web#706]
The Active Systems Only Clinched header on the main user page (https://travelmapping.net/user/?units=miles&u=ntallyn&) doesn't sort. All of the other headers work as expected.

**Comment by jteresco** [comment]
Thanks for reporting the problem.  The very old and clunky table sorter library we are using has quite a few problems, and I'd like to replace it some time (see some old discussion in #183).  For this particular problem, it's one that's eluded me for a while.  I don't see what's different about the column that doesn't work compared to all the ones that work...

As always, I welcome other eyes looking at the code.  I must be missing something.  Here's where the header of that column is defined:

https://github.com/TravelMapping/Web/blob/1d96ef368d5928e039b20f8043e6b2a6a61cc1f3/user/index.php#L207

**Comment by jteresco** [comment]
Looks good now on the staging server with the new table library.  https://tmstage.teresco.org/user/?units=miles&u=ntallyn&
