### ISSUE TITLE
Mapview: Copy list of travelers to clipboard

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#722]
I'd like to be able to simply copy the user names from the info window. I request a quick and dirty solution only before a "final improvement" #468 might be implemted down the road.

![mapview](https://user-images.githubusercontent.com/16516970/170836134-3aae151a-616b-4875-9cbc-4216fd9c9a67.png)

**Comment by jteresco** [comment]
Looks simple enough.  https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

**Comment by jteresco** [comment]
@michihdeu What do you think about a double-click to copy to clipboard?

**Comment by michihdeu** [comment]
@jteresco On the travel list field before getting the list? Fine to me. The tooltip `Click then hover for list` should be extended though.

**Comment by jteresco** [comment]
Try out the initial implementation on https://tmstage.teresco.org/

The double-click highlights the number or the word "travelers" but the actual traveler list gets copied to the clipboard.  I am not sure if there should be any further feedback to the user.

**Comment by michihdeu** [comment]
Fine to me, thanks 😄 Good to go live.

**Comment by jteresco** [comment]
Live on the production site.
