### ISSUE TITLE
Manual: Update NMPs

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#723]
[syserr.php#nearmisspoint](https://travelmapping.net/devel/manual/syserr.php#nearmisspoint) needs to be updated according to the [latest modification by Jim](https://forum.travelmapping.net/index.php?topic=3656.msg27804#msg27804)

> https://travelmapping.net/logs/nmpbyregion now has an index file that has 2 links per NMP file: one to see the file contents and one to load right into HDX.  Note that many files are empty, so if you try those with HDX, it will not be especially interesting.

**Comment by jteresco** [comment]
I've edited the manual for these changes and put my current version on https://tmstage.teresco.org .

Please see if the changes look good both on [syserr.php](https://tmstage.teresco.org/devel/manual/syserr.php) and also [logs.php](https://tmstage.teresco.org/devel/logs.php).  Note that we removed the zip file as no one seems to use it.  Also note that the links to logs/nmpregion on these pages will not work, as the staging server does not have a copy of the logs.

**Comment by michihdeu** [comment]
I guess it's fine but I'd like to see the diffs on Github.

**Comment by jteresco** [comment]
https://github.com/TravelMapping/Web/commit/bd4132efa97b14930ae71390bf869f1e632be250

**Comment by michihdeu** [comment]
fine to me!

**Comment by jteresco** [comment]
Live on the main site.  Thanks for the reminder to keep our documentation up-to-date.
