### ISSUE TITLE
Table sorting

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#725]
Stats by region is sorted by active clinched but was sorted by active+preview clinched before the recent modifications. https://travelmapping.net/user/?u=michih has Sweden and Italy in the wrong order (3rd + 4th region)

**Comment by michihdeu** [comment]
Importance is higher now since there is no active railway system. The order is random at the moment.

**Comment by michihdeu** [comment]
Stats by system are also different to before the 2022 modification. It should be sorted by:
1. `% Clinched`
2. `Clinched (miles)`

It is currently only sorted by `% Clinched`.

**Comment by jteresco** [comment]
I'm going to experiment with the latest version of the [sortable library](https://github.com/tofsjonas/sortable) that we use for this.  It looks like there are some new options that might be just what we need.

**Comment by jteresco** [comment]
I think I've got it - @michihdeu see what you think.  It's on tmdevel and tmrail so far.

**Comment by michihdeu** [comment]
Checked both. Both fine. Thanks a lot 😄
