### ISSUE TITLE
MapQuest/OSM mapping tiles

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#73]
Just getting an issue posted for this.

http://tm.teresco.org/forum/index.php?topic=308.0

**Comment by ssoworld** [comment]
Can’t see the message – is this on a collaborator only forum?

**Comment by yakra** [comment]
> Can’t see the message – is this on a collaborator only forum?
Yes.

**Comment by Thing342** [comment]
Can somebody post the actual text? The link doesn't work for me.

**Comment by michihdeu** [comment]
The first post from @rickmastfan67 is:
> We'll need to do something about this before July 11th.
> https://twitter.com/richardf/status/743159548266020864
> https://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/
> https://twitter.com/MQDeveloper/status/745346555020976129
> https://developer.mapquest.com/documentation/leaflet-plugins/open

I think it's just a duplicate of https://github.com/TravelMapping/Web/issues/84 and the issue should be closed.

**Comment by Thing342** [comment]
I don't think it is. If I read this correctly, the MapQuest Open tiles will stop working on 11 July and need to be replaced. I'm not too familiar with the JS code that produces the maps, so I'll let somebody else handle this.

**Comment by michihdeu** [comment]
I think this issue is fixed and can be closed, isn't it?

**Comment by jteresco** [comment]
Best I can tell, we've moved away from MapQuest tiles.  Closing.
