### ISSUE TITLE
Restrict stats/rankings to "real" users

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#741]
Discussion so far in https://github.com/TravelMapping/DataProcessing/issues/71

Idea: by introducing a convention that non-"real" users (like the a3.list which are my travels in my current car only) have a specific pattern, such lists could be processed normally and stats and maps viewed when that user is selected, but those users would not count as travelers for stats and rankings.  And can this all be done on the web front end by updating SQL queries in various places?

**Comment by jteresco** [comment]
I might try to tackle this one soon.  Options for how to indicate that a .list file is not a "real user":

1. Put non-real user list in a subdirectory of `list_files` in the repository, or possibly all lists into one of two subdirectories, one for real users and one for non-real.
2. Add a separate file in the repository listing the names of non-real users.  If this were to be a .csv file, it could have other augmentations like a "real name" for the user, a home location, etc.
3. Require something special in the filenames for non-real users like starting with an underscore.

When a non-real user is identified during the site update process, a new table would need to be introduced into the DB to make this information available.

**Comment by jteresco** [comment]
Such information can now be added to the DB (https://github.com/TravelMapping/DataProcessing/issues/71) and it's time to think about how to use it on the front end.  Where should the "unranked" users be listed and not?

Thread here: https://forum.travelmapping.net/index.php?topic=6309.msg34907#msg34907

**Comment by michihdeu** [comment]
- [ ] Update [manual](https://travelmapping.net/participate.php)

**Comment by jteresco** [comment]
> * [ ]  Describe https://github.com/TravelMapping/UserData/blob/master/list_files/listfileinfo.csv in the [manual](https://travelmapping.net/participate.php)

Yes, for sure, once the implementation is finalized.
