### ISSUE TITLE
ON-418 shield

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#743]
@rickmastfan67 [wrote on the forum](https://forum.travelmapping.net/index.php?topic=5357):
> So, I'm not sure where the shield code is stored, but we can now safely swap it from the 'blue' shield to the 'normal' shield now for ON-418.
https://www.aaroads.com/forum/index.php?topic=59.msg2805583#msg2805583
>
> The shield change is due to them removing the tolls on ON-418 & ON-412 (no conformation of shield changes on it yet) in 2022.

**Comment by jteresco** [comment]
Making the easy fix: remove the ON418-specific shield and a generic one is now generated based on the standard canon template.

**Comment by rickmastfan67** [comment]
Nice, now I know where to look when I get conformation that they've changed the shields for ON-412. :)

**Comment by jteresco** [comment]
> Nice, now I know where to look when I get conformation that they've changed the shields for ON-412. :)

Yes, we'll just move its file into `arc`.
