### ISSUE TITLE
MariaDB for SQL

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#744]
I'm setting up a full test TM/METAL server on my MacBook Pro, and I'm trying MariaDB.  

I'm opening this Issue more as a place to put notes about any differences between the MySQL versions we've been using and MariaDB.

**Comment by jteresco** [comment]
When adding the users as in the https://github.com/TravelMapping/Web/blob/master/README.md file, the command did not work until I omitted `WITH mysql_native_password`.

**Comment by michihdeu** [comment]
We switch from the older daughter to the younger daughter? ;)
https://en.wikipedia.org/wiki/Michael_Widenius#Personal_life

**Comment by jteresco** [comment]
We are now successfully using MariaDB on the production server.
