### ISSUE TITLE
Mapview: Start at current location when loading?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#746]
If the information is available, should Mapview default to start at the current location?

**Comment by michihdeu** [comment]
no

**Comment by jteresco** [comment]
Another possibility: a cookie that takes you back to the last place you were.

**Comment by mapcat** [comment]
Really doesn't affect me, since I almost always load mapview via a saved link (to a state or group of states, or a system). Siena College is fine.

**Comment by jteresco** [comment]
There was no enthusiasm for this and it's not any kind of priority for me either, so I'm going to close this one.
