### ISSUE TITLE
wpt editor: railway tiles and overlays

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#758]
With the expansion to railways, specific tiles might help: https://forum.travelmapping.net/index.php?topic=444.msg31801#msg31801

**Comment by jteresco** [comment]
I am due to update the Leaflet version on the production server to the latest anyway.  That might be a good time to try out some new map tile options.

**Comment by michihdeu** [comment]
Tiles are online: https://tmdevel.teresco.org/wptedit/

**Comment by michihdeu** [comment]
@jteresco I guess that overlays are not (easily) possible? I don't mind since I'm very happy with the `ÖPNV map`. that's good enough for Europe....

**Comment by jteresco** [comment]
I haven't even looked at what would be needed to add overlays.  I'll make a new Issue about it so it's not forgotten.
