### ISSUE TITLE
findroute.php does no longer work for railways

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#763]
https://tmrail.teresco.org/hb/findroute.php does not load anymore. Same issue with Firefox and Edge. It worked last week though. It's still fine for [hwy ](https://travelmapping.net/hb/findroute.php).

```
Uncaught ReferenceError: findrouteSystems is not defined
    parseRouteInfo https://tmrail.teresco.org/lib/findroutefuncs.js:52
```

**Comment by jteresco** [comment]
I'm going to be traveling today but hope to take a look soon.

**Comment by michihdeu** [comment]
No hurry, I just checked what needs to be done before going to production 😉

**Comment by jteresco** [comment]
It looks like the problem is the use of double quotes in a system name: Chicago "L".

This causes the JS code generated by findroute.php to have a syntax error.  I can make a fix if we really want/need to support double quotes in system names, but the easy fix for now is to change that entry.

**Comment by michihdeu** [comment]
@Duke87ofST Is `"` essential for the system name or can we rename it to `Chicago Elevated`?

https://en.wikipedia.org/wiki/Chicago_%22L%22

**Comment by Duke87ofST** [comment]
If the quote marks break things go ahead and remove them.

**Comment by michihdeu** [comment]
Done. @jteresco you can close the issue when you will have run an update and checked findroute.php.

**Comment by michihdeu** [comment]
On second thought.... a data check might help, however, a the JS code fix seems to be the best solution to avoid that the issue might come again.

**Comment by jteresco** [comment]
I'd prefer disallowing double quotes and possibly a hard error if and when that happens.
