### ISSUE TITLE
Incorrect % for preview table on Stat.php

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#784]
https://travelmapping.net/stat.php

eg michih has 10.83% now but above the table, the correct 7.13% is output.

**Comment by jteresco** [comment]
Thanks for the report, @michihdeu. I had total mileages hard-coded in a couple of queries from testing related to the recent changes for unranked users.

**Comment by michihdeu** [comment]
Thanks, please update the railway server too @jteresco

**Comment by jteresco** [comment]
Done!
