### ISSUE TITLE
Google Maps API Keys

### ISSUE THREAD

**Issue by Thing342** [TravelMapping/Web#84]
As of 22 June 2016 (http://googlegeodevelopers.blogspot.com.au/2016/06/building-for-scale-updates-to-google.html), The Google Maps API now requires the use of keys for requests coming from new URLs, meaning that while the keyless production code maps will still work, anyone setting up a development environment (i.e. me on my new computer this week) will need to get API keys and write incompatible workaround code in order for their setups to work properly.

Thus, I propose that we:
A: Implement support for using GMaps API keys (I am working on this presently)
B: Get a Travel Mapping API key for production use.

**Comment by jteresco** [comment]
Thanks.  Is there much to implement?  I can get the API key when we're ready.  Do you know if there's any reason we should wait to implement this until we can switch from my domain to the travelmapping.net domain?

**Comment by Thing342** [comment]
I can submit a pull request for the code portion by the end of the day. I would recommend acting soon because it is now impossible to set up a working dev environment without using an API key.

**Comment by jteresco** [comment]
Yes, I'll get a key soon.

**Comment by jteresco** [comment]
I'm planning to put the version that uses a project-specific API key into production tomorrow if no problems are reported before then.

**Comment by jteresco** [comment]
I believe this is now resolved.
