### ISSUE TITLE
stat.php not using common DB access and other common code

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#87]
Somehow I missed updating this file when I revamped and reorganized code last month.  I hope to get to it tonight or tomorrow.  Shouldn't take long.

**Comment by jteresco** [comment]
I decided to take a quick look and I think it was a quick fix.  Please let me know if you notice any problems with the version on tmtest.teresco.org/stat.php .

**Comment by ssoworld** [comment]
I noticed the same issue in view.php as well.

**Comment by ssoworld** [comment]
never mind my last comment - that was deleted.

**Comment by jteresco** [comment]
I believe this is now resolved.
