### ISSUE TITLE
New waypoint editor

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#94]
We still use the CHM editor: http://cmap.m-plex.com/tools/wpteditv3/wptedit.html. I think we'll need our own wpt editor anytime because no one knows if CHM will go offline one day...

I think the editor required is very similar to our existing HB.

Please refer to the corresponding thread in the collaborator section of the forum: http://tm.teresco.org/forum/index.php?topic=351.

**Comment by Thing342** [comment]
Cross posted from the forum: 

> I don't do any waypoint editing, but is this what you're looking for? I have no idea who wrote it or if it's complete, but it seems to be similar to the CHM editor.

**Comment by michihdeu** [comment]
Let's discuss on the forum. This issue is just a reminder...

**Comment by jteresco** [comment]
To consider: instead of building a new standalone WPT editor, would it be better to integrate functionality into the HB or HDX?  Unfortunately, this is not looking like something that will get to the top of my priority queue for this summer.

**Comment by michihdeu** [comment]
I generally prefer having as less code as possible. Integration to the HDX sounds good 👍 HB is for "normal" users and shouldn't be overloaded.

**Comment by michihdeu** [comment]
A wp editor based on HDX would enable to add features like:

- Show nearby points of other routes
- Optional warning when a waypoint is moved and there is a waypoint with the same coodinates in another route

**Comment by jteresco** [comment]
I think at this point, we're likely committed to using the CHM wptedit program as adapted to fit into the current TM framework, and it addresses the main concern of this issue: that CHM is not actively maintained and could go away at any time.  I'd still like to write, or better yet have someone contribute, a brand new waypoint editor with many more features, but that is not happening on my end any time soon.  So I'm closing this issue.

**Comment by michihdeu** [comment]
I understand that we need to organize our backlog better but closing an issue just because it won't be implemented any time soon?

Sure, we could open it again but it's not possible to distinguish "closed because done" and "closed but open" issues. Maybe we should put it into a 2nd "long-term" backlog? I don't know if Github has anything like this.
